// Code generated by alef. DO NOT EDIT.

package htmltomarkdown

/*
#cgo CFLAGS: -I${SRCDIR}/../../crates/html-to-markdown-ffi/include
#include "html_to_markdown.h"
#include <stdlib.h>
#include <string.h>

extern int32_t goHtmlVisitorVisitElementStart(void* user_data, *C.char _ctx, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitElementEnd(void* user_data, *C.char _ctx, *C.char _output, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitText(void* user_data, *C.char _ctx, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitLink(void* user_data, *C.char _ctx, *C.char _href, *C.char _text, *C.char _title, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitImage(void* user_data, *C.char _ctx, *C.char _src, *C.char _alt, *C.char _title, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitHeading(void* user_data, *C.char _ctx, C.uint32_t _level, *C.char _text, *C.char _id, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitCodeBlock(void* user_data, *C.char _ctx, *C.char _lang, *C.char _code, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitCodeInline(void* user_data, *C.char _ctx, *C.char _code, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitListItem(void* user_data, *C.char _ctx, C.int32_t _ordered, *C.char _marker, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitListStart(void* user_data, *C.char _ctx, C.int32_t _ordered, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitListEnd(void* user_data, *C.char _ctx, C.int32_t _ordered, *C.char _output, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitTableStart(void* user_data, *C.char _ctx, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitTableRow(void* user_data, *C.char _ctx, *C.char _cells, C.int32_t _is_header, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitTableEnd(void* user_data, *C.char _ctx, *C.char _output, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitBlockquote(void* user_data, *C.char _ctx, *C.char _content, C.size_t _depth, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitStrong(void* user_data, *C.char _ctx, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitEmphasis(void* user_data, *C.char _ctx, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitStrikethrough(void* user_data, *C.char _ctx, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitUnderline(void* user_data, *C.char _ctx, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitSubscript(void* user_data, *C.char _ctx, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitSuperscript(void* user_data, *C.char _ctx, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitMark(void* user_data, *C.char _ctx, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitLineBreak(void* user_data, *C.char _ctx, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitHorizontalRule(void* user_data, *C.char _ctx, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitCustomElement(void* user_data, *C.char _ctx, *C.char _tag_name, *C.char _html, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitDefinitionListStart(void* user_data, *C.char _ctx, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitDefinitionTerm(void* user_data, *C.char _ctx, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitDefinitionDescription(void* user_data, *C.char _ctx, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitDefinitionListEnd(void* user_data, *C.char _ctx, *C.char _output, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitForm(void* user_data, *C.char _ctx, *C.char _action, *C.char _method, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitInput(void* user_data, *C.char _ctx, *C.char _input_type, *C.char _name, *C.char _value, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitButton(void* user_data, *C.char _ctx, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitAudio(void* user_data, *C.char _ctx, *C.char _src, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitVideo(void* user_data, *C.char _ctx, *C.char _src, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitIframe(void* user_data, *C.char _ctx, *C.char _src, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitDetails(void* user_data, *C.char _ctx, C.int32_t _open, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitSummary(void* user_data, *C.char _ctx, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitFigureStart(void* user_data, *C.char _ctx, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitFigcaption(void* user_data, *C.char _ctx, *C.char _text, char** out_result, char** out_error);
extern int32_t goHtmlVisitorVisitFigureEnd(void* user_data, *C.char _ctx, *C.char _output, char** out_result, char** out_error);
extern int32_t goHtmlVisitorName(void*, char**, char**);
extern int32_t goHtmlVisitorVersion(void*, char**, char**);
extern int32_t goHtmlVisitorInitialize(void*, char**);
extern int32_t goHtmlVisitorShutdown(void*, char**);
extern void goHtmlVisitorFreeUserData(void*);
*/
import "C"

import (
	"encoding/json"
	"fmt"
	"runtime/cgo"
	"unsafe"
)

// HtmlVisitor defines the Go interface for the HtmlVisitor trait.
type HtmlVisitor interface {
	// Name returns the plugin name.
	Name() string

	// Version returns the plugin version.
	Version() string

	// Initialize is called when the plugin is loaded.
	Initialize() error

	// Shutdown is called when the plugin is unloaded.
	Shutdown() error

	// visit_element_start.
	VisitElementStart(_ctx: map[string]interface{}) map[string]interface{}

	// visit_element_end.
	VisitElementEnd(_ctx: map[string]interface{}, _output: string) map[string]interface{}

	// visit_text.
	VisitText(_ctx: map[string]interface{}, _text: string) map[string]interface{}

	// visit_link.
	VisitLink(_ctx: map[string]interface{}, _href: string, _text: string, _title: string) map[string]interface{}

	// visit_image.
	VisitImage(_ctx: map[string]interface{}, _src: string, _alt: string, _title: string) map[string]interface{}

	// visit_heading.
	VisitHeading(_ctx: map[string]interface{}, _level: uint32, _text: string, _id: string) map[string]interface{}

	// visit_code_block.
	VisitCodeBlock(_ctx: map[string]interface{}, _lang: string, _code: string) map[string]interface{}

	// visit_code_inline.
	VisitCodeInline(_ctx: map[string]interface{}, _code: string) map[string]interface{}

	// visit_list_item.
	VisitListItem(_ctx: map[string]interface{}, _ordered: bool, _marker: string, _text: string) map[string]interface{}

	// visit_list_start.
	VisitListStart(_ctx: map[string]interface{}, _ordered: bool) map[string]interface{}

	// visit_list_end.
	VisitListEnd(_ctx: map[string]interface{}, _ordered: bool, _output: string) map[string]interface{}

	// visit_table_start.
	VisitTableStart(_ctx: map[string]interface{}) map[string]interface{}

	// visit_table_row.
	VisitTableRow(_ctx: map[string]interface{}, _cells: []string, _is_header: bool) map[string]interface{}

	// visit_table_end.
	VisitTableEnd(_ctx: map[string]interface{}, _output: string) map[string]interface{}

	// visit_blockquote.
	VisitBlockquote(_ctx: map[string]interface{}, _content: string, _depth: uint) map[string]interface{}

	// visit_strong.
	VisitStrong(_ctx: map[string]interface{}, _text: string) map[string]interface{}

	// visit_emphasis.
	VisitEmphasis(_ctx: map[string]interface{}, _text: string) map[string]interface{}

	// visit_strikethrough.
	VisitStrikethrough(_ctx: map[string]interface{}, _text: string) map[string]interface{}

	// visit_underline.
	VisitUnderline(_ctx: map[string]interface{}, _text: string) map[string]interface{}

	// visit_subscript.
	VisitSubscript(_ctx: map[string]interface{}, _text: string) map[string]interface{}

	// visit_superscript.
	VisitSuperscript(_ctx: map[string]interface{}, _text: string) map[string]interface{}

	// visit_mark.
	VisitMark(_ctx: map[string]interface{}, _text: string) map[string]interface{}

	// visit_line_break.
	VisitLineBreak(_ctx: map[string]interface{}) map[string]interface{}

	// visit_horizontal_rule.
	VisitHorizontalRule(_ctx: map[string]interface{}) map[string]interface{}

	// visit_custom_element.
	VisitCustomElement(_ctx: map[string]interface{}, _tag_name: string, _html: string) map[string]interface{}

	// visit_definition_list_start.
	VisitDefinitionListStart(_ctx: map[string]interface{}) map[string]interface{}

	// visit_definition_term.
	VisitDefinitionTerm(_ctx: map[string]interface{}, _text: string) map[string]interface{}

	// visit_definition_description.
	VisitDefinitionDescription(_ctx: map[string]interface{}, _text: string) map[string]interface{}

	// visit_definition_list_end.
	VisitDefinitionListEnd(_ctx: map[string]interface{}, _output: string) map[string]interface{}

	// visit_form.
	VisitForm(_ctx: map[string]interface{}, _action: string, _method: string) map[string]interface{}

	// visit_input.
	VisitInput(_ctx: map[string]interface{}, _input_type: string, _name: string, _value: string) map[string]interface{}

	// visit_button.
	VisitButton(_ctx: map[string]interface{}, _text: string) map[string]interface{}

	// visit_audio.
	VisitAudio(_ctx: map[string]interface{}, _src: string) map[string]interface{}

	// visit_video.
	VisitVideo(_ctx: map[string]interface{}, _src: string) map[string]interface{}

	// visit_iframe.
	VisitIframe(_ctx: map[string]interface{}, _src: string) map[string]interface{}

	// visit_details.
	VisitDetails(_ctx: map[string]interface{}, _open: bool) map[string]interface{}

	// visit_summary.
	VisitSummary(_ctx: map[string]interface{}, _text: string) map[string]interface{}

	// visit_figure_start.
	VisitFigureStart(_ctx: map[string]interface{}) map[string]interface{}

	// visit_figcaption.
	VisitFigcaption(_ctx: map[string]interface{}, _text: string) map[string]interface{}

	// visit_figure_end.
	VisitFigureEnd(_ctx: map[string]interface{}, _output: string) map[string]interface{}

}

//export goHtmlVisitorVisitElementStart
func goHtmlVisitorVisitElementStart(
	userData unsafe.Pointer,
	_ctx: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	// Call the method
	result := impl.VisitElementStart(go_ctx)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitElementEnd
func goHtmlVisitorVisitElementEnd(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_output: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_output := C.GoString(_output)

	// Call the method
	result := impl.VisitElementEnd(go_ctx, go_output)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitText
func goHtmlVisitorVisitText(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitText(go_ctx, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitLink
func goHtmlVisitorVisitLink(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_href: *C.char,
	_text: *C.char,
	_title: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_href := C.GoString(_href)

	go_text := C.GoString(_text)

	go_title := C.GoString(_title)

	// Call the method
	result := impl.VisitLink(go_ctx, go_href, go_text, go_title)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitImage
func goHtmlVisitorVisitImage(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_src: *C.char,
	_alt: *C.char,
	_title: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_src := C.GoString(_src)

	go_alt := C.GoString(_alt)

	go_title := C.GoString(_title)

	// Call the method
	result := impl.VisitImage(go_ctx, go_src, go_alt, go_title)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitHeading
func goHtmlVisitorVisitHeading(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_level: C.uint32_t,
	_text: *C.char,
	_id: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_level := uint32(_level)

	go_text := C.GoString(_text)

	go_id := C.GoString(_id)

	// Call the method
	result := impl.VisitHeading(go_ctx, go_level, go_text, go_id)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitCodeBlock
func goHtmlVisitorVisitCodeBlock(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_lang: *C.char,
	_code: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_lang := C.GoString(_lang)

	go_code := C.GoString(_code)

	// Call the method
	result := impl.VisitCodeBlock(go_ctx, go_lang, go_code)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitCodeInline
func goHtmlVisitorVisitCodeInline(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_code: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_code := C.GoString(_code)

	// Call the method
	result := impl.VisitCodeInline(go_ctx, go_code)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitListItem
func goHtmlVisitorVisitListItem(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_ordered: C.int32_t,
	_marker: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_ordered := _ordered != 0

	go_marker := C.GoString(_marker)

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitListItem(go_ctx, go_ordered, go_marker, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitListStart
func goHtmlVisitorVisitListStart(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_ordered: C.int32_t,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_ordered := _ordered != 0

	// Call the method
	result := impl.VisitListStart(go_ctx, go_ordered)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitListEnd
func goHtmlVisitorVisitListEnd(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_ordered: C.int32_t,
	_output: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_ordered := _ordered != 0

	go_output := C.GoString(_output)

	// Call the method
	result := impl.VisitListEnd(go_ctx, go_ordered, go_output)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitTableStart
func goHtmlVisitorVisitTableStart(
	userData unsafe.Pointer,
	_ctx: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	// Call the method
	result := impl.VisitTableStart(go_ctx)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitTableRow
func goHtmlVisitorVisitTableRow(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_cells: *C.char,
	_is_header: C.int32_t,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	var go_cells interface{}
	if _cells != nil {
		json.Unmarshal([]byte(C.GoString(_cells)), &go_cells)
	}

	go_is_header := _is_header != 0

	// Call the method
	result := impl.VisitTableRow(go_ctx, go_cells, go_is_header)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitTableEnd
func goHtmlVisitorVisitTableEnd(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_output: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_output := C.GoString(_output)

	// Call the method
	result := impl.VisitTableEnd(go_ctx, go_output)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitBlockquote
func goHtmlVisitorVisitBlockquote(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_content: *C.char,
	_depth: C.size_t,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_content := C.GoString(_content)

	go_depth := uint(_depth)

	// Call the method
	result := impl.VisitBlockquote(go_ctx, go_content, go_depth)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitStrong
func goHtmlVisitorVisitStrong(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitStrong(go_ctx, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitEmphasis
func goHtmlVisitorVisitEmphasis(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitEmphasis(go_ctx, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitStrikethrough
func goHtmlVisitorVisitStrikethrough(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitStrikethrough(go_ctx, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitUnderline
func goHtmlVisitorVisitUnderline(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitUnderline(go_ctx, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitSubscript
func goHtmlVisitorVisitSubscript(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitSubscript(go_ctx, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitSuperscript
func goHtmlVisitorVisitSuperscript(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitSuperscript(go_ctx, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitMark
func goHtmlVisitorVisitMark(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitMark(go_ctx, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitLineBreak
func goHtmlVisitorVisitLineBreak(
	userData unsafe.Pointer,
	_ctx: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	// Call the method
	result := impl.VisitLineBreak(go_ctx)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitHorizontalRule
func goHtmlVisitorVisitHorizontalRule(
	userData unsafe.Pointer,
	_ctx: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	// Call the method
	result := impl.VisitHorizontalRule(go_ctx)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitCustomElement
func goHtmlVisitorVisitCustomElement(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_tag_name: *C.char,
	_html: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_tag_name := C.GoString(_tag_name)

	go_html := C.GoString(_html)

	// Call the method
	result := impl.VisitCustomElement(go_ctx, go_tag_name, go_html)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitDefinitionListStart
func goHtmlVisitorVisitDefinitionListStart(
	userData unsafe.Pointer,
	_ctx: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	// Call the method
	result := impl.VisitDefinitionListStart(go_ctx)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitDefinitionTerm
func goHtmlVisitorVisitDefinitionTerm(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitDefinitionTerm(go_ctx, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitDefinitionDescription
func goHtmlVisitorVisitDefinitionDescription(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitDefinitionDescription(go_ctx, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitDefinitionListEnd
func goHtmlVisitorVisitDefinitionListEnd(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_output: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_output := C.GoString(_output)

	// Call the method
	result := impl.VisitDefinitionListEnd(go_ctx, go_output)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitForm
func goHtmlVisitorVisitForm(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_action: *C.char,
	_method: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_action := C.GoString(_action)

	go_method := C.GoString(_method)

	// Call the method
	result := impl.VisitForm(go_ctx, go_action, go_method)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitInput
func goHtmlVisitorVisitInput(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_input_type: *C.char,
	_name: *C.char,
	_value: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_input_type := C.GoString(_input_type)

	go_name := C.GoString(_name)

	go_value := C.GoString(_value)

	// Call the method
	result := impl.VisitInput(go_ctx, go_input_type, go_name, go_value)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitButton
func goHtmlVisitorVisitButton(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitButton(go_ctx, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitAudio
func goHtmlVisitorVisitAudio(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_src: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_src := C.GoString(_src)

	// Call the method
	result := impl.VisitAudio(go_ctx, go_src)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitVideo
func goHtmlVisitorVisitVideo(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_src: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_src := C.GoString(_src)

	// Call the method
	result := impl.VisitVideo(go_ctx, go_src)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitIframe
func goHtmlVisitorVisitIframe(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_src: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_src := C.GoString(_src)

	// Call the method
	result := impl.VisitIframe(go_ctx, go_src)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitDetails
func goHtmlVisitorVisitDetails(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_open: C.int32_t,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_open := _open != 0

	// Call the method
	result := impl.VisitDetails(go_ctx, go_open)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitSummary
func goHtmlVisitorVisitSummary(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitSummary(go_ctx, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitFigureStart
func goHtmlVisitorVisitFigureStart(
	userData unsafe.Pointer,
	_ctx: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	// Call the method
	result := impl.VisitFigureStart(go_ctx)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitFigcaption
func goHtmlVisitorVisitFigcaption(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_text: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_text := C.GoString(_text)

	// Call the method
	result := impl.VisitFigcaption(go_ctx, go_text)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorVisitFigureEnd
func goHtmlVisitorVisitFigureEnd(
	userData unsafe.Pointer,
	_ctx: *C.char,
	_output: *C.char,
	outError **C.char,
) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1  // error: invalid handle
	}

	var go_ctx interface{}
	if _ctx != nil {
		json.Unmarshal([]byte(C.GoString(_ctx)), &go_ctx)
	}

	go_output := C.GoString(_output)

	// Call the method
	result := impl.VisitFigureEnd(go_ctx, go_output)
	jsonBytes, _ := json.Marshal(result)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0  // success
}

//export goHtmlVisitorName
func goHtmlVisitorName(userData unsafe.Pointer, outResult **C.char, outError **C.char) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1
	}
	name := impl.Name()
	cName := C.CString(name)
	*outResult = cName
	return 0
}

//export goHtmlVisitorVersion
func goHtmlVisitorVersion(userData unsafe.Pointer, outResult **C.char, outError **C.char) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1
	}
	version := impl.Version()
	cVersion := C.CString(version)
	*outResult = cVersion
	return 0
}

//export goHtmlVisitorInitialize
func goHtmlVisitorInitialize(userData unsafe.Pointer, outError **C.char) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1
	}
	err := impl.Initialize()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goHtmlVisitorShutdown
func goHtmlVisitorShutdown(userData unsafe.Pointer, outError **C.char) C.int32_t {
	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(HtmlVisitor)
	if !ok {
		return 1
	}
	err := impl.Shutdown()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goHtmlVisitorFreeUserData
func goHtmlVisitorFreeUserData(userData unsafe.Pointer) {
	cgo.Handle(uintptr(unsafe.Pointer(userData))).Delete()
}

// RegisterHtmlVisitor registers a HtmlVisitor implementation with the C runtime.
func RegisterHtmlVisitor(impl HtmlVisitor) error {
	handle := cgo.NewHandle(impl)

	// Build the C vtable
	vtable := C.htm_html_visitor_VTable{
		visit_element_start: C.goHtmlVisitorVisitElementStart?,
		visit_element_end: C.goHtmlVisitorVisitElementEnd?,
		visit_text: C.goHtmlVisitorVisitText?,
		visit_link: C.goHtmlVisitorVisitLink?,
		visit_image: C.goHtmlVisitorVisitImage?,
		visit_heading: C.goHtmlVisitorVisitHeading?,
		visit_code_block: C.goHtmlVisitorVisitCodeBlock?,
		visit_code_inline: C.goHtmlVisitorVisitCodeInline?,
		visit_list_item: C.goHtmlVisitorVisitListItem?,
		visit_list_start: C.goHtmlVisitorVisitListStart?,
		visit_list_end: C.goHtmlVisitorVisitListEnd?,
		visit_table_start: C.goHtmlVisitorVisitTableStart?,
		visit_table_row: C.goHtmlVisitorVisitTableRow?,
		visit_table_end: C.goHtmlVisitorVisitTableEnd?,
		visit_blockquote: C.goHtmlVisitorVisitBlockquote?,
		visit_strong: C.goHtmlVisitorVisitStrong?,
		visit_emphasis: C.goHtmlVisitorVisitEmphasis?,
		visit_strikethrough: C.goHtmlVisitorVisitStrikethrough?,
		visit_underline: C.goHtmlVisitorVisitUnderline?,
		visit_subscript: C.goHtmlVisitorVisitSubscript?,
		visit_superscript: C.goHtmlVisitorVisitSuperscript?,
		visit_mark: C.goHtmlVisitorVisitMark?,
		visit_line_break: C.goHtmlVisitorVisitLineBreak?,
		visit_horizontal_rule: C.goHtmlVisitorVisitHorizontalRule?,
		visit_custom_element: C.goHtmlVisitorVisitCustomElement?,
		visit_definition_list_start: C.goHtmlVisitorVisitDefinitionListStart?,
		visit_definition_term: C.goHtmlVisitorVisitDefinitionTerm?,
		visit_definition_description: C.goHtmlVisitorVisitDefinitionDescription?,
		visit_definition_list_end: C.goHtmlVisitorVisitDefinitionListEnd?,
		visit_form: C.goHtmlVisitorVisitForm?,
		visit_input: C.goHtmlVisitorVisitInput?,
		visit_button: C.goHtmlVisitorVisitButton?,
		visit_audio: C.goHtmlVisitorVisitAudio?,
		visit_video: C.goHtmlVisitorVisitVideo?,
		visit_iframe: C.goHtmlVisitorVisitIframe?,
		visit_details: C.goHtmlVisitorVisitDetails?,
		visit_summary: C.goHtmlVisitorVisitSummary?,
		visit_figure_start: C.goHtmlVisitorVisitFigureStart?,
		visit_figcaption: C.goHtmlVisitorVisitFigcaption?,
		visit_figure_end: C.goHtmlVisitorVisitFigureEnd?,
		name: C.goHtmlVisitorName?,
		version: C.goHtmlVisitorVersion?,
		initialize: C.goHtmlVisitorInitialize?,
		shutdown: C.goHtmlVisitorShutdown?,
		free_user_data: C.goHtmlVisitorFreeUserData?,
	}

	// Call C registration
	cName := C.CString(impl.Name())
	defer C.free(unsafe.Pointer(cName))

	var cErr *C.char
	rc := C.htm_html_visitor_register(
		cName,
		unsafe.Pointer(&vtable),
		unsafe.Pointer(uintptr(handle)),
		&cErr,
	)

	if rc != 0 {
		msg := "failed to register HtmlVisitor"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.free(unsafe.Pointer(cErr))
		}
		handle.Delete()
		return fmt.Errorf("%s", msg)
	}

	return nil
}

// UnregisterHtmlVisitor unregisters a HtmlVisitor implementation.
func UnregisterHtmlVisitor(name string) error {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))

	var cErr *C.char
	rc := C.htm_html_visitor_unregister(cName, &cErr)

	if rc != 0 {
		msg := "failed to unregister HtmlVisitor"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.free(unsafe.Pointer(cErr))
		}
		return fmt.Errorf("%s", msg)
	}

	return nil
}
