// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import HtmlToMarkdownRs

/// E2e tests for category: metadata.
final class MetadataTests: XCTestCase {
    func testMetadataAuthorMeta() throws {
        // Extract author from <meta name='author'> tag
        let result = try convert("<html><head><title>Page</title><meta name=\"author\" content=\"Jane Doe\"></head><body><p>Content</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertEqual(result.metadata.document.author.trimmingCharacters(in: .whitespaces), "Jane Doe")
    }

    func testMetadataCanonicalUrl() throws {
        // Extract canonical URL from <link rel='canonical'> tag
        let result = try convert("<html><head><title>Page</title><link rel=\"canonical\" href=\"https://example.com/canonical-page\"></head><body><p>Content</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertEqual(result.metadata.document.canonical_url.trimmingCharacters(in: .whitespaces), "https://example.com/canonical-page")
    }

    func testMetadataDescriptionMeta() throws {
        // Extract description from <meta name='description'> tag
        let result = try convert("<html><head><title>Page</title><meta name=\"description\" content=\"This is the page description.\"></head><body><p>Content</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertEqual(result.metadata.document.description.trimmingCharacters(in: .whitespaces), "This is the page description.")
    }

    func testMetadataDublinCore() throws {
        // Extract Dublin Core metadata tags
        let result = try convert("<html><head><title>Scholarly Work</title><meta name=\"DC.title\" content=\"Principles of Knowledge Management\"><meta name=\"DC.creator\" content=\"Dr. Alice Johnson\"><meta name=\"DC.date\" content=\"2023-06-15\"><meta name=\"DC.subject\" content=\"Knowledge Management\"><meta name=\"DC.publisher\" content=\"Academic Press\"></head><body><p>This is a scholarly article.</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertTrue(result.content.contains("scholarly article"), "expected to contain: \("scholarly article")")
    }

    func testMetadataExtractAllImages() throws {
        // Extract all images from a document into metadata
        let result = try convert("<html><head><title>Gallery</title></head><body><img src=\"https://example.com/photo1.jpg\" alt=\"Photo 1\"><img src=\"https://example.com/photo2.png\" alt=\"Photo 2\"><img src=\"/local/image.webp\" alt=\"Local image\"></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertGreaterThanOrEqual(result.metadata.images.count, 2)
    }

    func testMetadataExtractAllLinks() throws {
        // Extract all links from a document into metadata
        let result = try convert("<html><head><title>Links Page</title></head><body><p>Visit <a href=\"https://example.com\">Example</a> or <a href=\"https://docs.example.com\">Docs</a>.</p><p>Also see <a href=\"/relative/path\">relative link</a> and <a href=\"mailto:hello@example.com\">email us</a>.</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertGreaterThanOrEqual(result.metadata.links.count, 2)
    }

    func testMetadataHeadersHierarchy() throws {
        // Extract heading hierarchy from document into metadata
        let result = try convert("<html><head><title>Docs</title></head><body><h1>Introduction</h1><h2>Getting Started</h2><h3>Installation</h3><h3>Configuration</h3><h2>Advanced Usage</h2><h3>Custom Options</h3></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertGreaterThanOrEqual(result.metadata.headers.count, 5)
    }

    func testMetadataKeywordsMeta() throws {
        // Extract keywords from <meta name='keywords'> tag
        let result = try convert("<html><head><title>Page</title><meta name=\"keywords\" content=\"rust, markdown, html, converter\"></head><body><p>Content</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertGreaterThanOrEqual(result.metadata.document.keywords.count, 1)
    }

    func testMetadataLangAttribute() throws {
        // Extract language from html lang attribute
        let result = try convert("<html lang=\"es\"><head><title>Spanish Page</title></head><body><h1>Hola Mundo</h1><p>Este es un documento en español.</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertTrue(result.content.contains("Hola Mundo"), "expected to contain: \("Hola Mundo")")
    }

    func testMetadataMicrodataSchemaArticle() throws {
        // Extract schema.org microdata for Article
        let result = try convert("<html><head><title>Article</title></head><body><article itemscope itemtype=\"https://schema.org/Article\"><h1 itemprop=\"headline\">Breaking News Today</h1><span itemprop=\"author\">Jane Reporter</span><span itemprop=\"datePublished\">2024-04-22</span><div itemprop=\"articleBody\"><p>The article content goes here with important information about the breaking news story.</p></div></article></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertTrue(result.content.contains("Breaking News Today"), "expected to contain: \("Breaking News Today")")
        XCTAssertTrue(result.content.contains("Jane Reporter"), "expected to contain: \("Jane Reporter")")
        XCTAssertTrue(result.content.contains("important information"), "expected to contain: \("important information")")
    }

    func testMetadataMicrodataSchemaBreadcrumb() throws {
        // Extract schema.org breadcrumb navigation microdata
        let result = try convert("<html><head><title>Navigation</title></head><body><nav itemscope itemtype=\"https://schema.org/BreadcrumbList\"><span itemprop=\"itemListElement\" itemscope itemtype=\"https://schema.org/ListItem\"><a itemprop=\"item\" href=\"https://example.com\"><span itemprop=\"name\">Home</span></a></span><span itemprop=\"itemListElement\" itemscope itemtype=\"https://schema.org/ListItem\"><a itemprop=\"item\" href=\"https://example.com/products\"><span itemprop=\"name\">Products</span></a></span><span itemprop=\"itemListElement\" itemscope itemtype=\"https://schema.org/ListItem\"><span itemprop=\"name\">Current Page</span></span></nav></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertTrue(result.content.contains("Home"), "expected to contain: \("Home")")
        XCTAssertTrue(result.content.contains("Products"), "expected to contain: \("Products")")
        XCTAssertTrue(result.content.contains("Current Page"), "expected to contain: \("Current Page")")
    }

    func testMetadataMicrodataSchemaOrganization() throws {
        // Extract schema.org microdata for Organization
        let result = try convert("<html><head><title>Company</title></head><body><div itemscope itemtype=\"https://schema.org/Organization\"><span itemprop=\"name\">Acme Corp</span><span itemprop=\"foundingDate\">2020</span><span itemprop=\"url\">https://acmecorp.example.com</span><span itemprop=\"logo\">https://acmecorp.example.com/logo.png</span></div></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertTrue(result.content.contains("Acme Corp"), "expected to contain: \("Acme Corp")")
        XCTAssertTrue(result.content.contains("2020"), "expected to contain: \("2020")")
    }

    func testMetadataMicrodataSchemaPerson() throws {
        // Extract schema.org microdata for Person
        let result = try convert("<html><head><title>Contact</title></head><body><div itemscope itemtype=\"https://schema.org/Person\"><span itemprop=\"name\">John Smith</span><span itemprop=\"email\">john@example.com</span><span itemprop=\"telephone\">+1-555-0100</span></div></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertTrue(result.content.contains("John Smith"), "expected to contain: \("John Smith")")
        XCTAssertTrue(result.content.contains("john@example.com"), "expected to contain: \("john@example.com")")
    }

    func testMetadataMicrodataSchemaProduct() throws {
        // Extract schema.org microdata for Product
        let result = try convert("<html><head><title>Product</title></head><body><div itemscope itemtype=\"https://schema.org/Product\"><h1 itemprop=\"name\">Awesome Widget</h1><span itemprop=\"description\">The best widget on the market</span><span itemprop=\"price\">29.99</span><span itemprop=\"priceCurrency\">USD</span><img itemprop=\"image\" src=\"widget.jpg\" alt=\"Widget\"><span itemprop=\"ratingValue\">4.5</span></div></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertTrue(result.content.contains("Awesome Widget"), "expected to contain: \("Awesome Widget")")
        XCTAssertTrue(result.content.contains("best widget"), "expected to contain: \("best widget")")
        XCTAssertTrue(result.content.contains("29.99"), "expected to contain: \("29.99")")
    }

    func testMetadataTextDirectionLtr() throws {
        // Extract text direction from lang attribute on html element
        let result = try convert("<html lang=\"en\" dir=\"ltr\"><head><title>LTR Document</title></head><body><p>This is left-to-right text.</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertTrue(result.content.contains("left-to-right text"), "expected to contain: \("left-to-right text")")
    }

    func testMetadataTextDirectionRtl() throws {
        // Extract right-to-left text direction
        let result = try convert("<html lang=\"ar\" dir=\"rtl\"><head><title>RTL Document</title></head><body><p>This is right-to-left text.</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertTrue(result.content.contains("right-to-left text"), "expected to contain: \("right-to-left text")")
    }

    func testMetadataTitleTag() throws {
        // Extract title from <title> tag
        let result = try convert("<html><head><title>My Page</title></head><body><p>Content</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertEqual(result.metadata.document.title.trimmingCharacters(in: .whitespaces), "My Page")
    }

    func testOgBasicTags() throws {
        // Extract og:title, og:description, and og:image from Open Graph meta tags
        let result = try convert("<html><head><title>Fallback Title</title><meta property=\"og:title\" content=\"OG Title\"><meta property=\"og:description\" content=\"OG description text.\"><meta property=\"og:image\" content=\"https://example.com/image.jpg\"></head><body><p>Content</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertEqual(result.metadata.document.open_graph.get("title").trimmingCharacters(in: .whitespaces), "OG Title")
        XCTAssertEqual(result.metadata.document.open_graph.get("description").trimmingCharacters(in: .whitespaces), "OG description text.")
        XCTAssertEqual(result.metadata.document.open_graph.get("image").trimmingCharacters(in: .whitespaces), "https://example.com/image.jpg")
    }

    func testOgMultipleTags() throws {
        // Extract multiple Open Graph tags including type, url, and site_name
        let result = try convert("<html><head><meta property=\"og:title\" content=\"Article Title\"><meta property=\"og:type\" content=\"article\"><meta property=\"og:url\" content=\"https://example.com/article\"><meta property=\"og:site_name\" content=\"Example Site\"><meta property=\"og:description\" content=\"An interesting article.\"><meta property=\"og:image\" content=\"https://example.com/article.jpg\"></head><body><article><p>Article content here.</p></article></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertEqual(result.metadata.document.open_graph.get("title").trimmingCharacters(in: .whitespaces), "Article Title")
        XCTAssertEqual(result.metadata.document.open_graph.get("type").trimmingCharacters(in: .whitespaces), "article")
        XCTAssertEqual(result.metadata.document.open_graph.get("url").trimmingCharacters(in: .whitespaces), "https://example.com/article")
        XCTAssertEqual(result.metadata.document.open_graph.get("site_name").trimmingCharacters(in: .whitespaces), "Example Site")
    }

    func testStructuredDataJsonLd() throws {
        // JSON-LD script tag is stripped from output (security) but metadata may be extracted
        let result = try convert("<html><head><title>Article</title><script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"Article\",\"headline\":\"My Article\",\"author\":{\"@type\":\"Person\",\"name\":\"Jane Doe\"},\"datePublished\":\"2024-01-15\"}</script></head><body><h1>My Article</h1><p>Article body text.</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertTrue(result.content.contains("My Article"), "expected to contain: \("My Article")")
    }

    func testStructuredDataMultipleJsonLd() throws {
        // Multiple JSON-LD blocks are all stripped from output
        let result = try convert("<html><head><title>Shop Page</title><script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"Product\",\"name\":\"Widget\",\"price\":\"9.99\"}</script><script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"BreadcrumbList\",\"itemListElement\":[{\"@type\":\"ListItem\",\"position\":1,\"name\":\"Home\"}]}</script></head><body><h1>Widget</h1><p>A great widget for all purposes.</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertTrue(result.content.contains("Widget"), "expected to contain: \("Widget")")
    }

    func testTwitterCardTags() throws {
        // Extract Twitter card meta tags
        let result = try convert("<html><head><meta name=\"twitter:card\" content=\"summary_large_image\"><meta name=\"twitter:site\" content=\"@examplesite\"><meta name=\"twitter:title\" content=\"Twitter Card Title\"><meta name=\"twitter:description\" content=\"Twitter card description.\"><meta name=\"twitter:image\" content=\"https://example.com/twitter-image.jpg\"></head><body><p>Content</p></body></html>")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
        XCTAssertEqual(result.metadata.document.twitter_card.get("card").trimmingCharacters(in: .whitespaces), "summary_large_image")
        XCTAssertEqual(result.metadata.document.twitter_card.get("title").trimmingCharacters(in: .whitespaces), "Twitter Card Title")
        XCTAssertEqual(result.metadata.document.twitter_card.get("description").trimmingCharacters(in: .whitespaces), "Twitter card description.")
    }

}
