// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import HtmlToMarkdownRs

/// E2e tests for category: visitor.
final class VisitorTests: XCTestCase {
    func testVisitorAudioCustom() throws {
        // Visitor replaces audio element with custom output
        let result = try convert("<p>Listen to this: <audio src=\"podcast.mp3\" controls></audio></p>")
        XCTAssertTrue(result.content.contains("[AUDIO: podcast.mp3]"), "expected to contain: \("[AUDIO: podcast.mp3]")")
        XCTAssertTrue(result.content.contains("Listen to this:"), "expected to contain: \("Listen to this:")")
    }

    func testVisitorAudioSkip() throws {
        // Visitor removes audio elements from output
        let result = try convert("<p>Background music:</p><audio src=\"music.ogg\" autoplay></audio><p>Enjoy!</p>")
        XCTAssertTrue(result.content.contains("Background music:"), "expected to contain: \("Background music:")")
        XCTAssertTrue(result.content.contains("Enjoy!"), "expected to contain: \("Enjoy!")")
        XCTAssertFalse(result.content.contains("music.ogg"), "expected NOT to contain: \("music.ogg")")
    }

    func testVisitorButtonCustom() throws {
        // Visitor replaces button with bracketed text
        let result = try convert("<p>Confirm action: <button type=\"submit\">Click me</button> or <button type=\"reset\">Cancel</button></p>")
        XCTAssertTrue(result.content.contains("[BTN:Click me]"), "expected to contain: \("[BTN:Click me]")")
        XCTAssertTrue(result.content.contains("[BTN:Cancel]"), "expected to contain: \("[BTN:Cancel]")")
        XCTAssertTrue(result.content.contains("Confirm action:"), "expected to contain: \("Confirm action:")")
    }

    func testVisitorButtonSkip() throws {
        // Visitor removes all buttons from output
        let result = try convert("<p>Actions available: <button>Save</button> <button>Delete</button> <button>Export</button></p>")
        XCTAssertTrue(result.content.contains("Actions available:"), "expected to contain: \("Actions available:")")
        XCTAssertFalse(result.content.contains("Save"), "expected NOT to contain: \("Save")")
        XCTAssertFalse(result.content.contains("Delete"), "expected NOT to contain: \("Delete")")
        XCTAssertFalse(result.content.contains("Export"), "expected NOT to contain: \("Export")")
    }

    func testVisitorContinueDefault() throws {
        // Visitor continue action preserves default conversion
        let result = try convert("<p>Hello <strong>World</strong></p>")
        XCTAssertTrue(result.content.contains("**World**"), "expected to contain: \("**World**")")
    }

    func testVisitorCustomBlockquote() throws {
        // Visitor replaces blockquote with custom format
        let result = try convert("<blockquote><p>A wise quote.</p></blockquote>")
        XCTAssertTrue(result.content.contains("QUOTE:"), "expected to contain: \("QUOTE:")")
        XCTAssertTrue(result.content.contains("A wise quote."), "expected to contain: \("A wise quote.")")
    }

    func testVisitorCustomEmphasis() throws {
        // Visitor replaces emphasis with custom output
        let result = try convert("<p>This is <em>important</em> text.</p>")
        XCTAssertTrue(result.content.contains(">>>important<<<"), "expected to contain: \(">>>important<<<")")
        XCTAssertFalse(result.content.contains("*important*"), "expected NOT to contain: \("*important*")")
    }

    func testVisitorCustomHeading() throws {
        // Visitor replaces heading with custom format
        let result = try convert("<h2>Section Title</h2><p>Content below heading.</p>")
        XCTAssertTrue(result.content.contains("--- Section Title ---"), "expected to contain: \("--- Section Title ---")")
        XCTAssertFalse(result.content.contains("## Section Title"), "expected NOT to contain: \("## Section Title")")
        XCTAssertTrue(result.content.contains("Content below heading."), "expected to contain: \("Content below heading.")")
    }

    func testVisitorCustomImage() throws {
        // Visitor replaces image with custom output using template
        let result = try convert("<img src=\"banner.png\" alt=\"Banner\">")
        XCTAssertTrue(result.content.contains("[Image: Banner]"), "expected to contain: \("[Image: Banner]")")
        XCTAssertFalse(result.content.contains("banner.png"), "expected NOT to contain: \("banner.png")")
    }

    func testVisitorCustomLinkFormat() throws {
        // Visitor reformats links using template interpolation
        let result = try convert("<p>Visit <a href=\"https://example.com\">Example</a> for more info.</p>")
        XCTAssertTrue(result.content.contains("Example (https://example.com)"), "expected to contain: \("Example (https://example.com)")")
        XCTAssertFalse(result.content.contains("[Example]"), "expected NOT to contain: \("[Example]")")
    }

    func testVisitorCustomLinkStatic() throws {
        // Visitor replaces link with static custom output
        let result = try convert("<a href=\"https://example.com\">Click here</a>")
        XCTAssertTrue(result.content.contains("[REDACTED LINK]"), "expected to contain: \("[REDACTED LINK]")")
        XCTAssertFalse(result.content.contains("example.com"), "expected NOT to contain: \("example.com")")
    }

    func testVisitorCustomOutput() throws {
        // Visitor custom action replaces element output
        let result = try convert("<h1>Original Heading</h1>")
        XCTAssertTrue(result.content.contains("## REPLACED HEADING"), "expected to contain: \("## REPLACED HEADING")")
        XCTAssertFalse(result.content.contains("# Original Heading"), "expected NOT to contain: \("# Original Heading")")
    }

    func testVisitorDefinitionListCustom() throws {
        // Visitor customizes definition list items
        let result = try convert("<dl><dt>HTML</dt><dd>HyperText Markup Language</dd><dt>CSS</dt><dd>Cascading Style Sheets</dd></dl>")
        XCTAssertTrue(result.content.contains("**HTML**"), "expected to contain: \("**HTML**")")
        XCTAssertTrue(result.content.contains("**CSS**"), "expected to contain: \("**CSS**")")
        XCTAssertTrue(result.content.contains("HyperText Markup Language"), "expected to contain: \("HyperText Markup Language")")
    }

    func testVisitorDefinitionListCustomFormat() throws {
        // Visitor formats definition lists with custom templates
        let result = try convert("<dl><dt>Python</dt><dd>A high-level programming language</dd><dt>JavaScript</dt><dd>A scripting language for web browsers</dd></dl>")
        XCTAssertTrue(result.content.contains("### Python"), "expected to contain: \("### Python")")
        XCTAssertTrue(result.content.contains("### JavaScript"), "expected to contain: \("### JavaScript")")
        XCTAssertTrue(result.content.contains("> A high-level programming language"), "expected to contain: \("> A high-level programming language")")
        XCTAssertTrue(result.content.contains("> A scripting language for web browsers"), "expected to contain: \("> A scripting language for web browsers")")
    }

    func testVisitorDefinitionListSkip() throws {
        // Visitor skips definition list items from output
        let result = try convert("<p>Glossary:</p><dl><dt>Term A</dt><dd>Definition of term A</dd><dt>Term B</dt><dd>Definition of term B</dd></dl><p>End of glossary</p>")
        XCTAssertTrue(result.content.contains("Glossary:"), "expected to contain: \("Glossary:")")
        XCTAssertTrue(result.content.contains("End of glossary"), "expected to contain: \("End of glossary")")
        XCTAssertFalse(result.content.contains("Term A"), "expected NOT to contain: \("Term A")")
        XCTAssertFalse(result.content.contains("Definition"), "expected NOT to contain: \("Definition")")
    }

    func testVisitorDetailsSummaryCustom() throws {
        // Visitor customizes details/summary disclosure elements
        let result = try convert("<details><summary>Click to expand</summary><p>This content is initially hidden.</p><p>But can be revealed by the user.</p></details>")
        XCTAssertTrue(result.content.contains("[EXPANDABLE] Click to expand"), "expected to contain: \("[EXPANDABLE] Click to expand")")
        XCTAssertTrue(result.content.contains("This content is initially hidden."), "expected to contain: \("This content is initially hidden.")")
    }

    func testVisitorDetailsSummarySkip() throws {
        // Visitor removes details/summary elements entirely
        let result = try convert("<p>Main content here.</p><details><summary>Hidden section</summary><p>Secret details</p></details><p>More main content.</p>")
        XCTAssertTrue(result.content.contains("Main content here."), "expected to contain: \("Main content here.")")
        XCTAssertTrue(result.content.contains("More main content."), "expected to contain: \("More main content.")")
        XCTAssertFalse(result.content.contains("Hidden section"), "expected NOT to contain: \("Hidden section")")
        XCTAssertFalse(result.content.contains("Secret details"), "expected NOT to contain: \("Secret details")")
    }

    func testVisitorFigureCustom() throws {
        // Visitor customizes figure and figcaption elements
        let result = try convert("<article><h1>Article Title</h1><p>Introduction paragraph.</p><figure><img src=\"diagram.png\" alt=\"System architecture diagram\"><figcaption>Figure 1: System Architecture</figcaption></figure><p>Explanation of the figure.</p></article>")
        XCTAssertTrue(result.content.contains("Article Title"), "expected to contain: \("Article Title")")
        XCTAssertTrue(result.content.contains("*Figure 1: System Architecture*"), "expected to contain: \("*Figure 1: System Architecture*")")
        XCTAssertTrue(result.content.contains("Explanation of the figure."), "expected to contain: \("Explanation of the figure.")")
    }

    func testVisitorFigureCustomWrap() throws {
        // Visitor wraps figure content with custom formatting
        let result = try convert("<section><h2>Gallery</h2><figure><img src=\"photo1.jpg\" alt=\"Photo\"><figcaption>Beautiful sunset</figcaption></figure></section>")
        XCTAssertTrue(result.content.contains("[FIGURE]"), "expected to contain: \("[FIGURE]")")
        XCTAssertTrue(result.content.contains("[/FIGURE]"), "expected to contain: \("[/FIGURE]")")
        XCTAssertTrue(result.content.contains("Gallery"), "expected to contain: \("Gallery")")
    }

    func testVisitorFigureSkip() throws {
        // Visitor removes figure elements with their captions
        let result = try convert("<p>See the chart below:</p><figure><img src=\"chart.svg\"><figcaption>Revenue Trends 2020-2024</figcaption></figure><p>As shown in the chart above.</p>")
        XCTAssertTrue(result.content.contains("See the chart below:"), "expected to contain: \("See the chart below:")")
        XCTAssertTrue(result.content.contains("As shown in the chart above."), "expected to contain: \("As shown in the chart above.")")
        XCTAssertFalse(result.content.contains("Revenue Trends"), "expected NOT to contain: \("Revenue Trends")")
        XCTAssertFalse(result.content.contains("chart.svg"), "expected NOT to contain: \("chart.svg")")
    }

    func testVisitorFormCustom() throws {
        // Visitor replaces form with custom output
        let result = try convert("<div><form action=\"/submit\" method=\"POST\"><label>Name: <input type=\"text\" name=\"name\"></label><button type=\"submit\">Submit</button></form></div>")
        XCTAssertTrue(result.content.contains("[FORM PLACEHOLDER]"), "expected to contain: \("[FORM PLACEHOLDER]")")
        XCTAssertFalse(result.content.contains("submit"), "expected NOT to contain: \("submit")")
        XCTAssertFalse(result.content.contains("input"), "expected NOT to contain: \("input")")
    }

    func testVisitorFormSkip() throws {
        // Visitor skips form elements entirely
        let result = try convert("<p>Before form</p><form><input type=\"email\" name=\"email\"></form><p>After form</p>")
        XCTAssertTrue(result.content.contains("Before form"), "expected to contain: \("Before form")")
        XCTAssertTrue(result.content.contains("After form"), "expected to contain: \("After form")")
        XCTAssertFalse(result.content.contains("email"), "expected NOT to contain: \("email")")
    }

    func testVisitorHorizontalRuleCustom() throws {
        // Visitor replaces horizontal rule with custom output
        let result = try convert("<h1>Section A</h1><p>Content A</p><hr><h1>Section B</h1><p>Content B</p>")
        XCTAssertTrue(result.content.contains("[DIVIDER]"), "expected to contain: \("[DIVIDER]")")
        XCTAssertTrue(result.content.contains("Section A"), "expected to contain: \("Section A")")
        XCTAssertTrue(result.content.contains("Section B"), "expected to contain: \("Section B")")
        XCTAssertFalse(result.content.contains("---"), "expected NOT to contain: \("---")")
    }

    func testVisitorHorizontalRuleSkip() throws {
        // Visitor removes all horizontal rules
        let result = try convert("<p>Part 1</p><hr><p>Part 2</p><hr><p>Part 3</p>")
        XCTAssertTrue(result.content.contains("Part 1"), "expected to contain: \("Part 1")")
        XCTAssertTrue(result.content.contains("Part 2"), "expected to contain: \("Part 2")")
        XCTAssertTrue(result.content.contains("Part 3"), "expected to contain: \("Part 3")")
        XCTAssertFalse(result.content.contains("---"), "expected NOT to contain: \("---")")
    }

    func testVisitorIframeCustom() throws {
        // Visitor replaces embedded iframe with custom text
        let result = try convert("<p>Embedded map:</p><iframe src=\"https://maps.example.com/embed\" width=\"400\" height=\"300\"></iframe><p>End of map</p>")
        XCTAssertTrue(result.content.contains("[EMBEDDED: https://maps.example.com/embed]"), "expected to contain: \("[EMBEDDED: https://maps.example.com/embed]")")
        XCTAssertTrue(result.content.contains("Embedded map:"), "expected to contain: \("Embedded map:")")
        XCTAssertTrue(result.content.contains("End of map"), "expected to contain: \("End of map")")
    }

    func testVisitorIframeSkip() throws {
        // Visitor removes embedded iframes
        let result = try convert("<h3>Reviews</h3><iframe src=\"https://widget.example.com/reviews\"></iframe><p>See reviews from our partners.</p>")
        XCTAssertTrue(result.content.contains("Reviews"), "expected to contain: \("Reviews")")
        XCTAssertTrue(result.content.contains("See reviews from our partners."), "expected to contain: \("See reviews from our partners.")")
        XCTAssertFalse(result.content.contains("widget.example.com"), "expected NOT to contain: \("widget.example.com")")
    }

    func testVisitorInputCustom() throws {
        // Visitor replaces input with labeled output
        let result = try convert("<form><label>Username: <input type=\"text\" name=\"username\" value=\"\"></label><label>Password: <input type=\"password\" name=\"password\"></label></form>")
        XCTAssertTrue(result.content.contains("[INPUT:text]"), "expected to contain: \("[INPUT:text]")")
        XCTAssertTrue(result.content.contains("[INPUT:password]"), "expected to contain: \("[INPUT:password]")")
    }

    func testVisitorInputSkip() throws {
        // Visitor skips all input elements
        let result = try convert("<p>Sign up:</p><input type=\"text\" name=\"email\" placeholder=\"your@email.com\"><input type=\"checkbox\" name=\"agree\"><p>Continue</p>")
        XCTAssertTrue(result.content.contains("Sign up:"), "expected to contain: \("Sign up:")")
        XCTAssertTrue(result.content.contains("Continue"), "expected to contain: \("Continue")")
        XCTAssertFalse(result.content.contains("email"), "expected NOT to contain: \("email")")
    }

    func testVisitorLineBreakCustom() throws {
        // Visitor replaces line break with custom output
        let result = try convert("<p>First line<br>Second line<br>Third line</p>")
        XCTAssertTrue(result.content.contains("First line | Second line | Third line"), "expected to contain: \("First line | Second line | Third line")")
        XCTAssertFalse(result.content.contains("\n\n"), "expected NOT to contain: \("\n\n")")
    }

    func testVisitorLineBreakSkip() throws {
        // Visitor removes all line breaks
        let result = try convert("<p>Address Line 1<br>Address Line 2<br>Address Line 3</p>")
        XCTAssertTrue(result.content.contains("Address Line 1Address Line 2Address Line 3"), "expected to contain: \("Address Line 1Address Line 2Address Line 3")")
    }

    func testVisitorMarkCustom() throws {
        // Visitor replaces highlight/mark with custom template
        let result = try convert("<p>This is a <mark>highlighted passage</mark> in the text.</p>")
        XCTAssertTrue(result.content.contains("==highlighted passage=="), "expected to contain: \("==highlighted passage==")")
        XCTAssertTrue(result.content.contains("This is a"), "expected to contain: \("This is a")")
    }

    func testVisitorMarkSkip() throws {
        // Visitor skips mark elements entirely
        let result = try convert("<p>Key insight: <mark>always validate input</mark> for security.</p>")
        XCTAssertFalse(result.content.contains("always validate input"), "expected NOT to contain: \("always validate input")")
        XCTAssertTrue(result.content.contains("Key insight:"), "expected to contain: \("Key insight:")")
        XCTAssertTrue(result.content.contains("for security."), "expected to contain: \("for security.")")
    }

    func testVisitorPreserveHtml() throws {
        // Visitor preserve_html action includes raw HTML in output
        let result = try convert("<div><custom-tag>Custom content</custom-tag></div>")
        XCTAssertTrue(result.content.contains("<custom-tag>"), "expected to contain: \("<custom-tag>")")
    }

    func testVisitorSkipAllHeadings() throws {
        // Visitor skips all headings from document
        let result = try convert("<h1>Title</h1><p>Body text remains.</p>")
        XCTAssertFalse(result.content.contains("Title"), "expected NOT to contain: \("Title")")
        XCTAssertTrue(result.content.contains("Body text remains."), "expected to contain: \("Body text remains.")")
    }

    func testVisitorSkipCodeBlocks() throws {
        // Visitor skips code blocks from output
        let result = try convert("<p>Intro text</p><pre><code>let x = 42;</code></pre><p>Outro text</p>")
        XCTAssertTrue(result.content.contains("Intro text"), "expected to contain: \("Intro text")")
        XCTAssertTrue(result.content.contains("Outro text"), "expected to contain: \("Outro text")")
        XCTAssertFalse(result.content.contains("let x = 42"), "expected NOT to contain: \("let x = 42")")
    }

    func testVisitorSkipHeading() throws {
        // Visitor skip action omits all headings from output
        let result = try convert("<h1>Title</h1><p>Body text remains.</p>")
        XCTAssertFalse(result.content.contains("Title"), "expected NOT to contain: \("Title")")
        XCTAssertTrue(result.content.contains("Body text remains."), "expected to contain: \("Body text remains.")")
    }

    func testVisitorSkipImages() throws {
        // Visitor skips all images from output
        let result = try convert("<p>Before image</p><img src=\"photo.jpg\" alt=\"A photo\"><p>After image</p>")
        XCTAssertTrue(result.content.contains("Before image"), "expected to contain: \("Before image")")
        XCTAssertTrue(result.content.contains("After image"), "expected to contain: \("After image")")
        XCTAssertFalse(result.content.contains("photo.jpg"), "expected NOT to contain: \("photo.jpg")")
        XCTAssertFalse(result.content.contains("A photo"), "expected NOT to contain: \("A photo")")
    }

    func testVisitorSkipLinks() throws {
        // Visitor skips all links entirely
        let result = try convert("<p>Before <a href=\"https://example.com\">link text</a> after</p>")
        XCTAssertFalse(result.content.contains("link text"), "expected NOT to contain: \("link text")")
        XCTAssertFalse(result.content.contains("example.com"), "expected NOT to contain: \("example.com")")
    }

    func testVisitorSkipStrong() throws {
        // Visitor skips bold/strong elements
        let result = try convert("<p>Normal <strong>bold text</strong> normal</p>")
        XCTAssertFalse(result.content.contains("bold text"), "expected NOT to contain: \("bold text")")
        XCTAssertTrue(result.content.contains("Normal"), "expected to contain: \("Normal")")
    }

    func testVisitorSubscriptCustom() throws {
        // Visitor replaces subscript with custom template
        let result = try convert("<p>H<sub>2</sub>O is water.</p>")
        XCTAssertTrue(result.content.contains("H~2~O"), "expected to contain: \("H~2~O")")
        XCTAssertTrue(result.content.contains("is water"), "expected to contain: \("is water")")
    }

    func testVisitorSubscriptSkip() throws {
        // Visitor skips subscript elements entirely
        let result = try convert("<p>The formula C<sub>12</sub>H<sub>22</sub>O<sub>11</sub> is sugar.</p>")
        XCTAssertTrue(result.content.contains("The formula CHO is sugar."), "expected to contain: \("The formula CHO is sugar.")")
    }

    func testVisitorSuperscriptCustom() throws {
        // Visitor replaces superscript with custom template
        let result = try convert("<p>Einstein's E=mc<sup>2</sup> revolutionized physics.</p>")
        XCTAssertTrue(result.content.contains("E=mc^2^"), "expected to contain: \("E=mc^2^")")
        XCTAssertTrue(result.content.contains("revolutionized physics"), "expected to contain: \("revolutionized physics")")
    }

    func testVisitorSuperscriptSkip() throws {
        // Visitor skips superscript from output
        let result = try convert("<p>The equation x<sup>3</sup> + y<sup>3</sup> = z<sup>3</sup> has no solutions.</p>")
        XCTAssertTrue(result.content.contains("The equation x + y = z has no solutions."), "expected to contain: \("The equation x + y = z has no solutions.")")
    }

    func testVisitorUnderlineCustom() throws {
        // Visitor replaces underline with custom markup
        let result = try convert("<p>This is <u>very important</u> text.</p>")
        XCTAssertTrue(result.content.contains("_very important_"), "expected to contain: \("_very important_")")
        XCTAssertFalse(result.content.contains("**"), "expected NOT to contain: \("**")")
    }

    func testVisitorUnderlineSkip() throws {
        // Visitor skips underline elements from output
        let result = try convert("<p>Normal text with <u>underlined part</u> and more text.</p>")
        XCTAssertTrue(result.content.contains("Normal text with"), "expected to contain: \("Normal text with")")
        XCTAssertTrue(result.content.contains("and more text."), "expected to contain: \("and more text.")")
        XCTAssertFalse(result.content.contains("underlined part"), "expected NOT to contain: \("underlined part")")
    }

    func testVisitorVideoCustom() throws {
        // Visitor replaces video with custom link
        let result = try convert("<p>Watch our tutorial:</p><video src=\"tutorial.mp4\" width=\"320\" height=\"240\" controls></video><p>Great content!</p>")
        XCTAssertTrue(result.content.contains("[VIDEO: tutorial.mp4]"), "expected to contain: \("[VIDEO: tutorial.mp4]")")
        XCTAssertTrue(result.content.contains("Watch our tutorial:"), "expected to contain: \("Watch our tutorial:")")
        XCTAssertTrue(result.content.contains("Great content!"), "expected to contain: \("Great content!")")
    }

    func testVisitorVideoSkip() throws {
        // Visitor removes video elements entirely
        let result = try convert("<h2>Demo</h2><video src=\"demo.webm\"></video><p>See the demo above.</p>")
        XCTAssertTrue(result.content.contains("Demo"), "expected to contain: \("Demo")")
        XCTAssertTrue(result.content.contains("See the demo above."), "expected to contain: \("See the demo above.")")
        XCTAssertFalse(result.content.contains("demo.webm"), "expected NOT to contain: \("demo.webm")")
    }

}
