# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:241458cfb7c6928edc10860da6d5a3b428554f8f4dfe02b9975981c23a9f4dc2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module HtmlToMarkdown
  VERSION = "3.3.3"
end
