# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8216461f8bb598dc0d58c812381f735a26bd775672a8f3b8b527434524a9c554
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module HtmlToMarkdown
  VERSION = "3.4.0-rc.3"
end
