# E2e tests for category: smoke
# Generated by html-to-markdown-e2e-generator — do not edit manually.

defmodule HtmlToMarkdown.SmokeTest do
  use ExUnit.Case

  test "smoke_empty_string: Empty string produces empty output" do
    html = ""
    {:ok, result} = HtmlToMarkdown.convert(html)
    content = result[:content] || ""

    assert String.trim(content) == ""
  end

  test "smoke_simple_heading: H1 heading converts to ATX markdown" do
    html = "<h1>Title</h1>"
    {:ok, result} = HtmlToMarkdown.convert(html)
    content = result[:content] || ""

    assert String.contains?(content, "\# Title")
  end

  test "smoke_simple_paragraph: Simple paragraph converts correctly" do
    html = "<p>Hello World</p>"
    {:ok, result} = HtmlToMarkdown.convert(html)
    content = result[:content] || ""

    assert String.trim(content) == "Hello World"
    assert String.trim(content) != ""
  end
end
