# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: smoke
defmodule E2e.SmokeTest do
  use ExUnit.Case, async: true

  describe "smoke_empty_string" do
    test "Empty string produces empty output" do
      {:ok, result} = HtmlToMarkdown.convert("")
      assert String.trim(result.content) == ""
    end
  end

  describe "smoke_simple_heading" do
    test "H1 heading converts to ATX markdown" do
      {:ok, result} = HtmlToMarkdown.convert("<h1>Title</h1>")
      assert String.contains?(to_string(result.content), "\# Title")
    end
  end

  describe "smoke_simple_paragraph" do
    test "Simple paragraph converts correctly" do
      {:ok, result} = HtmlToMarkdown.convert("<p>Hello World</p>")
      assert String.trim(result.content) == "Hello World"
      assert result.content != ""
    end
  end
end
