//! E2e tests for category: conversion
//! Generated by html-to-markdown-e2e-generator — do not edit manually.

use html_to_markdown_rs::convert;

#[test]
fn test_blockquote_simple() {
    // Simple blockquote
    let html = r#"<blockquote><p>Quote text</p></blockquote>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(
        content.contains("> Quote text"),
        "expected content to contain: > Quote text"
    );
}

#[test]
fn test_bold_and_italic() {
    // Nested bold and italic
    let html = r#"<p><strong><em>both</em></strong></p>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(
        content.contains("***both***"),
        "expected content to contain: ***both***"
    );
}

#[test]
fn test_bold_strong() {
    // Strong tag converts to bold
    let html = r#"<p><strong>bold</strong></p>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(content.contains("**bold**"), "expected content to contain: **bold**");
}

#[test]
fn test_code_block() {
    // Code block with language
    let html = r#"<pre><code class="language-python">print('hello')</code></pre>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(content.contains("```python"), "expected content to contain: ```python");
    assert!(
        content.contains("print('hello')"),
        "expected content to contain: print('hello')"
    );
    assert!(content.contains("```"), "expected content to contain: ```");
}

#[test]
fn test_heading_h1() {
    // H1 heading
    let html = r#"<h1>Heading 1</h1>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert_eq!(content.trim(), "# Heading 1", "content_equals mismatch");
}

#[test]
fn test_heading_h2() {
    // H2 heading
    let html = r#"<h2>Heading 2</h2>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert_eq!(content.trim(), "## Heading 2", "content_equals mismatch");
}

#[test]
fn test_heading_h3() {
    // H3 heading
    let html = r#"<h3>Heading 3</h3>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert_eq!(content.trim(), "### Heading 3", "content_equals mismatch");
}

#[test]
fn test_heading_h4() {
    // H4 heading
    let html = r#"<h4>Heading 4</h4>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert_eq!(content.trim(), "#### Heading 4", "content_equals mismatch");
}

#[test]
fn test_heading_h5() {
    // H5 heading
    let html = r#"<h5>Heading 5</h5>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert_eq!(content.trim(), "##### Heading 5", "content_equals mismatch");
}

#[test]
fn test_heading_h6() {
    // H6 heading
    let html = r#"<h6>Heading 6</h6>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert_eq!(content.trim(), "###### Heading 6", "content_equals mismatch");
}

#[test]
fn test_image_simple() {
    // Image with alt text
    let html = r#"<img src="photo.jpg" alt="A photo">"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(
        content.contains("![A photo](photo.jpg)"),
        "expected content to contain: ![A photo](photo.jpg)"
    );
}

#[test]
fn test_inline_code() {
    // Inline code
    let html = r#"<p>Use <code>console.log()</code> to debug</p>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(
        content.contains("`console.log()`"),
        "expected content to contain: `console.log()`"
    );
}

#[test]
fn test_italic_em() {
    // Em tag converts to italic
    let html = r#"<p><em>italic</em></p>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(content.contains("*italic*"), "expected content to contain: *italic*");
}

#[test]
fn test_link_simple() {
    // Simple link
    let html = r#"<a href="https://example.com">Example</a>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(
        content.contains("[Example](https://example.com)"),
        "expected content to contain: [Example](https://example.com)"
    );
}

#[test]
fn test_link_with_title() {
    // Link with title attribute
    let html = r#"<a href="https://example.com" title="Example Site">Example</a>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(
        content.contains("[Example](https://example.com"),
        "expected content to contain: [Example](https://example.com"
    );
    assert!(
        content.contains("Example Site"),
        "expected content to contain: Example Site"
    );
}

#[test]
fn test_ordered_list() {
    // Ordered list
    let html = r#"<ol><li>First</li><li>Second</li><li>Third</li></ol>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(content.contains("1. First"), "expected content to contain: 1. First");
    assert!(content.contains("2. Second"), "expected content to contain: 2. Second");
    assert!(content.contains("3. Third"), "expected content to contain: 3. Third");
}

#[test]
fn test_simple_table() {
    // Simple table with header
    let html = r#"<table><thead><tr><th>Name</th><th>Age</th></tr></thead><tbody><tr><td>Alice</td><td>30</td></tr></tbody></table>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(content.contains("Name"), "expected content to contain: Name");
    assert!(content.contains("Age"), "expected content to contain: Age");
    assert!(content.contains("Alice"), "expected content to contain: Alice");
    assert!(content.contains("30"), "expected content to contain: 30");
    assert!(content.contains("|"), "expected content to contain: |");
    assert!(content.contains("---"), "expected content to contain: ---");
}

#[test]
fn test_unordered_list() {
    // Unordered list
    let html = r#"<ul><li>Item 1</li><li>Item 2</li><li>Item 3</li></ul>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(content.contains("- Item 1"), "expected content to contain: - Item 1");
    assert!(content.contains("- Item 2"), "expected content to contain: - Item 2");
    assert!(content.contains("- Item 3"), "expected content to contain: - Item 3");
}
