//! E2e tests for category: real-world
//! Generated by html-to-markdown-e2e-generator — do not edit manually.

use html_to_markdown_rs::convert;

#[test]
fn test_real_world_blog_post() {
    // Blog post with headings, paragraphs, code blocks, and links converts to readable Markdown
    let html = r#"<article><h1>Getting Started with Rust</h1><p>Rust is a systems programming language focused on <strong>safety</strong>, <em>performance</em>, and concurrency. It was created by <a href="https://www.mozilla.org">Mozilla</a> and has grown significantly in popularity.</p><h2>Installation</h2><p>Install Rust using the official installer:</p><pre><code class="language-bash">curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh</code></pre><h2>Hello World</h2><p>Create your first Rust program:</p><pre><code class="language-rust">fn main() {
    println!("Hello, world!");
}</code></pre><p>Run it with <code>cargo run</code> from your project directory.</p><h2>Key Concepts</h2><ul><li>Ownership and borrowing</li><li>Lifetimes</li><li>Traits and generics</li><li>Pattern matching</li></ul><p>For more information, visit the <a href="https://doc.rust-lang.org/book/">Rust Book</a>.</p></article>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(!content.trim().is_empty(), "expected non-empty content");
    assert!(
        content.contains("# Getting Started with Rust"),
        "expected content to contain: # Getting Started with Rust"
    );
    assert!(
        content.contains("## Installation"),
        "expected content to contain: ## Installation"
    );
    assert!(
        content.contains("## Hello World"),
        "expected content to contain: ## Hello World"
    );
    assert!(
        content.contains("## Key Concepts"),
        "expected content to contain: ## Key Concepts"
    );
    assert!(content.contains("cargo run"), "expected content to contain: cargo run");
    assert!(
        content.contains("[Mozilla](https://www.mozilla.org)"),
        "expected content to contain: [Mozilla](https://www.mozilla.org)"
    );
    assert!(
        content.contains("- Ownership and borrowing"),
        "expected content to contain: - Ownership and borrowing"
    );
    assert!(
        content.len() >= 200,
        "expected content length >= 200, got {}",
        content.len()
    );
}

#[test]
fn test_real_world_documentation_page() {
    // Documentation page with nested lists, code examples, and blockquotes converts correctly
    let html = r##"<div class="docs"><h1>API Reference</h1><p>This guide covers the core API for the <code>html-to-markdown</code> library.</p><blockquote><p><strong>Note:</strong> All functions are thread-safe and can be called from multiple threads concurrently.</p></blockquote><h2>convert_html</h2><p>Converts an HTML string to Markdown format.</p><pre><code class="language-rust">pub fn convert_html(html: &amp;str) -&gt; Result&lt;String, ConversionError&gt;</code></pre><h3>Parameters</h3><ul><li><code>html</code> - The HTML input string<ul><li>Must be valid UTF-8</li><li>Maximum size: 50MB</li></ul></li></ul><h3>Returns</h3><ul><li><code>Ok(String)</code> - The converted Markdown</li><li><code>Err(ConversionError)</code> - If conversion fails</li></ul><h3>Example</h3><pre><code class="language-rust">let markdown = convert_html("&lt;h1&gt;Hello&lt;/h1&gt;").unwrap();
assert_eq!(markdown, "# Hello");</code></pre><h2>ConversionOptions</h2><p>Configure conversion behavior using the builder pattern:</p><pre><code class="language-rust">let options = ConversionOptions::builder()
    .heading_style(HeadingStyle::ATX)
    .code_block_style(CodeBlockStyle::Fenced)
    .build();</code></pre><blockquote><p>See the <a href="/docs/options">options reference</a> for a full list of configuration values.</p></blockquote></div>"##;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(!content.trim().is_empty(), "expected non-empty content");
    assert!(
        content.contains("# API Reference"),
        "expected content to contain: # API Reference"
    );
    assert!(
        content.contains("## convert_html"),
        "expected content to contain: ## convert_html"
    );
    assert!(
        content.contains("### Parameters"),
        "expected content to contain: ### Parameters"
    );
    assert!(
        content.contains("### Returns"),
        "expected content to contain: ### Returns"
    );
    assert!(
        content.contains("### Example"),
        "expected content to contain: ### Example"
    );
    assert!(
        content.contains("## ConversionOptions"),
        "expected content to contain: ## ConversionOptions"
    );
    assert!(content.contains("> "), "expected content to contain: > ");
    assert!(
        content.contains("thread-safe"),
        "expected content to contain: thread-safe"
    );
    assert!(
        content.contains("convert_html"),
        "expected content to contain: convert_html"
    );
    assert!(
        content.contains("ConversionOptions"),
        "expected content to contain: ConversionOptions"
    );
    assert!(
        content.len() >= 400,
        "expected content length >= 400, got {}",
        content.len()
    );
}

#[test]
fn test_real_world_product_page() {
    // Product page with table, images, and lists converts correctly
    let html = r#"<div class="product"><h1>Wireless Keyboard Pro</h1><img src="https://example.com/keyboard.jpg" alt="Wireless Keyboard Pro"><p>The ultimate wireless keyboard for professionals. Features a comfortable layout with <strong>backlit keys</strong> and <em>ultra-long battery life</em>.</p><h2>Specifications</h2><table><thead><tr><th>Feature</th><th>Details</th></tr></thead><tbody><tr><td>Battery Life</td><td>Up to 12 months</td></tr><tr><td>Connectivity</td><td>Bluetooth 5.0</td></tr><tr><td>Key Travel</td><td>2mm</td></tr><tr><td>Weight</td><td>750g</td></tr></tbody></table><h2>What's in the Box</h2><ul><li>Wireless Keyboard Pro</li><li>USB-C charging cable</li><li>USB receiver dongle</li><li>Quick start guide</li></ul><h2>Compatibility</h2><p>Compatible with <strong>Windows</strong>, <strong>macOS</strong>, <strong>Linux</strong>, <strong>iOS</strong>, and <strong>Android</strong>.</p></div>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(!content.trim().is_empty(), "expected non-empty content");
    assert!(
        content.contains("# Wireless Keyboard Pro"),
        "expected content to contain: # Wireless Keyboard Pro"
    );
    assert!(
        content.contains("![Wireless Keyboard Pro](https://example.com/keyboard.jpg)"),
        "expected content to contain: ![Wireless Keyboard Pro](https://example.com/keyboard.jpg)"
    );
    assert!(
        content.contains("## Specifications"),
        "expected content to contain: ## Specifications"
    );
    assert!(
        content.contains("Battery Life"),
        "expected content to contain: Battery Life"
    );
    assert!(content.contains("12 months"), "expected content to contain: 12 months");
    assert!(
        content.contains("Bluetooth 5.0"),
        "expected content to contain: Bluetooth 5.0"
    );
    assert!(
        content.contains("## What's in the Box"),
        "expected content to contain: ## What's in the Box"
    );
    assert!(
        content.contains("USB-C charging cable"),
        "expected content to contain: USB-C charging cable"
    );
    assert!(content.contains("|"), "expected content to contain: |");
    assert!(content.contains("---"), "expected content to contain: ---");
    assert!(
        content.len() >= 300,
        "expected content length >= 300, got {}",
        content.len()
    );
}
