//! E2e tests for category: smoke
//! Generated by html-to-markdown-e2e-generator — do not edit manually.

use html_to_markdown_rs::convert;

#[test]
fn test_smoke_empty_string() {
    // Empty string produces empty output
    let html = r#""#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert_eq!(content.trim(), "", "content_equals mismatch");
}

#[test]
fn test_smoke_simple_heading() {
    // H1 heading converts to ATX markdown
    let html = r#"<h1>Title</h1>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert!(content.contains("# Title"), "expected content to contain: # Title");
}

#[test]
fn test_smoke_simple_paragraph() {
    // Simple paragraph converts correctly
    let html = r#"<p>Hello World</p>"#;
    let result = convert(html, None).expect("conversion should succeed");
    let content = result.content.unwrap_or_default();

    assert_eq!(content.trim(), "Hello World", "content_equals mismatch");
    assert!(!content.trim().is_empty(), "expected non-empty content");
}
