// This file is auto-generated by alef. DO NOT EDIT.
//! E2e tests for category: visitor

use html_to_markdown_rs::convert;

#[test]
fn test_visitor_continue_default() {
    // Visitor continue action preserves default conversion
    let html = r#"<p>Hello <strong>World</strong></p>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_strong(&self, ctx, text) -> VisitResult {
            VisitResult::Continue
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(format!("{:?}", content).contains(r#"**World**"#), "expected to contain: {}", r#"**World**"#);
}

#[test]
fn test_visitor_custom_blockquote() {
    // Visitor replaces blockquote with custom format
    let html = r#"<blockquote><p>A wise quote.</p></blockquote>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_blockquote(&self, ctx, content, depth) -> VisitResult {
            VisitResult::Custom(format!("QUOTE: "{content}""))
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(format!("{:?}", content).contains(r#"QUOTE:"#), "expected to contain: {}", r#"QUOTE:"#);
    assert!(format!("{:?}", content).contains(r#"A wise quote."#), "expected to contain: {}", r#"A wise quote."#);
}

#[test]
fn test_visitor_custom_emphasis() {
    // Visitor replaces emphasis with custom output
    let html = r#"<p>This is <em>important</em> text.</p>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_emphasis(&self, ctx, text) -> VisitResult {
            VisitResult::Custom(format!(">>>{text}<<<"))
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(format!("{:?}", content).contains(r#">>>important<<<"#), "expected to contain: {}", r#">>>important<<<"#);
    assert!(!format!("{:?}", content).contains(r#"*important*"#), "expected NOT to contain: {}", r#"*important*"#);
}

#[test]
fn test_visitor_custom_heading() {
    // Visitor replaces heading with custom format
    let html = r#"<h2>Section Title</h2><p>Content below heading.</p>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_heading(&self, ctx, level, text, id) -> VisitResult {
            VisitResult::Custom(format!("--- {text} ---"))
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(format!("{:?}", content).contains(r#"--- Section Title ---"#), "expected to contain: {}", r#"--- Section Title ---"#);
    assert!(!format!("{:?}", content).contains(r#"## Section Title"#), "expected NOT to contain: {}", r#"## Section Title"#);
    assert!(format!("{:?}", content).contains(r#"Content below heading."#), "expected to contain: {}", r#"Content below heading."#);
}

#[test]
fn test_visitor_custom_image() {
    // Visitor replaces image with custom output using template
    let html = r#"<img src="banner.png" alt="Banner">"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_image(&self, ctx, src, alt, title) -> VisitResult {
            VisitResult::Custom(format!("[Image: {alt}]"))
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(format!("{:?}", content).contains(r#"[Image: Banner]"#), "expected to contain: {}", r#"[Image: Banner]"#);
    assert!(!format!("{:?}", content).contains(r#"banner.png"#), "expected NOT to contain: {}", r#"banner.png"#);
}

#[test]
fn test_visitor_custom_link_format() {
    // Visitor reformats links using template interpolation
    let html = r#"<p>Visit <a href="https://example.com">Example</a> for more info.</p>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_link(&self, ctx, href, text, title) -> VisitResult {
            VisitResult::Custom(format!("{text} ({href})"))
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(format!("{:?}", content).contains(r#"Example (https://example.com)"#), "expected to contain: {}", r#"Example (https://example.com)"#);
    assert!(!format!("{:?}", content).contains(r#"[Example]"#), "expected NOT to contain: {}", r#"[Example]"#);
}

#[test]
fn test_visitor_custom_link_static() {
    // Visitor replaces link with static custom output
    let html = r#"<a href="https://example.com">Click here</a>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_link(&self, ctx, href, text, title) -> VisitResult {
            VisitResult::Custom([REDACTED LINK].to_string())
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(format!("{:?}", content).contains(r#"[REDACTED LINK]"#), "expected to contain: {}", r#"[REDACTED LINK]"#);
    assert!(!format!("{:?}", content).contains(r#"example.com"#), "expected NOT to contain: {}", r#"example.com"#);
}

#[test]
fn test_visitor_custom_output() {
    // Visitor custom action replaces element output
    let html = r#"<h1>Original Heading</h1>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_heading(&self, ctx, level, text, id) -> VisitResult {
            VisitResult::Custom(## REPLACED HEADING.to_string())
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(format!("{:?}", content).contains(r#"## REPLACED HEADING"#), "expected to contain: {}", r#"## REPLACED HEADING"#);
    assert!(!format!("{:?}", content).contains(r#"# Original Heading"#), "expected NOT to contain: {}", r#"# Original Heading"#);
}

#[test]
fn test_visitor_preserve_html() {
    // Visitor preserve_html action includes raw HTML in output
    let html = r#"<div><custom-tag>Custom content</custom-tag></div>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_custom_element(&self, ctx, tag_name, html) -> VisitResult {
            VisitResult::PreserveHtml
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(format!("{:?}", content).contains(r#"<custom-tag>"#), "expected to contain: {}", r#"<custom-tag>"#);
}

#[test]
fn test_visitor_skip_all_headings() {
    // Visitor skips all headings from document
    let html = r#"<h1>Title</h1><p>Body text remains.</p>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_heading(&self, ctx, level, text, id) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(!format!("{:?}", content).contains(r#"Title"#), "expected NOT to contain: {}", r#"Title"#);
    assert!(format!("{:?}", content).contains(r#"Body text remains."#), "expected to contain: {}", r#"Body text remains."#);
}

#[test]
fn test_visitor_skip_code_blocks() {
    // Visitor skips code blocks from output
    let html = r#"<p>Intro text</p><pre><code>let x = 42;</code></pre><p>Outro text</p>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_code_block(&self, ctx, lang, code) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(format!("{:?}", content).contains(r#"Intro text"#), "expected to contain: {}", r#"Intro text"#);
    assert!(format!("{:?}", content).contains(r#"Outro text"#), "expected to contain: {}", r#"Outro text"#);
    assert!(!format!("{:?}", content).contains(r#"let x = 42"#), "expected NOT to contain: {}", r#"let x = 42"#);
}

#[test]
fn test_visitor_skip_heading() {
    // Visitor skip action omits all headings from output
    let html = r#"<h1>Title</h1><p>Body text remains.</p>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_heading(&self, ctx, level, text, id) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(!format!("{:?}", content).contains(r#"Title"#), "expected NOT to contain: {}", r#"Title"#);
    assert!(format!("{:?}", content).contains(r#"Body text remains."#), "expected to contain: {}", r#"Body text remains."#);
}

#[test]
fn test_visitor_skip_images() {
    // Visitor skips all images from output
    let html = r#"<p>Before image</p><img src="photo.jpg" alt="A photo"><p>After image</p>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_image(&self, ctx, src, alt, title) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(format!("{:?}", content).contains(r#"Before image"#), "expected to contain: {}", r#"Before image"#);
    assert!(format!("{:?}", content).contains(r#"After image"#), "expected to contain: {}", r#"After image"#);
    assert!(!format!("{:?}", content).contains(r#"photo.jpg"#), "expected NOT to contain: {}", r#"photo.jpg"#);
    assert!(!format!("{:?}", content).contains(r#"A photo"#), "expected NOT to contain: {}", r#"A photo"#);
}

#[test]
fn test_visitor_skip_links() {
    // Visitor skips all links entirely
    let html = r#"<p>Before <a href="https://example.com">link text</a> after</p>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_link(&self, ctx, href, text, title) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(!format!("{:?}", content).contains(r#"link text"#), "expected NOT to contain: {}", r#"link text"#);
    assert!(!format!("{:?}", content).contains(r#"example.com"#), "expected NOT to contain: {}", r#"example.com"#);
}

#[test]
fn test_visitor_skip_strong() {
    // Visitor skips bold/strong elements
    let html = r#"<p>Normal <strong>bold text</strong> normal</p>"#;
    let options = Default::default();
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_strong(&self, ctx, text) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::rc::Rc::new(std::cell::RefCell::new(_TestVisitor));
    let result = convert(&html, &options, Some(visitor)).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(!format!("{:?}", content).contains(r#"bold text"#), "expected NOT to contain: {}", r#"bold text"#);
    assert!(format!("{:?}", content).contains(r#"Normal"#), "expected to contain: {}", r#"Normal"#);
}
