<?php

// E2e tests for category: metadata
// Generated by html-to-markdown-e2e-generator — do not edit manually.

declare(strict_types=1);

namespace HtmlToMarkdown\Tests;

use PHPUnit\Framework\TestCase;

class MetadataTest extends TestCase
{
    /**
     * Extract author from <meta name='author'> tag
     */
    public function testMetadataAuthorMeta(): void
    {
        $html = "<html><head><title>Page</title><meta name=\"author\" content=\"Jane Doe\"></head><body><p>Content</p></body></html>";
        $options = json_decode("{\"extract_metadata\":true}", true);
        $result = html_to_markdown_convert($html, $options);
        $content = $result['content'] ?? '';

        $this->assertNotEmpty(trim($content), 'expected non-empty content');
    }

    /**
     * Extract canonical URL from <link rel='canonical'> tag
     */
    public function testMetadataCanonicalUrl(): void
    {
        $html = "<html><head><title>Page</title><link rel=\"canonical\" href=\"https://example.com/canonical-page\"></head><body><p>Content</p></body></html>";
        $options = json_decode("{\"extract_metadata\":true}", true);
        $result = html_to_markdown_convert($html, $options);
        $content = $result['content'] ?? '';

        $this->assertNotEmpty(trim($content), 'expected non-empty content');
    }

    /**
     * Extract description from <meta name='description'> tag
     */
    public function testMetadataDescriptionMeta(): void
    {
        $html = "<html><head><title>Page</title><meta name=\"description\" content=\"This is the page description.\"></head><body><p>Content</p></body></html>";
        $options = json_decode("{\"extract_metadata\":true}", true);
        $result = html_to_markdown_convert($html, $options);
        $content = $result['content'] ?? '';

        $this->assertNotEmpty(trim($content), 'expected non-empty content');
    }

    /**
     * Extract all images from a document into metadata
     */
    public function testMetadataExtractAllImages(): void
    {
        $html = "<html><head><title>Gallery</title></head><body><img src=\"https://example.com/photo1.jpg\" alt=\"Photo 1\"><img src=\"https://example.com/photo2.png\" alt=\"Photo 2\"><img src=\"/local/image.webp\" alt=\"Local image\"></body></html>";
        $options = json_decode("{\"extract_metadata\":true}", true);
        $result = html_to_markdown_convert($html, $options);
        $content = $result['content'] ?? '';

        $this->assertNotEmpty(trim($content), 'expected non-empty content');
    }

    /**
     * Extract all links from a document into metadata
     */
    public function testMetadataExtractAllLinks(): void
    {
        $html = "<html><head><title>Links Page</title></head><body><p>Visit <a href=\"https://example.com\">Example</a> or <a href=\"https://docs.example.com\">Docs</a>.</p><p>Also see <a href=\"/relative/path\">relative link</a> and <a href=\"mailto:hello@example.com\">email us</a>.</p></body></html>";
        $options = json_decode("{\"extract_metadata\":true}", true);
        $result = html_to_markdown_convert($html, $options);
        $content = $result['content'] ?? '';

        $this->assertNotEmpty(trim($content), 'expected non-empty content');
    }

    /**
     * Extract heading hierarchy from document into metadata
     */
    public function testMetadataHeadersHierarchy(): void
    {
        $html = "<html><head><title>Docs</title></head><body><h1>Introduction</h1><h2>Getting Started</h2><h3>Installation</h3><h3>Configuration</h3><h2>Advanced Usage</h2><h3>Custom Options</h3></body></html>";
        $options = json_decode("{\"extract_metadata\":true}", true);
        $result = html_to_markdown_convert($html, $options);
        $content = $result['content'] ?? '';

        $this->assertNotEmpty(trim($content), 'expected non-empty content');
    }

    /**
     * Extract keywords from <meta name='keywords'> tag
     */
    public function testMetadataKeywordsMeta(): void
    {
        $html = "<html><head><title>Page</title><meta name=\"keywords\" content=\"rust, markdown, html, converter\"></head><body><p>Content</p></body></html>";
        $options = json_decode("{\"extract_metadata\":true}", true);
        $result = html_to_markdown_convert($html, $options);
        $content = $result['content'] ?? '';

        $this->assertNotEmpty(trim($content), 'expected non-empty content');
    }

    /**
     * Extract title from <title> tag
     */
    public function testMetadataTitleTag(): void
    {
        $html = "<html><head><title>My Page</title></head><body><p>Content</p></body></html>";
        $options = json_decode("{\"extract_metadata\":true}", true);
        $result = html_to_markdown_convert($html, $options);
        $content = $result['content'] ?? '';

        $this->assertNotEmpty(trim($content), 'expected non-empty content');
    }

    /**
     * Extract og:title, og:description, and og:image from Open Graph meta tags
     */
    public function testOgBasicTags(): void
    {
        $html = "<html><head><title>Fallback Title</title><meta property=\"og:title\" content=\"OG Title\"><meta property=\"og:description\" content=\"OG description text.\"><meta property=\"og:image\" content=\"https://example.com/image.jpg\"></head><body><p>Content</p></body></html>";
        $options = json_decode("{\"extract_metadata\":true}", true);
        $result = html_to_markdown_convert($html, $options);
        $content = $result['content'] ?? '';

        $this->assertNotEmpty(trim($content), 'expected non-empty content');
    }

    /**
     * Extract multiple Open Graph tags including type, url, and site_name
     */
    public function testOgMultipleTags(): void
    {
        $html = "<html><head><meta property=\"og:title\" content=\"Article Title\"><meta property=\"og:type\" content=\"article\"><meta property=\"og:url\" content=\"https://example.com/article\"><meta property=\"og:site_name\" content=\"Example Site\"><meta property=\"og:description\" content=\"An interesting article.\"><meta property=\"og:image\" content=\"https://example.com/article.jpg\"></head><body><article><p>Article content here.</p></article></body></html>";
        $options = json_decode("{\"extract_metadata\":true}", true);
        $result = html_to_markdown_convert($html, $options);
        $content = $result['content'] ?? '';

        $this->assertNotEmpty(trim($content), 'expected non-empty content');
    }

    /**
     * JSON-LD script tag is stripped from output (security) but metadata may be extracted
     */
    public function testStructuredDataJsonLd(): void
    {
        $html = "<html><head><title>Article</title><script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"Article\",\"headline\":\"My Article\",\"author\":{\"@type\":\"Person\",\"name\":\"Jane Doe\"},\"datePublished\":\"2024-01-15\"}</script></head><body><h1>My Article</h1><p>Article body text.</p></body></html>";
        $options = json_decode("{\"extract_metadata\":true}", true);
        $result = html_to_markdown_convert($html, $options);
        $content = $result['content'] ?? '';

        $this->assertNotEmpty(trim($content), 'expected non-empty content');
        $this->assertStringContainsString("My Article", $content);
        $this->assertStringNotContainsString("application/ld+json", $content);
        $this->assertStringNotContainsString("@context", $content);
        $this->assertStringNotContainsString("schema.org", $content);
    }

    /**
     * Multiple JSON-LD blocks are all stripped from output
     */
    public function testStructuredDataMultipleJsonLd(): void
    {
        $html = "<html><head><title>Shop Page</title><script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"Product\",\"name\":\"Widget\",\"price\":\"9.99\"}</script><script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"BreadcrumbList\",\"itemListElement\":[{\"@type\":\"ListItem\",\"position\":1,\"name\":\"Home\"}]}</script></head><body><h1>Widget</h1><p>A great widget for all purposes.</p></body></html>";
        $options = json_decode("{\"extract_metadata\":true}", true);
        $result = html_to_markdown_convert($html, $options);
        $content = $result['content'] ?? '';

        $this->assertNotEmpty(trim($content), 'expected non-empty content');
        $this->assertStringContainsString("Widget", $content);
        $this->assertStringNotContainsString("@context", $content);
        $this->assertStringNotContainsString("BreadcrumbList", $content);
        $this->assertStringNotContainsString("ListItem", $content);
    }

    /**
     * Extract Twitter card meta tags
     */
    public function testTwitterCardTags(): void
    {
        $html = "<html><head><meta name=\"twitter:card\" content=\"summary_large_image\"><meta name=\"twitter:site\" content=\"@examplesite\"><meta name=\"twitter:title\" content=\"Twitter Card Title\"><meta name=\"twitter:description\" content=\"Twitter card description.\"><meta name=\"twitter:image\" content=\"https://example.com/twitter-image.jpg\"></head><body><p>Content</p></body></html>";
        $options = json_decode("{\"extract_metadata\":true}", true);
        $result = html_to_markdown_convert($html, $options);
        $content = $result['content'] ?? '';

        $this->assertNotEmpty(trim($content), 'expected non-empty content');
    }

}
