#![allow(missing_docs)]

//! Build script for generating C bindings and pkg-config files.
//!
//! Uses cbindgen to generate C header files from Rust FFI definitions,
//! generates pkg-config .pc files for system integration, and injects
//! version constants into the generated header.

use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let version = env::var("CARGO_PKG_VERSION").unwrap();
    let output_file = PathBuf::from(&crate_dir).join("html_to_markdown.h");

    // ── cbindgen: generate C header ──────────────────────────────────
    cbindgen::generate(&crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file(&output_file);

    // ── Phase 2: inject version defines into the generated header ────
    let header_content = std::fs::read_to_string(&output_file).unwrap();
    let parts: Vec<&str> = version.split('.').collect();
    let major = parts.first().unwrap_or(&"0");
    let minor = parts.get(1).unwrap_or(&"0");
    let patch_raw = parts.get(2).unwrap_or(&"0");
    // Strip any pre-release suffix (e.g., "2-rc1" -> "2")
    let patch = patch_raw.split('-').next().unwrap_or("0");

    let version_block = format!(
        r#"
#define HTML_TO_MARKDOWN_VERSION_MAJOR {major}
#define HTML_TO_MARKDOWN_VERSION_MINOR {minor}
#define HTML_TO_MARKDOWN_VERSION_PATCH {patch}
#define HTML_TO_MARKDOWN_VERSION "{version}""#
    );

    let injected = header_content.replacen(
        "/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */",
        &format!("/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */\n{version_block}"),
        1,
    );
    assert!(
        injected.contains("HTML_TO_MARKDOWN_VERSION_MAJOR"),
        "Version injection failed: cbindgen autogen_warning marker not found in generated header"
    );
    std::fs::write(&output_file, injected).unwrap();

    // ── pkg-config: generate .pc files ───────────────────────────────
    generate_pkg_config(&crate_dir, &out_dir, &version);

    // ── rerun-if-changed directives ──────────────────────────────────
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/error.rs");
    println!("cargo:rerun-if-changed=src/conversion.rs");
    println!("cargo:rerun-if-changed=src/version.rs");
    println!("cargo:rerun-if-changed=src/strings.rs");
    println!("cargo:rerun-if-changed=cbindgen.toml");
    println!("cargo:rerun-if-changed=html-to-markdown-ffi.pc.in");
}

/// Generate pkg-config .pc files for both development and installation.
fn generate_pkg_config(crate_dir: &str, out_dir: &str, version: &str) {
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

    // Platform-specific private libs
    let libs_private = match target_os.as_str() {
        "macos" => "-framework Security -framework CoreFoundation",
        "windows" => "-lws2_32 -lbcrypt -luserenv",
        _ => "-ldl -lm -lpthread",
    };

    // Determine the target build directory for dev .pc file.
    // OUT_DIR is something like target/debug/build/<crate>/out
    // We need to walk up to target/<profile>/
    let out_path = PathBuf::from(out_dir);
    let target_dir = out_path.ancestors().nth(3).unwrap_or(out_path.as_path()).to_path_buf();

    // ── Development .pc (points to build artifacts) ──────────────────
    let target_dir_display = target_dir.display();
    let dev_pc = format!(
        r"prefix={crate_dir}
exec_prefix=${{prefix}}
libdir={target_dir_display}
includedir=${{prefix}}

Name: html-to-markdown-ffi
Description: C FFI bindings for html-to-markdown conversion library
Version: {version}
URL: https://github.com/kreuzberg-dev/html-to-markdown
Libs: -L${{libdir}} -lhtml_to_markdown_ffi
Libs.private: {libs_private}
Cflags: -I${{includedir}}
"
    );

    let dev_pc_path = PathBuf::from(out_dir).join("html-to-markdown-ffi.pc");
    std::fs::write(&dev_pc_path, dev_pc).unwrap();

    // ── Install .pc (from .pc.in template with /usr/local prefix) ────
    let template_path = PathBuf::from(crate_dir).join("html-to-markdown-ffi.pc.in");
    if let Ok(template) = std::fs::read_to_string(&template_path) {
        let install_pc = template
            .replace("@PREFIX@", "/usr/local")
            .replace("@VERSION@", version)
            .replace("@LIBS_PRIVATE@", libs_private);

        let install_pc_path = PathBuf::from(out_dir).join("html-to-markdown-ffi-install.pc");
        std::fs::write(&install_pc_path, install_pc).unwrap();
    }
}
