// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6fcad3a8975fdb5949aa58491e9dd454d06e78210ed7349136e77f2a92bcb50e
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/html_to_markdown.h");
}
