/* Auto-generated C bindings for html-to-markdown */

#ifndef HTML_TO_MARKDOWN_H
#define HTML_TO_MARKDOWN_H

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Start Rust-side profiling and write a flamegraph to the specified path.
 *
 * Returns 1 on success, 0 on failure. Use `html_to_markdown_last_error` to inspect failures.
 *
 * # Safety
 *
 * - `output` must be a valid, null-terminated UTF-8 C string for the duration of the call.
 */
bool html_to_markdown_profile_start(const char *output, int32_t frequency);

/**
 * Stop Rust-side profiling and flush the flamegraph.
 *
 * Returns 1 on success, 0 on failure. Use `html_to_markdown_last_error` to inspect failures.
 *
 * # Safety
 *
 * - This must only be called after a successful `html_to_markdown_profile_start`.
 */
bool html_to_markdown_profile_stop(void);

/**
 * Convert HTML to Markdown using default options.
 *
 * # Safety
 *
 * - `html` must be a valid null-terminated C string
 * - The returned string must be freed with `html_to_markdown_free_string`
 * - Returns NULL on error
 *
 * # Example (C)
 *
 * ```c
 * const char* html = "<h1>Hello</h1>";
 * char* markdown = html_to_markdown_convert(html);
 * if (markdown != NULL) {
 *     printf("%s\n", markdown);
 *     html_to_markdown_free_string(markdown);
 * }
 * ```
 */
char *html_to_markdown_convert(const char *html);

/**
 * Get the last error message from a failed conversion.
 *
 * # Safety
 *
 * - Returns a pointer to a thread-local buffer; copy it immediately if needed
 * - Pointer is invalidated by the next call to any `html_to_markdown_*` function
 * - May return NULL if no error has occurred in this thread
 */
const char *html_to_markdown_last_error(void);

/**
 * Free a string returned by html_to_markdown_convert.
 *
 * # Safety
 *
 * - `s` must be a string previously returned by `html_to_markdown_convert`
 * - `s` must not be NULL
 * - `s` must not be used after this call
 *
 * # Example (C)
 *
 * ```c
 * char* markdown = html_to_markdown_convert("<p>text</p>");
 * html_to_markdown_free_string(markdown);
 * // markdown is now invalid
 * ```
 */
void html_to_markdown_free_string(char *s);

/**
 * Get the library version string.
 *
 * # Safety
 *
 * - Returns a static string that does not need to be freed
 */
const char *html_to_markdown_version(void);

/**
 * Convert HTML to Markdown with metadata extraction.
 *
 * # Safety
 *
 * - `html` must be a valid null-terminated C string
 * - `metadata_json_out` must be a valid pointer to a char pointer
 * - The returned markdown string must be freed with `html_to_markdown_free_string`
 * - The metadata JSON string (written to metadata_json_out) must be freed with `html_to_markdown_free_string`
 * - Returns NULL on error (check error with `html_to_markdown_last_error`)
 *
 * # Example (C)
 *
 * ```c
 * const char* html = "<html><head><title>Test</title></head><body><h1>Hello</h1></body></html>";
 * char* metadata_json = NULL;
 * char* markdown = html_to_markdown_convert_with_metadata(html, &metadata_json);
 * if (markdown != NULL && metadata_json != NULL) {
 *     printf("Markdown: %s\n", markdown);
 *     printf("Metadata: %s\n", metadata_json);
 *     html_to_markdown_free_string(markdown);
 *     html_to_markdown_free_string(metadata_json);
 * }
 * ```
 */
char *html_to_markdown_convert_with_metadata(const char *html,
                                             char **metadata_json_out);

#endif  /* HTML_TO_MARKDOWN_H */
