//! C test generator for html-to-markdown e2e tests.
//!
//! Generates `e2e/c/test_{category}.c`, a main test runner, and a Makefile.

use crate::fixtures::Fixture;
use anyhow::Result;
use camino::Utf8Path;
use itertools::Itertools;
use std::collections::HashMap;
use std::fmt::Write as FmtWrite;

/// Generate C e2e tests from fixtures into `output_dir/c/`.
pub fn generate(fixtures: &[Fixture], output_dir: &Utf8Path) -> Result<usize> {
    let c_dir = output_dir.join("c");
    std::fs::create_dir_all(&c_dir)?;

    // Group fixtures by category.
    let by_category: HashMap<&str, Vec<&Fixture>> = fixtures
        .iter()
        .filter(|f| !f.is_skipped_for("c"))
        .into_group_map_by(|f| f.resolved_category());

    let mut total = 0;
    let mut all_test_functions = Vec::new();

    for (category, category_fixtures) in &by_category {
        let file_name = format!("test_{}.c", sanitize_ident(category));
        let path = c_dir.join(&file_name);
        let (content, test_functions) = render_test_file(category, category_fixtures);
        std::fs::write(&path, content)?;
        total += category_fixtures.len();
        all_test_functions.extend(test_functions);
    }

    // Generate main.c with test runner.
    let main_c = render_main_c(&all_test_functions);
    std::fs::write(c_dir.join("main.c"), main_c)?;

    // Generate Makefile.
    let makefile = render_makefile(&by_category);
    std::fs::write(c_dir.join("Makefile"), makefile)?;

    // Generate header file.
    let header = render_header_h(&by_category);
    std::fs::write(c_dir.join("test_runner.h"), header)?;

    Ok(total)
}

fn render_header_h(by_category: &HashMap<&str, Vec<&Fixture>>) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "#ifndef TEST_RUNNER_H");
    let _ = writeln!(out, "#define TEST_RUNNER_H");
    let _ = writeln!(out);

    // Declare all test functions
    for fixtures in by_category.values() {
        for fixture in fixtures {
            let fn_name = sanitize_ident(&fixture.id);
            let _ = writeln!(out, "void test_{}(void);", fn_name);
        }
    }

    let _ = writeln!(out);
    let _ = writeln!(out, "#endif // TEST_RUNNER_H");
    out
}

fn render_main_c(test_functions: &[String]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "/*! Test runner main for html-to-markdown C e2e tests.");
    let _ = writeln!(
        out,
        " *  Generated by html-to-markdown-e2e-generator — do not edit manually."
    );
    let _ = writeln!(out, " */");
    let _ = writeln!(out);
    let _ = writeln!(out, "#include <stdio.h>");
    let _ = writeln!(out, "#include \"test_runner.h\"");
    let _ = writeln!(out);

    let _ = writeln!(out, "int main(void) {{");
    let _ = writeln!(out, "    int passed = 0;");
    let _ = writeln!(out, "    int failed = 0;");
    let _ = writeln!(out);

    for test_fn in test_functions {
        let _ = writeln!(out, "    printf(\"Running {{}}...\\n\", \"{}\");", test_fn);
        let _ = writeln!(out, "    {}();", test_fn);
        let _ = writeln!(out, "    passed++;");
        let _ = writeln!(out);
    }

    let _ = writeln!(out, "    printf(\"\\n==== RESULTS ====\\n\");");
    let _ = writeln!(out, "    printf(\"Passed: %d\\n\", passed);");
    let _ = writeln!(out, "    printf(\"Failed: %d\\n\", failed);");
    let _ = writeln!(out, "    return failed == 0 ? 0 : 1;");
    let _ = writeln!(out, "}}");

    out
}

fn render_makefile(by_category: &HashMap<&str, Vec<&Fixture>>) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# Makefile for html-to-markdown C e2e tests");
    let _ = writeln!(out, "# Generated by html-to-markdown-e2e-generator");
    let _ = writeln!(out);
    let _ = writeln!(out, "CC = gcc");
    let _ = writeln!(out, "CFLAGS = -Wall -Wextra -std=c11");
    let _ = writeln!(out, "LDFLAGS = -L. -lhtml_to_markdown");
    let _ = writeln!(out);

    // Get test file names
    let test_files: Vec<String> = by_category
        .keys()
        .map(|cat| format!("test_{}.o", sanitize_ident(cat)))
        .collect();
    let test_files_str = test_files.join(" ");

    let _ = writeln!(out, "SOURCES = main.c {}", test_files_str.replace(".o", ".c"));
    let _ = writeln!(out, "OBJECTS = main.o {}", test_files_str);
    let _ = writeln!(out, "TARGET = test_runner");
    let _ = writeln!(out);
    let _ = writeln!(out, ".PHONY: all clean test");
    let _ = writeln!(out);
    let _ = writeln!(out, "all: $(TARGET)");
    let _ = writeln!(out);
    let _ = writeln!(out, "$(TARGET): $(OBJECTS)");
    let _ = writeln!(out, "\t$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)");
    let _ = writeln!(out);
    let _ = writeln!(out, "%.o: %.c");
    let _ = writeln!(out, "\t$(CC) $(CFLAGS) -c -o $@ $<");
    let _ = writeln!(out);
    let _ = writeln!(out, "clean:");
    let _ = writeln!(out, "\trm -f $(OBJECTS) $(TARGET)");
    let _ = writeln!(out);
    let _ = writeln!(out, "test: $(TARGET)");
    let _ = writeln!(out, "\t./$(TARGET)");

    out
}

fn render_test_file(category: &str, fixtures: &[&Fixture]) -> (String, Vec<String>) {
    let mut out = String::new();
    let mut test_functions = Vec::new();

    let _ = writeln!(out, "/*! E2e tests for category: {}", category);
    let _ = writeln!(
        out,
        " *  Generated by html-to-markdown-e2e-generator — do not edit manually."
    );
    let _ = writeln!(out, " */");
    let _ = writeln!(out);
    let _ = writeln!(out, "#include <assert.h>");
    let _ = writeln!(out, "#include <string.h>");
    let _ = writeln!(out, "#include <stdio.h>");
    let _ = writeln!(out, "#include \"html_to_markdown.h\"");
    let _ = writeln!(out);

    for fixture in fixtures {
        let fn_name = sanitize_ident(&fixture.id);
        render_test_function(&mut out, fixture);
        test_functions.push(format!("test_{}", fn_name));
        let _ = writeln!(out);
    }

    (out, test_functions)
}

fn render_test_function(out: &mut String, fixture: &Fixture) {
    let fn_name = sanitize_ident(&fixture.id);
    let description = &fixture.description;

    let _ = writeln!(out, "void test_{}(void) {{", fn_name);
    let _ = writeln!(out, "    /* {} */", description);

    // HTML input
    match &fixture.html {
        Some(html) => {
            let escaped = escape_c_string(html);
            let _ = writeln!(out, "    const char *html = \"{}\";", escaped);
        }
        None => {
            let _ = writeln!(out, "    /* SKIP: no inline html */");
            let _ = writeln!(out, "}}");
            return;
        }
    }

    // Conversion call
    if fixture.assertions.expect_error == Some(true) {
        let _ = writeln!(out, "    char *result = html_to_markdown_convert(html, NULL);");
        let _ = writeln!(out, "    assert(result == NULL && \"expected conversion to fail\");");
        if let Some(contains) = &fixture.assertions.error_contains {
            // Note: error message checking would require additional API
            let _ = writeln!(
                out,
                "    /* TODO: error message check: {} */",
                escape_c_string(contains)
            );
        }
        let _ = writeln!(out, "}}");
        return;
    }

    let _ = writeln!(out, "    char *result = html_to_markdown_convert(html, NULL);");
    let _ = writeln!(out, "    assert(result != NULL && \"conversion should succeed\");");
    let _ = writeln!(out);

    let a = &fixture.assertions;

    // content_equals
    if let Some(expected) = &a.content_equals {
        let escaped = escape_c_string(expected);
        let _ = writeln!(out, "    /* content_equals */");
        let _ = writeln!(out, "    assert(strcmp(result, \"{}\") == 0);", escaped);
    }

    // content_not_empty
    if a.content_not_empty == Some(true) {
        let _ = writeln!(out, "    /* content_not_empty */");
        let _ = writeln!(out, "    assert(strlen(result) > 0);");
    }

    // content_is_none
    if a.content_is_none == Some(true) {
        let _ = writeln!(out, "    /* content_is_none */");
        let _ = writeln!(out, "    assert(strlen(result) == 0);");
    }

    // content_contains_all
    if let Some(substrings) = &a.content_contains_all {
        let _ = writeln!(out, "    /* content_contains_all */");
        for s in substrings {
            let escaped = escape_c_string(s);
            let _ = writeln!(out, "    assert(strstr(result, \"{}\") != NULL);", escaped);
        }
    }

    // content_contains_any
    if let Some(substrings) = &a.content_contains_any {
        let _ = writeln!(out, "    /* content_contains_any */");
        let checks: Vec<String> = substrings
            .iter()
            .map(|s| format!("strstr(result, \"{}\")", escape_c_string(s)))
            .collect();
        let condition = checks.join(" || ");
        let _ = writeln!(out, "    assert({});", condition);
    }

    // content_not_contains
    if let Some(substrings) = &a.content_not_contains {
        let _ = writeln!(out, "    /* content_not_contains */");
        for s in substrings {
            let escaped = escape_c_string(s);
            let _ = writeln!(out, "    assert(strstr(result, \"{}\") == NULL);", escaped);
        }
    }

    // min_content_length
    if let Some(min) = a.min_content_length {
        let _ = writeln!(out, "    /* min_content_length */");
        let _ = writeln!(out, "    assert(strlen(result) >= {});", min);
    }

    // max_content_length
    if let Some(max) = a.max_content_length {
        let _ = writeln!(out, "    /* max_content_length */");
        let _ = writeln!(out, "    assert(strlen(result) <= {});", max);
    }

    // content_starts_with
    if let Some(prefix) = &a.content_starts_with {
        let escaped = escape_c_string(prefix);
        let _ = writeln!(out, "    /* content_starts_with */");
        let _ = writeln!(
            out,
            "    assert(strncmp(result, \"{}\", {}) == 0);",
            escaped,
            escaped.len()
        );
    }

    // content_ends_with
    if let Some(suffix) = &a.content_ends_with {
        let escaped = escape_c_string(suffix);
        let suffix_len = escaped.len();
        let _ = writeln!(out, "    /* content_ends_with */");
        let _ = writeln!(
            out,
            "    size_t len = strlen(result); size_t suffix_len = {}; assert(len >= suffix_len && strcmp(&result[len - suffix_len], \"{}\") == 0);",
            suffix_len, escaped
        );
    }

    let _ = writeln!(out, "    html_to_markdown_free_string(result);");
    let _ = writeln!(out, "}}");
}

/// Convert a string to a valid C identifier by replacing non-alphanumeric chars with `_`.
fn sanitize_ident(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    // Remove leading digits
    if out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// Escape a string for use inside a C `"..."` string literal.
fn escape_c_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}
