//! Go test generator for html-to-markdown e2e tests.
//!
//! Generates `e2e/go/{category}_test.go` files and a `go.mod`.

use crate::fixtures::Fixture;
use anyhow::Result;
use camino::Utf8Path;
use itertools::Itertools;
use std::collections::HashMap;
use std::fmt::Write as FmtWrite;

/// Generate Go e2e tests from fixtures into `output_dir/go/`.
pub fn generate(fixtures: &[Fixture], output_dir: &Utf8Path) -> Result<usize> {
    let go_dir = output_dir.join("go");
    std::fs::create_dir_all(&go_dir)?;

    // Group fixtures by category.
    let by_category: HashMap<&str, Vec<&Fixture>> = fixtures
        .iter()
        .filter(|f| !f.is_skipped_for("go"))
        .into_group_map_by(|f| f.resolved_category());

    let mut total = 0;

    for (category, category_fixtures) in &by_category {
        let file_name = format!("{}_test.go", sanitize_filename(category));
        let path = go_dir.join(&file_name);
        let content = render_test_file(category, category_fixtures);
        std::fs::write(&path, content)?;
        total += category_fixtures.len();
    }

    // Generate go.mod.
    let go_mod = render_go_mod();
    std::fs::write(go_dir.join("go.mod"), go_mod)?;

    Ok(total)
}

fn render_go_mod() -> String {
    r#"module github.com/kreuzberg-dev/html-to-markdown/e2e/go

go 1.26

require github.com/kreuzberg-dev/html-to-markdown/packages/go/v3 v3.0.0

replace github.com/kreuzberg-dev/html-to-markdown/packages/go/v3 => ../../packages/go/v3
"#
    .to_string()
}

fn render_test_file(category: &str, fixtures: &[&Fixture]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Code generated by html-to-markdown-e2e-generator; DO NOT EDIT.");
    let _ = writeln!(out);
    let _ = writeln!(out, "// E2e tests for category: {category}");
    let _ = writeln!(out, "package e2e_test");
    let _ = writeln!(out);
    let _ = writeln!(out, "import (");
    let _ = writeln!(out, "    \"strings\"");
    let _ = writeln!(out, "    \"testing\"");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "    htmd \"github.com/kreuzberg-dev/html-to-markdown/packages/go/v3/htmltomarkdown\""
    );
    let _ = writeln!(out, ")");
    let _ = writeln!(out);

    for (i, fixture) in fixtures.iter().enumerate() {
        render_test_function(&mut out, fixture);
        if i + 1 < fixtures.len() {
            let _ = writeln!(out);
        }
    }

    // Ensure final newline
    while out.ends_with("\n\n") {
        out.pop();
    }
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

fn render_test_function(out: &mut String, fixture: &Fixture) {
    let fn_name = sanitize_func_name(&fixture.id);
    let description = &fixture.description;

    // HTML input.
    let html = match &fixture.html {
        Some(html) => html.as_str(),
        None => {
            let _ = writeln!(out, "func Test_{fn_name}(t *testing.T) {{");
            let _ = writeln!(out, "    t.Skip(\"no inline html\")");
            let _ = writeln!(out, "}}");
            return;
        }
    };

    let html_literal = go_string_literal(html);

    // Conversion call + error handling.
    if fixture.assertions.expect_error == Some(true) {
        let _ = writeln!(out, "func Test_{fn_name}(t *testing.T) {{");
        let _ = writeln!(out, "    // {description}");
        let _ = writeln!(out, "    html := {html_literal}");
        let _ = writeln!(out, "    _, err := htmd.Convert(html)");
        let _ = writeln!(out, "    if err == nil {{");
        let _ = writeln!(
            out,
            "        t.Errorf(\"expected conversion to fail, but it succeeded\")"
        );
        let _ = writeln!(out, "    }}");
        if let Some(contains) = &fixture.assertions.error_contains {
            let escaped = escape_string(contains);
            let _ = writeln!(out, "    if !strings.Contains(err.Error(), \"{escaped}\") {{");
            let _ = writeln!(out, "        t.Errorf(\"error message mismatch: got %v\", err)");
            let _ = writeln!(out, "    }}");
        }
        let _ = writeln!(out, "}}");
        return;
    }

    let _ = writeln!(out, "func Test_{fn_name}(t *testing.T) {{");
    let _ = writeln!(out, "    // {description}");
    let _ = writeln!(out, "    html := {html_literal}");
    let _ = writeln!(out, "    result, err := htmd.Convert(html)");
    let _ = writeln!(out, "    if err != nil {{");
    let _ = writeln!(out, "        t.Fatalf(\"conversion failed: %v\", err)");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "    content := \"\"");
    let _ = writeln!(out, "    if result != nil && result.Content != nil {{");
    let _ = writeln!(out, "        content = *result.Content");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out);

    let a = &fixture.assertions;

    // content_equals
    if let Some(expected) = &a.content_equals {
        let escaped = escape_string(expected);
        let _ = writeln!(out, "    if strings.TrimSpace(content) != \"{escaped}\" {{");
        let _ = writeln!(out, "        t.Errorf(\"content_equals mismatch: got %q\", content)");
        let _ = writeln!(out, "    }}");
    }

    // content_not_empty
    if a.content_not_empty == Some(true) {
        let _ = writeln!(out, "    if strings.TrimSpace(content) == \"\" {{");
        let _ = writeln!(out, "        t.Errorf(\"expected non-empty content\")");
        let _ = writeln!(out, "    }}");
    }

    // content_is_none
    if a.content_is_none == Some(true) {
        let _ = writeln!(out, "    if strings.TrimSpace(content) != \"\" {{");
        let _ = writeln!(out, "        t.Errorf(\"expected empty/nil content, got %q\", content)");
        let _ = writeln!(out, "    }}");
    }

    // content_contains_all
    if let Some(substrings) = &a.content_contains_all {
        for s in substrings {
            let escaped = escape_string(s);
            let _ = writeln!(out, "    if !strings.Contains(content, \"{escaped}\") {{");
            let _ = writeln!(out, "        t.Errorf(\"expected content to contain: {escaped}\")");
            let _ = writeln!(out, "    }}");
        }
    }

    // content_contains_any
    if let Some(substrings) = &a.content_contains_any {
        let _ = writeln!(out, "    foundAny := false");
        for s in substrings {
            let escaped = escape_string(s);
            let _ = writeln!(out, "    if strings.Contains(content, \"{escaped}\") {{");
            let _ = writeln!(out, "        foundAny = true");
            let _ = writeln!(out, "    }}");
        }
        let _ = writeln!(out, "    if !foundAny {{");
        let _ = writeln!(
            out,
            "        t.Errorf(\"expected content to contain at least one of the specified strings\")"
        );
        let _ = writeln!(out, "    }}");
    }

    // content_not_contains
    if let Some(substrings) = &a.content_not_contains {
        for s in substrings {
            let escaped = escape_string(s);
            let _ = writeln!(out, "    if strings.Contains(content, \"{escaped}\") {{");
            let _ = writeln!(out, "        t.Errorf(\"expected content NOT to contain: {escaped}\")");
            let _ = writeln!(out, "    }}");
        }
    }

    // min_content_length
    if let Some(min) = a.min_content_length {
        let _ = writeln!(out, "    if len(content) < {min} {{");
        let _ = writeln!(
            out,
            "        t.Errorf(\"expected content length >= {min}, got %d\", len(content))"
        );
        let _ = writeln!(out, "    }}");
    }

    // max_content_length
    if let Some(max) = a.max_content_length {
        let _ = writeln!(out, "    if len(content) > {max} {{");
        let _ = writeln!(
            out,
            "        t.Errorf(\"expected content length <= {max}, got %d\", len(content))"
        );
        let _ = writeln!(out, "    }}");
    }

    // content_starts_with
    if let Some(prefix) = &a.content_starts_with {
        let escaped = escape_string(prefix);
        let _ = writeln!(out, "    if !strings.HasPrefix(content, \"{escaped}\") {{");
        let _ = writeln!(out, "        t.Errorf(\"expected content to start with: {escaped}\")");
        let _ = writeln!(out, "    }}");
    }

    // content_ends_with
    if let Some(suffix) = &a.content_ends_with {
        let escaped = escape_string(suffix);
        let _ = writeln!(out, "    if !strings.HasSuffix(content, \"{escaped}\") {{");
        let _ = writeln!(out, "        t.Errorf(\"expected content to end with: {escaped}\")");
        let _ = writeln!(out, "    }}");
    }

    // ---- Metadata / Table / Warning assertions ----
    // Go's Convert() currently returns (string, error) — only content is available.
    // Structured result assertions will be added in Stage 2.
    let has_non_content_assertion = a.metadata_title.is_some()
        || a.metadata_description.is_some()
        || a.metadata_author.is_some()
        || a.metadata_keywords.is_some()
        || a.metadata_canonical_url.is_some()
        || a.metadata_og_title.is_some()
        || a.metadata_og_description.is_some()
        || a.metadata_og_image.is_some()
        || a.metadata_og_type.is_some()
        || a.metadata_og_url.is_some()
        || a.metadata_og_site_name.is_some()
        || a.metadata_twitter_card.is_some()
        || a.metadata_twitter_title.is_some()
        || a.metadata_twitter_description.is_some()
        || a.metadata_has_links.is_some()
        || a.metadata_link_count_min.is_some()
        || a.metadata_links_include_urls.is_some()
        || a.metadata_links_count_min.is_some()
        || a.metadata_has_headers.is_some()
        || a.metadata_header_count_min.is_some()
        || a.metadata_images_count_min.is_some()
        || a.metadata_images_include_srcs.is_some()
        || a.metadata_headings_count_min.is_some()
        || a.metadata_headings_include.is_some()
        || a.table_count_min.is_some()
        || a.table_contains_cell.is_some()
        || a.warnings_empty.is_some();

    if has_non_content_assertion {
        let _ = writeln!(
            out,
            "    // TODO(v3-parity): metadata/table/warning assertions require ConversionResult return type"
        );
    }

    let _ = writeln!(out, "}}");
}

/// Convert a category name to a valid filename.
fn sanitize_filename(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    out
}

/// Convert a fixture id to a valid Go function name (PascalCase).
fn sanitize_func_name(s: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = true;

    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() {
            if capitalize_next {
                out.push(ch.to_ascii_uppercase());
                capitalize_next = false;
            } else {
                out.push(ch);
            }
        } else if ch == '_' || ch == '-' || ch == ' ' {
            capitalize_next = true;
        }
    }

    out
}

/// Escape a string for use inside a Go double-quoted string literal.
fn escape_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

/// Format a Go string literal for the given content.
/// Uses raw strings (backticks) when possible, falls back to double-quoted strings.
fn go_string_literal(s: &str) -> String {
    if s.contains('`') {
        format!("\"{}\"", escape_string(s))
    } else {
        let clean = s.replace('\r', "");
        format!("`{clean}`")
    }
}
