//! PHP test generator for html-to-markdown e2e tests.
//!
//! Generates `e2e/php/tests/{Category}Test.php` using PHPUnit.

use crate::fixtures::Fixture;
use anyhow::Result;
use camino::Utf8Path;
use itertools::Itertools;
use std::collections::HashMap;
use std::fmt::Write as FmtWrite;

/// Generate PHP e2e tests from fixtures into `output_dir/php/`.
pub fn generate(fixtures: &[Fixture], output_dir: &Utf8Path) -> Result<usize> {
    let php_dir = output_dir.join("php");
    let tests_dir = php_dir.join("tests");
    std::fs::create_dir_all(&tests_dir)?;

    // Group fixtures by category.
    let by_category: HashMap<&str, Vec<&Fixture>> = fixtures
        .iter()
        .filter(|f| !f.is_skipped_for("php"))
        .into_group_map_by(|f| f.resolved_category());

    let mut total = 0;

    for (category, category_fixtures) in &by_category {
        let class_name = capitalize_category(category);
        let file_name = format!("{}Test.php", class_name);
        let path = tests_dir.join(&file_name);
        let content = render_test_file(category, &class_name, category_fixtures);
        std::fs::write(&path, content)?;
        total += category_fixtures.len();
    }

    Ok(total)
}

fn render_test_file(category: &str, class_name: &str, fixtures: &[&Fixture]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "<?php");
    let _ = writeln!(out, "// E2e tests for category: {category}");
    let _ = writeln!(
        out,
        "// Generated by html-to-markdown-e2e-generator — do not edit manually."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "declare(strict_types=1);");
    let _ = writeln!(out);
    let _ = writeln!(out, "namespace HtmlToMarkdown\\Tests;");
    let _ = writeln!(out);
    let _ = writeln!(out, "use PHPUnit\\Framework\\TestCase;");
    let _ = writeln!(out, "use function HtmlToMarkdown\\convert;");
    let _ = writeln!(out);
    let _ = writeln!(out, "class {class_name}Test extends TestCase {{");
    let _ = writeln!(out);

    for fixture in fixtures {
        render_test_function(&mut out, fixture);
        let _ = writeln!(out);
    }

    let _ = writeln!(out, "}}");

    out
}

fn render_test_function(out: &mut String, fixture: &Fixture) {
    let method_name = sanitize_method_name(&fixture.id);
    let description = &fixture.description;

    let _ = writeln!(out, "    /**");
    let _ = writeln!(out, "     * {description}");
    let _ = writeln!(out, "     */");
    let _ = writeln!(out, "    public function test{method_name}(): void");
    let _ = writeln!(out, "    {{");

    // HTML input.
    let html = match &fixture.html {
        Some(html) => html.as_str(),
        None => {
            let _ = writeln!(out, "        $this->markTestSkipped('no inline html');");
            let _ = writeln!(out, "    }}");
            return;
        }
    };

    let escaped_html = escape_php_string(html);
    let _ = writeln!(out, "        $html = \"{escaped_html}\";");

    // Conversion call + error handling.
    if fixture.assertions.expect_error == Some(true) {
        let _ = writeln!(out, "        $this->expectException(\\Exception::class);");
        if let Some(contains) = &fixture.assertions.error_contains {
            let escaped = escape_php_string(contains);
            let _ = writeln!(out, "        $this->expectExceptionMessageMatches('/{escaped}/');");
        }
        let _ = writeln!(out, "        convert($html);");
        let _ = writeln!(out, "    }}");
        return;
    }

    let _ = writeln!(out, "        $result = convert($html);");
    let _ = writeln!(out, "        $content = $result['content'] ?? '';");
    let _ = writeln!(out);

    let a = &fixture.assertions;

    // content_equals
    if let Some(expected) = &a.content_equals {
        let escaped = escape_php_string(expected);
        let _ = writeln!(out, "        $this->assertSame(\"{escaped}\", trim($content));");
    }

    // content_not_empty
    if a.content_not_empty == Some(true) {
        let _ = writeln!(
            out,
            "        $this->assertNotEmpty(trim($content), 'expected non-empty content');"
        );
    }

    // content_is_none
    if a.content_is_none == Some(true) {
        let _ = writeln!(
            out,
            "        $this->assertEmpty(trim($content), 'expected empty/None content');"
        );
    }

    // content_contains_all
    if let Some(substrings) = &a.content_contains_all {
        for s in substrings {
            let escaped = escape_php_string(s);
            let _ = writeln!(
                out,
                "        $this->assertStringContainsString(\"{escaped}\", $content);"
            );
        }
    }

    // content_contains_any
    if let Some(substrings) = &a.content_contains_any {
        let _ = writeln!(out, "        $found = false;");
        for s in substrings {
            let escaped = escape_php_string(s);
            let _ = writeln!(out, "        if (str_contains($content, \"{escaped}\")) $found = true;");
        }
        let _ = writeln!(
            out,
            "        $this->assertTrue($found, 'expected content to contain at least one of the specified strings');"
        );
    }

    // content_not_contains
    if let Some(substrings) = &a.content_not_contains {
        for s in substrings {
            let escaped = escape_php_string(s);
            let _ = writeln!(
                out,
                "        $this->assertStringNotContainsString(\"{escaped}\", $content);"
            );
        }
    }

    // min_content_length
    if let Some(min) = a.min_content_length {
        let _ = writeln!(
            out,
            "        $this->assertGreaterThanOrEqual({min}, strlen($content), 'expected content length >= {min}');"
        );
    }

    // max_content_length
    if let Some(max) = a.max_content_length {
        let _ = writeln!(
            out,
            "        $this->assertLessThanOrEqual({max}, strlen($content), 'expected content length <= {max}');"
        );
    }

    // content_starts_with
    if let Some(prefix) = &a.content_starts_with {
        let escaped = escape_php_string(prefix);
        let _ = writeln!(
            out,
            "        $this->assertTrue(str_starts_with($content, \"{escaped}\"), 'expected content to start with: {escaped}');"
        );
    }

    // content_ends_with
    if let Some(suffix) = &a.content_ends_with {
        let escaped = escape_php_string(suffix);
        let _ = writeln!(
            out,
            "        $this->assertTrue(str_ends_with($content, \"{escaped}\"), 'expected content to end with: {escaped}');"
        );
    }

    let _ = writeln!(out, "    }}");
}

/// Capitalize category name for PHP class naming.
fn capitalize_category(s: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = true;

    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() {
            if capitalize_next {
                out.push(ch.to_ascii_uppercase());
                capitalize_next = false;
            } else {
                out.push(ch.to_ascii_lowercase());
            }
        } else if ch == '_' || ch == '-' || ch == ' ' {
            capitalize_next = true;
        }
    }

    out
}

/// Convert a fixture id to a valid PHP method name (camelCase).
fn sanitize_method_name(s: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = false;

    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() {
            if capitalize_next {
                out.push(ch.to_ascii_uppercase());
                capitalize_next = false;
            } else if out.is_empty() {
                out.push(ch.to_ascii_uppercase()); // First character always uppercase for method
            } else {
                out.push(ch.to_ascii_lowercase());
            }
        } else if ch == '_' || ch == '-' {
            capitalize_next = true;
        }
    }

    out
}

/// Escape a string for use inside a PHP `"..."` string literal.
fn escape_php_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
        .replace('$', "\\$")
}
