//! R test generator for html-to-markdown e2e tests.
//!
//! Generates `e2e/r/tests/test_{category}.R` using testthat.

use crate::fixtures::Fixture;
use anyhow::Result;
use camino::Utf8Path;
use itertools::Itertools;
use std::collections::HashMap;
use std::fmt::Write as FmtWrite;

/// Generate R e2e tests from fixtures into `output_dir/r/`.
pub fn generate(fixtures: &[Fixture], output_dir: &Utf8Path) -> Result<usize> {
    let r_dir = output_dir.join("r");
    let tests_dir = r_dir.join("tests");
    std::fs::create_dir_all(&tests_dir)?;

    // Group fixtures by category.
    let by_category: HashMap<&str, Vec<&Fixture>> = fixtures
        .iter()
        .filter(|f| !f.is_skipped_for("r"))
        .into_group_map_by(|f| f.resolved_category());

    let mut total = 0;

    for (category, category_fixtures) in &by_category {
        let file_name = format!("test_{}.R", sanitize_name(category));
        let path = tests_dir.join(&file_name);
        let content = render_test_file(category, category_fixtures);
        std::fs::write(&path, content)?;
        total += category_fixtures.len();
    }

    // Generate testthat.R
    let testthat = render_testthat();
    std::fs::create_dir_all(tests_dir.join("testthat"))?;
    std::fs::write(tests_dir.join("testthat.R"), testthat)?;

    Ok(total)
}

fn render_testthat() -> String {
    r#"# Generated by html-to-markdown-e2e-generator — do not edit manually.
# This file enables running tests with testthat::test_dir("tests/testthat")

library(testthat)
library(htmltomarkdown)
"#
    .to_string()
}

fn render_test_file(category: &str, fixtures: &[&Fixture]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# E2e tests for category: {}", category);
    let _ = writeln!(
        out,
        "# Generated by html-to-markdown-e2e-generator — do not edit manually."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "library(testthat)");
    let _ = writeln!(out, "library(htmltomarkdown)");
    let _ = writeln!(out);

    for (i, fixture) in fixtures.iter().enumerate() {
        render_test_function(&mut out, fixture);
        if i + 1 < fixtures.len() {
            let _ = writeln!(out);
        }
    }

    // Ensure exactly one trailing newline
    while out.ends_with("\n\n") {
        out.pop();
    }
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

fn render_test_function(out: &mut String, fixture: &Fixture) {
    let description = &fixture.description;

    let _ = writeln!(out, "test_that(\"{}: {}\", {{", sanitize_name(&fixture.id), description);

    // HTML input
    match &fixture.html {
        Some(html) => {
            let escaped = escape_r_string(html);
            let _ = writeln!(out, "  html <- \"{}\"", escaped);
        }
        None => {
            let _ = writeln!(out, "  skip(\"no inline html\")");
            let _ = writeln!(out, "}})");
            return;
        }
    }

    // Build options list if specified.
    if let Some(opts) = &fixture.options {
        let entries: Vec<String> = opts
            .iter()
            .map(|(k, v)| {
                let snake_key = camel_to_snake(k);
                let r_val = json_value_to_r(v);
                format!("{snake_key} = {r_val}")
            })
            .collect();
        let list_literal = entries.join(", ");
        let _ = writeln!(out, "  opts <- list({})", list_literal);
    }

    let convert_call = if fixture.options.is_some() {
        "convert(html, options = opts)"
    } else {
        "convert(html)"
    };

    // Conversion call
    if fixture.assertions.expect_error == Some(true) {
        let _ = writeln!(out, "  expect_error({})", convert_call);
        if let Some(contains) = &fixture.assertions.error_contains {
            let escaped = escape_r_string(contains);
            let _ = writeln!(out, "  # Error should contain: {}", escaped);
        }
        let _ = writeln!(out, "}})");
        return;
    }

    let _ = writeln!(out, "  result <- {}", convert_call);
    let _ = writeln!(out, "  content <- result$content %||% \"\"");
    let _ = writeln!(out);

    let a = &fixture.assertions;

    // content_equals
    if let Some(expected) = &a.content_equals {
        let escaped = escape_r_string(expected);
        let _ = writeln!(out, "  expect_equal(trimws(content), \"{}\")", escaped);
    }

    // content_not_empty
    if a.content_not_empty == Some(true) {
        let _ = writeln!(out, "  expect_true(nchar(trimws(content)) > 0)");
    }

    // content_is_none
    if a.content_is_none == Some(true) {
        let _ = writeln!(out, "  expect_equal(nchar(trimws(content)), 0)");
    }

    // content_contains_all
    if let Some(substrings) = &a.content_contains_all {
        let _ = writeln!(out, "  # content_contains_all");
        for s in substrings {
            let escaped = escape_r_string(s);
            let _ = writeln!(out, "  expect_true(grepl(\"{}\", content, fixed = TRUE))", escaped);
        }
    }

    // content_contains_any
    if let Some(substrings) = &a.content_contains_any {
        let _ = writeln!(out, "  # content_contains_any");
        let checks: Vec<String> = substrings
            .iter()
            .map(|s| format!("grepl(\"{}\", content, fixed = TRUE)", escape_r_string(s)))
            .collect();
        let condition = checks.join(" || ");
        let _ = writeln!(out, "  expect_true({})", condition);
    }

    // content_not_contains
    if let Some(substrings) = &a.content_not_contains {
        let _ = writeln!(out, "  # content_not_contains");
        for s in substrings {
            let escaped = escape_r_string(s);
            let _ = writeln!(out, "  expect_false(grepl(\"{}\", content, fixed = TRUE))", escaped);
        }
    }

    // min_content_length
    if let Some(min) = a.min_content_length {
        let _ = writeln!(out, "  expect_true(nchar(content) >= {})", min);
    }

    // max_content_length
    if let Some(max) = a.max_content_length {
        let _ = writeln!(out, "  expect_true(nchar(content) <= {})", max);
    }

    // content_starts_with
    if let Some(prefix) = &a.content_starts_with {
        let escaped = escape_r_string(prefix);
        let _ = writeln!(out, "  expect_true(startsWith(trimws(content), \"{}\"))", escaped);
    }

    // content_ends_with
    if let Some(suffix) = &a.content_ends_with {
        let escaped = escape_r_string(suffix);
        let _ = writeln!(out, "  expect_true(endsWith(trimws(content), \"{}\"))", escaped);
    }

    let _ = writeln!(out, "}})");
}

/// Convert a string to a valid R identifier/name.
fn sanitize_name(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    // Remove leading digits
    if out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// Convert a camelCase string to snake_case.
fn camel_to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

/// Format a `serde_json::Value` as an R literal.
fn json_value_to_r(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::String(s) => {
            let lower = s.to_lowercase();
            format!("\"{}\"", escape_r_string(&lower))
        }
        serde_json::Value::Bool(true) => "TRUE".to_string(),
        serde_json::Value::Bool(false) => "FALSE".to_string(),
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::Null => "NULL".to_string(),
        other => format!("\"{}\"", escape_r_string(&other.to_string())),
    }
}

/// Escape a string for use inside an R `"..."` string literal.
fn escape_r_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}
