//! Ruby test generator for html-to-markdown e2e tests.
//!
//! Generates `e2e/ruby/spec/{category}_spec.rb` using RSpec.

use crate::fixtures::Fixture;
use anyhow::Result;
use camino::Utf8Path;
use itertools::Itertools;
use std::collections::HashMap;
use std::fmt::Write as FmtWrite;

/// Generate Ruby e2e tests from fixtures into `output_dir/ruby/`.
pub fn generate(fixtures: &[Fixture], output_dir: &Utf8Path) -> Result<usize> {
    let ruby_dir = output_dir.join("ruby");
    let spec_dir = ruby_dir.join("spec");
    std::fs::create_dir_all(&spec_dir)?;

    // Generate Gemfile.
    let gemfile = render_gemfile();
    std::fs::write(ruby_dir.join("Gemfile"), gemfile)?;

    // Group fixtures by category.
    let by_category: HashMap<&str, Vec<&Fixture>> = fixtures
        .iter()
        .filter(|f| !f.is_skipped_for("ruby"))
        .into_group_map_by(|f| f.resolved_category());

    let mut total = 0;

    for (category, category_fixtures) in &by_category {
        let file_name = format!("{}_spec.rb", sanitize_module_name(category));
        let path = spec_dir.join(&file_name);
        let content = render_test_file(category, category_fixtures);
        std::fs::write(&path, content)?;
        total += category_fixtures.len();
    }

    Ok(total)
}

fn render_gemfile() -> String {
    r#"# frozen_string_literal: true

source 'https://rubygems.org'

gem 'html-to-markdown', path: '../../packages/ruby'
gem 'rspec'
"#
    .to_string()
}

fn render_test_file(category: &str, fixtures: &[&Fixture]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# frozen_string_literal: true");
    let _ = writeln!(out);
    let _ = writeln!(out, "# E2e tests for category: {category}");
    let _ = writeln!(
        out,
        "# Generated by html-to-markdown-e2e-generator — do not edit manually."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "require 'html_to_markdown'");
    let _ = writeln!(out);
    let _ = writeln!(out, "RSpec.describe '{category}' do");
    let _ = writeln!(out);

    for fixture in fixtures {
        render_test_function(&mut out, fixture);
        let _ = writeln!(out);
    }

    let _ = writeln!(out, "end");

    out
}

fn render_test_function(out: &mut String, fixture: &Fixture) {
    let test_name = &fixture.id;
    let description = fixture.description.replace('\'', "\\'");

    let _ = writeln!(out, "  it '{test_name}: {description}' do");

    // HTML input.
    let html = match &fixture.html {
        Some(html) => html.as_str(),
        None => {
            let _ = writeln!(out, "    skip 'no inline html'");
            let _ = writeln!(out, "  end");
            return;
        }
    };

    let escaped_html = escape_ruby_string(html);
    let _ = writeln!(out, "    html = \"{escaped_html}\"");

    // Build options hash if specified.
    if let Some(opts) = &fixture.options {
        let entries: Vec<String> = opts
            .iter()
            .map(|(k, v)| {
                let snake_key = camel_to_snake(k);
                let rb_val = json_value_to_ruby(v);
                format!("\"{snake_key}\" => {rb_val}")
            })
            .collect();
        let hash_literal = entries.join(", ");
        let _ = writeln!(out, "    opts = {{ {hash_literal} }}");
    }

    let convert_call = if fixture.options.is_some() {
        "HtmlToMarkdown.convert(html, opts)"
    } else {
        "HtmlToMarkdown.convert(html)"
    };

    // Conversion call + error handling.
    if fixture.assertions.expect_error == Some(true) {
        let _ = writeln!(out, "    expect {{");
        let _ = writeln!(out, "      {convert_call}");
        let _ = writeln!(out, "    }}.to raise_error");
        if let Some(contains) = &fixture.assertions.error_contains {
            let escaped = escape_ruby_string(contains);
            let _ = writeln!(out, "    # Error should contain: {escaped}");
        }
        let _ = writeln!(out, "  end");
        return;
    }

    let _ = writeln!(out, "    result = {convert_call}");
    let _ = writeln!(out, "    content = result[:content] || ''");
    let _ = writeln!(out);

    let a = &fixture.assertions;

    // content_equals
    if let Some(expected) = &a.content_equals {
        let escaped = escape_ruby_string(expected);
        let _ = writeln!(out, "    expect(content.strip).to eq(\"{escaped}\")");
    }

    // content_not_empty
    if a.content_not_empty == Some(true) {
        let _ = writeln!(out, "    expect(content.strip).not_to be_empty");
    }

    // content_is_none
    if a.content_is_none == Some(true) {
        let _ = writeln!(out, "    expect(content.strip).to be_empty");
    }

    // content_contains_all
    if let Some(substrings) = &a.content_contains_all {
        for s in substrings {
            let escaped = escape_ruby_string(s);
            let _ = writeln!(out, "    expect(content).to include(\"{escaped}\")");
        }
    }

    // content_contains_any
    if let Some(substrings) = &a.content_contains_any {
        let checks: Vec<String> = substrings
            .iter()
            .map(|s| format!("content.include?(\"{}\")", escape_ruby_string(s)))
            .collect();
        let condition = checks.join(" || ");
        let _ = writeln!(out, "    expect({condition}).to be true");
    }

    // content_not_contains
    if let Some(substrings) = &a.content_not_contains {
        for s in substrings {
            let escaped = escape_ruby_string(s);
            let _ = writeln!(out, "    expect(content).not_to include(\"{escaped}\")");
        }
    }

    // min_content_length
    if let Some(min) = a.min_content_length {
        let _ = writeln!(out, "    expect(content.length).to be >= {min}");
    }

    // max_content_length
    if let Some(max) = a.max_content_length {
        let _ = writeln!(out, "    expect(content.length).to be <= {max}");
    }

    // content_starts_with
    if let Some(prefix) = &a.content_starts_with {
        let escaped = escape_ruby_string(prefix);
        let _ = writeln!(out, "    expect(content).to start_with(\"{escaped}\")");
    }

    // content_ends_with
    if let Some(suffix) = &a.content_ends_with {
        let escaped = escape_ruby_string(suffix);
        let _ = writeln!(out, "    expect(content).to end_with(\"{escaped}\")");
    }

    let _ = writeln!(out, "  end");
}

/// Convert a category name to a valid Ruby module name.
fn sanitize_module_name(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    out
}

/// Convert a camelCase string to snake_case.
fn camel_to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

/// Format a `serde_json::Value` as a Ruby literal.
fn json_value_to_ruby(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::String(s) => {
            let snake = camel_to_snake(s);
            format!("\"{}\"", escape_ruby_string(&snake))
        }
        serde_json::Value::Bool(true) => "true".to_string(),
        serde_json::Value::Bool(false) => "false".to_string(),
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::Null => "nil".to_string(),
        other => format!("\"{}\"", escape_ruby_string(&other.to_string())),
    }
}

/// Escape a string for use inside a Ruby `"..."` string literal.
fn escape_ruby_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
        .replace('#', "\\#")
}
