//! Rust test generator for html-to-markdown e2e tests.
//!
//! Generates `e2e/rust/tests/{category}_test.rs` and a `Cargo.toml`.

use crate::fixtures::Fixture;
use anyhow::Result;
use camino::Utf8Path;
use itertools::Itertools;
use std::collections::HashMap;
use std::fmt::Write as FmtWrite;

/// Generate Rust e2e tests from fixtures into `output_dir/rust/`.
pub fn generate(fixtures: &[Fixture], output_dir: &Utf8Path) -> Result<usize> {
    let rust_dir = output_dir.join("rust");
    let tests_dir = rust_dir.join("tests");
    std::fs::create_dir_all(&tests_dir)?;

    // Group fixtures by category.
    let by_category: HashMap<&str, Vec<&Fixture>> = fixtures
        .iter()
        .filter(|f| !f.is_skipped_for("rust"))
        .into_group_map_by(|f| f.resolved_category());

    let mut total = 0;

    for (category, category_fixtures) in &by_category {
        let file_name = format!("{}_test.rs", sanitize_ident(category));
        let path = tests_dir.join(&file_name);
        let content = render_test_file(category, category_fixtures);
        std::fs::write(&path, content)?;
        total += category_fixtures.len();
    }

    // Generate Cargo.toml.
    let cargo_toml = render_cargo_toml();
    std::fs::write(rust_dir.join("Cargo.toml"), cargo_toml)?;

    Ok(total)
}

fn render_cargo_toml() -> String {
    r#"[package]
name = "html-to-markdown-e2e-rust"
version = "0.1.0"
edition = "2021"
publish = false

# Standalone crate — not part of the workspace to avoid circular dependency.
[workspace]

[dependencies]
html-to-markdown-rs = { path = "../../crates/html-to-markdown" }

[[test]]
name = "smoke_test"
path = "tests/smoke_test.rs"
"#
    .to_string()
}

fn render_test_file(category: &str, fixtures: &[&Fixture]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "//! E2e tests for category: {category}");
    let _ = writeln!(
        out,
        "//! Generated by html-to-markdown-e2e-generator — do not edit manually."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "use html_to_markdown_rs::convert;");
    let _ = writeln!(out);

    for fixture in fixtures {
        render_test_function(&mut out, fixture);
        let _ = writeln!(out);
    }

    // Ensure final newline
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

fn render_test_function(out: &mut String, fixture: &Fixture) {
    let fn_name = sanitize_ident(&fixture.id);
    let description = &fixture.description;

    let _ = writeln!(out, "#[test]");
    let _ = writeln!(out, "fn test_{fn_name}() {{");
    let _ = writeln!(out, "    // {description}");

    // HTML input.
    match &fixture.html {
        Some(html) => {
            let literal = raw_string_literal(html);
            let _ = writeln!(out, "    let html = {literal};");
        }
        None => {
            // html_file is not supported in the inline Rust generator.
            let _ = writeln!(out, "    // SKIP: no inline html");
            let _ = writeln!(out, "}}");
            return;
        }
    }

    // Conversion call.
    if fixture.assertions.expect_error == Some(true) {
        let _ = writeln!(out, "    let result = convert(html, None);");
        let _ = writeln!(out, "    assert!(result.is_err(), \"expected conversion to fail\");");
        if let Some(contains) = &fixture.assertions.error_contains {
            let escaped = escape_string(contains);
            let _ = writeln!(
                out,
                "    assert!(result.unwrap_err().to_string().contains(\"{escaped}\"), \"error message mismatch\");"
            );
        }
        let _ = writeln!(out, "}}");
        return;
    }

    let _ = writeln!(
        out,
        "    let result = convert(html, None).expect(\"conversion should succeed\");"
    );
    let _ = writeln!(out, "    let content = result.content.unwrap_or_default();");
    let _ = writeln!(out);

    let a = &fixture.assertions;

    // content_equals
    if let Some(expected) = &a.content_equals {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(content.trim(), \"{escaped}\", \"content_equals mismatch\");"
        );
    }

    // content_not_empty
    if a.content_not_empty == Some(true) {
        let _ = writeln!(
            out,
            "    assert!(!content.trim().is_empty(), \"expected non-empty content\");"
        );
    }

    // content_is_none
    if a.content_is_none == Some(true) {
        let _ = writeln!(
            out,
            "    assert!(result.content.as_deref().unwrap_or(\"\").is_empty(), \"expected empty/None content\");"
        );
    }

    // content_contains_all
    if let Some(substrings) = &a.content_contains_all {
        for s in substrings {
            let escaped = escape_string(s);
            let _ = writeln!(
                out,
                "    assert!(content.contains(\"{escaped}\"), \"expected content to contain: {escaped}\");"
            );
        }
    }

    // content_contains_any
    if let Some(substrings) = &a.content_contains_any {
        let checks: Vec<String> = substrings
            .iter()
            .map(|s| format!("content.contains(\"{}\")", escape_string(s)))
            .collect();
        let condition = checks.join(" || ");
        let _ = writeln!(
            out,
            "    assert!({condition}, \"expected content to contain at least one of the specified strings\");"
        );
    }

    // content_not_contains
    if let Some(substrings) = &a.content_not_contains {
        for s in substrings {
            let escaped = escape_string(s);
            let _ = writeln!(
                out,
                "    assert!(!content.contains(\"{escaped}\"), \"expected content NOT to contain: {escaped}\");"
            );
        }
    }

    // min_content_length
    if let Some(min) = a.min_content_length {
        let _ = writeln!(
            out,
            "    assert!(content.len() >= {min}, \"expected content length >= {min}, got {{}}\", content.len());"
        );
    }

    // max_content_length
    if let Some(max) = a.max_content_length {
        let _ = writeln!(
            out,
            "    assert!(content.len() <= {max}, \"expected content length <= {max}, got {{}}\", content.len());"
        );
    }

    // content_starts_with
    if let Some(prefix) = &a.content_starts_with {
        let escaped = escape_string(prefix);
        let _ = writeln!(
            out,
            "    assert!(content.starts_with(\"{escaped}\"), \"expected content to start with: {escaped}\");"
        );
    }

    // content_ends_with
    if let Some(suffix) = &a.content_ends_with {
        let escaped = escape_string(suffix);
        let _ = writeln!(
            out,
            "    assert!(content.ends_with(\"{escaped}\"), \"expected content to end with: {escaped}\");"
        );
    }

    // ---- Metadata assertions ----

    // metadata_title
    if let Some(expected) = &a.metadata_title {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(result.metadata.document.title.as_deref(), Some(\"{escaped}\"), \"metadata_title mismatch\");"
        );
    }

    // metadata_description
    if let Some(expected) = &a.metadata_description {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(result.metadata.document.description.as_deref(), Some(\"{escaped}\"), \"metadata_description mismatch\");"
        );
    }

    // metadata_author
    if let Some(expected) = &a.metadata_author {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(result.metadata.document.author.as_deref(), Some(\"{escaped}\"), \"metadata_author mismatch\");"
        );
    }

    // metadata_keywords (comma-separated string)
    if let Some(keywords_str) = &a.metadata_keywords {
        for kw in keywords_str.split(',').map(|s| s.trim()) {
            let escaped = escape_string(kw);
            let _ = writeln!(
                out,
                "    assert!(result.metadata.document.keywords.iter().any(|k| k == \"{escaped}\"), \"expected keyword: {escaped}\");"
            );
        }
    }

    // metadata_canonical_url
    if let Some(expected) = &a.metadata_canonical_url {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(result.metadata.document.canonical_url.as_deref(), Some(\"{escaped}\"), \"metadata_canonical_url mismatch\");"
        );
    }

    // metadata_og_title
    if let Some(expected) = &a.metadata_og_title {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(result.metadata.document.open_graph.get(\"title\").map(|s| s.as_str()), Some(\"{escaped}\"), \"metadata_og_title mismatch\");"
        );
    }

    // metadata_og_description
    if let Some(expected) = &a.metadata_og_description {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(result.metadata.document.open_graph.get(\"description\").map(|s| s.as_str()), Some(\"{escaped}\"), \"metadata_og_description mismatch\");"
        );
    }

    // metadata_og_image
    if let Some(expected) = &a.metadata_og_image {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(result.metadata.document.open_graph.get(\"image\").map(|s| s.as_str()), Some(\"{escaped}\"), \"metadata_og_image mismatch\");"
        );
    }

    // metadata_og_type
    if let Some(expected) = &a.metadata_og_type {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(result.metadata.document.open_graph.get(\"type\").map(|s| s.as_str()), Some(\"{escaped}\"), \"metadata_og_type mismatch\");"
        );
    }

    // metadata_og_url
    if let Some(expected) = &a.metadata_og_url {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(result.metadata.document.open_graph.get(\"url\").map(|s| s.as_str()), Some(\"{escaped}\"), \"metadata_og_url mismatch\");"
        );
    }

    // metadata_og_site_name
    if let Some(expected) = &a.metadata_og_site_name {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(result.metadata.document.open_graph.get(\"site_name\").map(|s| s.as_str()), Some(\"{escaped}\"), \"metadata_og_site_name mismatch\");"
        );
    }

    // metadata_twitter_card
    if let Some(expected) = &a.metadata_twitter_card {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(result.metadata.document.twitter_card.get(\"card\").map(|s| s.as_str()), Some(\"{escaped}\"), \"metadata_twitter_card mismatch\");"
        );
    }

    // metadata_twitter_title
    if let Some(expected) = &a.metadata_twitter_title {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(result.metadata.document.twitter_card.get(\"title\").map(|s| s.as_str()), Some(\"{escaped}\"), \"metadata_twitter_title mismatch\");"
        );
    }

    // metadata_twitter_description
    if let Some(expected) = &a.metadata_twitter_description {
        let escaped = escape_string(expected);
        let _ = writeln!(
            out,
            "    assert_eq!(result.metadata.document.twitter_card.get(\"description\").map(|s| s.as_str()), Some(\"{escaped}\"), \"metadata_twitter_description mismatch\");"
        );
    }

    // metadata_has_links
    if a.metadata_has_links == Some(true) {
        let _ = writeln!(
            out,
            "    assert!(!result.metadata.links.is_empty(), \"expected metadata to include links\");"
        );
    }

    // metadata_link_count_min
    if let Some(min) = a.metadata_link_count_min {
        let _ = writeln!(
            out,
            "    assert!(result.metadata.links.len() >= {min}, \"expected at least {min} links, got {{}}\", result.metadata.links.len());"
        );
    }

    // metadata_links_count_min
    if let Some(min) = a.metadata_links_count_min {
        let _ = writeln!(
            out,
            "    assert!(result.metadata.links.len() >= {min}, \"expected at least {min} links, got {{}}\", result.metadata.links.len());"
        );
    }

    // metadata_links_include_urls
    if let Some(urls) = &a.metadata_links_include_urls {
        for url in urls {
            let escaped = escape_string(url);
            let _ = writeln!(
                out,
                "    assert!(result.metadata.links.iter().any(|l| l.href == \"{escaped}\"), \"expected links to include URL: {escaped}\");"
            );
        }
    }

    // metadata_has_headers
    if a.metadata_has_headers == Some(true) {
        let _ = writeln!(
            out,
            "    assert!(!result.metadata.headers.is_empty(), \"expected metadata to include headers\");"
        );
    }

    // metadata_header_count_min
    if let Some(min) = a.metadata_header_count_min {
        let _ = writeln!(
            out,
            "    assert!(result.metadata.headers.len() >= {min}, \"expected at least {min} headers, got {{}}\", result.metadata.headers.len());"
        );
    }

    // metadata_headings_count_min
    if let Some(min) = a.metadata_headings_count_min {
        let _ = writeln!(
            out,
            "    assert!(result.metadata.headers.len() >= {min}, \"expected at least {min} headings, got {{}}\", result.metadata.headers.len());"
        );
    }

    // metadata_headings_include
    if let Some(headings) = &a.metadata_headings_include {
        for heading in headings {
            let escaped = escape_string(heading);
            let _ = writeln!(
                out,
                "    assert!(result.metadata.headers.iter().any(|h| h.text == \"{escaped}\"), \"expected headings to include: {escaped}\");"
            );
        }
    }

    // metadata_images_count_min
    if let Some(min) = a.metadata_images_count_min {
        let _ = writeln!(
            out,
            "    assert!(result.metadata.images.len() >= {min}, \"expected at least {min} images, got {{}}\", result.metadata.images.len());"
        );
    }

    // metadata_images_include_srcs
    if let Some(srcs) = &a.metadata_images_include_srcs {
        for src in srcs {
            let escaped = escape_string(src);
            let _ = writeln!(
                out,
                "    assert!(result.metadata.images.iter().any(|i| i.src == \"{escaped}\"), \"expected images to include src: {escaped}\");"
            );
        }
    }

    // ---- Table assertions ----

    // table_count_min
    if let Some(min) = a.table_count_min {
        let _ = writeln!(
            out,
            "    assert!(result.tables.len() >= {min}, \"expected at least {min} tables, got {{}}\", result.tables.len());"
        );
    }

    // table_contains_cell
    if let Some(cell) = &a.table_contains_cell {
        let escaped = escape_string(cell);
        let _ = writeln!(
            out,
            "    assert!(result.tables.iter().any(|t| t.rows.iter().any(|r| r.cells.iter().any(|c| c.content.contains(\"{escaped}\")))), \"expected a table cell to contain: {escaped}\");"
        );
    }

    // ---- Warning assertions ----

    // warnings_empty
    if a.warnings_empty == Some(true) {
        let _ = writeln!(
            out,
            "    assert!(result.warnings.is_empty(), \"expected no warnings, got: {{:?}}\", result.warnings);"
        );
    }

    let _ = writeln!(out, "}}");
}

/// Convert a string to a valid Rust identifier by replacing non-alphanumeric chars with `_`.
fn sanitize_ident(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    // Remove leading digits.
    if out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// Escape a string for use inside a Rust `"..."` string literal.
fn escape_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

/// Determine how many `#` delimiters are needed for a raw string containing `s`.
fn raw_string_hashes(s: &str) -> usize {
    let mut max_run = 0;
    let mut run = 0;
    let mut after_quote = false;
    for ch in s.chars() {
        if ch == '"' {
            after_quote = true;
            run = 0;
        } else if ch == '#' && after_quote {
            run += 1;
            if run > max_run {
                max_run = run;
            }
        } else {
            after_quote = false;
            run = 0;
        }
    }
    max_run + 1
}

/// Format a string as a Rust raw string literal with sufficient `#` delimiters.
fn raw_string_literal(s: &str) -> String {
    let clean = s.replace('\r', "");
    let hashes = raw_string_hashes(&clean);
    let h = "#".repeat(hashes);
    format!("r{h}\"{clean}\"{h}")
}
