//! TypeScript test generator for html-to-markdown e2e tests.
//!
//! Generates `e2e/typescript/tests/{category}.test.ts` and a `package.json`.

use crate::fixtures::Fixture;
use anyhow::Result;
use camino::Utf8Path;
use itertools::Itertools;
use std::collections::HashMap;
use std::fmt::Write as FmtWrite;

/// Generate TypeScript e2e tests from fixtures into `output_dir/typescript/`.
pub fn generate(fixtures: &[Fixture], output_dir: &Utf8Path) -> Result<usize> {
    let ts_dir = output_dir.join("typescript");
    let tests_dir = ts_dir.join("tests");
    std::fs::create_dir_all(&tests_dir)?;

    // Group fixtures by category.
    let by_category: HashMap<&str, Vec<&Fixture>> = fixtures
        .iter()
        .filter(|f| !f.is_skipped_for("typescript"))
        .into_group_map_by(|f| f.resolved_category());

    let mut total = 0;

    for (category, category_fixtures) in &by_category {
        let file_name = format!("{}.test.ts", sanitize_filename(category));
        let path = tests_dir.join(&file_name);
        let content = render_test_file(category, category_fixtures);
        std::fs::write(&path, content)?;
        total += category_fixtures.len();
    }

    // Generate package.json.
    let package_json = render_package_json();
    std::fs::write(ts_dir.join("package.json"), package_json)?;

    Ok(total)
}

fn render_package_json() -> String {
    r#"{
  "name": "html-to-markdown-e2e-typescript",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "test": "vitest run"
  },
  "devDependencies": {
    "@kreuzberg/html-to-markdown": "workspace:*",
    "vitest": "^1.0.0"
  }
}
"#
    .to_string()
}

fn render_test_file(category: &str, fixtures: &[&Fixture]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "/**");
    let _ = writeln!(out, " * E2e tests for category: {category}");
    let _ = writeln!(
        out,
        " * Generated by html-to-markdown-e2e-generator — do not edit manually."
    );
    let _ = writeln!(out, " */");
    let _ = writeln!(out, "import {{ describe, it, expect }} from 'vitest';");
    let _ = writeln!(out, "import {{ convert }} from '@kreuzberg/html-to-markdown';");
    let _ = writeln!(out);

    let _ = writeln!(out, "describe('{category}', () => {{");

    for fixture in fixtures {
        render_test_function(&mut out, fixture);
        let _ = writeln!(out);
    }

    let _ = writeln!(out, "}});");

    out
}

fn render_test_function(out: &mut String, fixture: &Fixture) {
    let fn_name = sanitize_test_name(&fixture.id);
    let description = &fixture.description;

    // HTML input.
    let html = match &fixture.html {
        Some(html) => html.as_str(),
        None => {
            let _ = writeln!(out, "  it.skip('{fn_name}: {description}', () => {{}});");
            return;
        }
    };

    let escaped_html = escape_template_string(html);

    // Conversion call + error handling.
    if fixture.assertions.expect_error == Some(true) {
        let _ = writeln!(out, "  it('{fn_name}: {description}', () => {{");
        let _ = writeln!(out, "    const html = `{escaped_html}`;");
        let _ = writeln!(out, "    expect(() => convert(html)).toThrow();");
        if let Some(contains) = &fixture.assertions.error_contains {
            let escaped = escape_string(contains);
            let _ = writeln!(out, "    try {{");
            let _ = writeln!(out, "      convert(html);");
            let _ = writeln!(out, "      expect.fail('Expected an error');");
            let _ = writeln!(out, "    }} catch (err) {{");
            let _ = writeln!(out, "      expect((err as Error).message).toContain('{escaped}');");
            let _ = writeln!(out, "    }}");
        }
        let _ = writeln!(out, "  }});");
        return;
    }

    let _ = writeln!(out, "  it('{fn_name}: {description}', () => {{");
    let _ = writeln!(out, "    const html = `{escaped_html}`;");
    let _ = writeln!(out, "    const result = convert(html);");
    let _ = writeln!(out, "    const content = result.content ?? '';");
    let _ = writeln!(out);

    let a = &fixture.assertions;

    // content_equals
    if let Some(expected) = &a.content_equals {
        let escaped = escape_string(expected);
        let _ = writeln!(out, "    expect(content.trim()).toBe('{escaped}');");
    }

    // content_not_empty
    if a.content_not_empty == Some(true) {
        let _ = writeln!(out, "    expect(content.trim().length).toBeGreaterThan(0);");
    }

    // content_is_none
    if a.content_is_none == Some(true) {
        let _ = writeln!(out, "    expect(content.trim()).toBe('');");
    }

    // content_contains_all
    if let Some(substrings) = &a.content_contains_all {
        for s in substrings {
            let escaped = escape_string(s);
            let _ = writeln!(out, "    expect(content).toContain('{escaped}');");
        }
    }

    // content_contains_any
    if let Some(substrings) = &a.content_contains_any {
        let checks: Vec<String> = substrings
            .iter()
            .map(|s| format!("content.includes('{}')", escape_string(s)))
            .collect();
        let condition = checks.join(" || ");
        let _ = writeln!(out, "    expect({condition}).toBe(true);");
    }

    // content_not_contains
    if let Some(substrings) = &a.content_not_contains {
        for s in substrings {
            let escaped = escape_string(s);
            let _ = writeln!(out, "    expect(content).not.toContain('{escaped}');");
        }
    }

    // min_content_length
    if let Some(min) = a.min_content_length {
        let _ = writeln!(out, "    expect(content.length).toBeGreaterThanOrEqual({min});");
    }

    // max_content_length
    if let Some(max) = a.max_content_length {
        let _ = writeln!(out, "    expect(content.length).toBeLessThanOrEqual({max});");
    }

    // content_starts_with
    if let Some(prefix) = &a.content_starts_with {
        let escaped = escape_string(prefix);
        let _ = writeln!(out, "    expect(content).toMatch(/^{}/);", regex_escape(&escaped));
    }

    // content_ends_with
    if let Some(suffix) = &a.content_ends_with {
        let escaped = escape_string(suffix);
        let _ = writeln!(out, "    expect(content).toMatch(/{}$/);", regex_escape(&escaped));
    }

    let _ = writeln!(out, "  }});");
}

/// Convert a category name to a valid filename.
fn sanitize_filename(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    out
}

/// Convert a fixture id to a valid test name.
fn sanitize_test_name(s: &str) -> String {
    // Keep alphanumeric and spaces/underscores, replace others with space
    s.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                ' '
            }
        })
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join("_")
}

/// Escape a string for use inside a JavaScript template literal (`...`).
fn escape_template_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('`', "\\`").replace("${", "\\${")
}

/// Escape a string for use inside a JavaScript string literal.
fn escape_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace("'", "\\'")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

/// Escape a string for use in a regex pattern.
fn regex_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('.', "\\.")
        .replace('^', "\\^")
        .replace('$', "\\$")
        .replace('*', "\\*")
        .replace('+', "\\+")
        .replace('?', "\\?")
        .replace('(', "\\(")
        .replace(')', "\\)")
        .replace('[', "\\[")
        .replace(']', "\\]")
        .replace('{', "\\{")
        .replace('}', "\\}")
        .replace('|', "\\|")
}
