/**
 * E2e tests for category: smoke
 * Generated by html-to-markdown-e2e-generator — do not edit manually.
 */
import { describe, it, expect } from 'vitest';
import { convert } from '@kreuzberg/html-to-markdown';

describe('smoke', () => {
  it('smoke_empty_string: Empty string produces empty output', () => {
    const html = ``;
    const result = convert(html);
    const content = result.content ?? '';

    expect(content.trim()).toBe('');
  });

  it('smoke_simple_heading: H1 heading converts to ATX markdown', () => {
    const html = `<h1>Title</h1>`;
    const result = convert(html);
    const content = result.content ?? '';

    expect(content).toContain('# Title');
  });

  it('smoke_simple_paragraph: Simple paragraph converts correctly', () => {
    const html = `<p>Hello World</p>`;
    const result = convert(html);
    const content = result.content ?? '';

    expect(content.trim()).toBe('Hello World');
    expect(content.trim().length).toBeGreaterThan(0);
  });

});
