# E2e tests for category: options
# Generated by html-to-markdown-e2e-generator — do not edit manually.

library(testthat)
library(htmltomarkdown)

test_that("options_code_block_backticks: Backticks code block style uses triple backtick fences", {
  html <- "<pre><code class=\"language-js\">console.log('hi');</code></pre>"
  result <- convert(html)
  content <- result$content %||% ""

  # content_contains_all
  expect_true(grepl("```", content, fixed = TRUE))
  expect_true(grepl("console.log('hi');", content, fixed = TRUE))
})

test_that("options_code_block_tildes: Tildes code block style uses triple tilde fences", {
  html <- "<pre><code>some code</code></pre>"
  result <- convert(html)
  content <- result$content %||% ""

  # content_contains_all
  expect_true(grepl("~~~", content, fixed = TRUE))
  expect_true(grepl("some code", content, fixed = TRUE))
})

test_that("options_escape_asterisks: escape_asterisks option escapes asterisks in plain text", {
  html <- "<p>Use 2*3 = 6 in math.</p>"
  result <- convert(html)
  content <- result$content %||% ""

  expect_true(nchar(trimws(content)) > 0)
  # content_contains_all
  expect_true(grepl("2", content, fixed = TRUE))
  expect_true(grepl("3", content, fixed = TRUE))
  expect_true(grepl("6", content, fixed = TRUE))
})

test_that("options_escape_misc: escape_misc option escapes miscellaneous markdown characters", {
  html <- "<p>Use # and | and ~ in text.</p>"
  result <- convert(html)
  content <- result$content %||% ""

  expect_true(nchar(trimws(content)) > 0)
  # content_contains_all
  expect_true(grepl("Use", content, fixed = TRUE))
  expect_true(grepl("and", content, fixed = TRUE))
  expect_true(grepl("in text.", content, fixed = TRUE))
})

test_that("options_escape_underscores: escape_underscores option escapes underscores in plain text", {
  html <- "<p>The variable_name is defined.</p>"
  result <- convert(html)
  content <- result$content %||% ""

  expect_true(nchar(trimws(content)) > 0)
  # content_contains_all
  expect_true(grepl("variable", content, fixed = TRUE))
  expect_true(grepl("name", content, fixed = TRUE))
  expect_true(grepl("defined.", content, fixed = TRUE))
})

test_that("options_heading_style_atx: ATX heading style produces hash-prefixed headings", {
  html <- "<h1>Title</h1><h2>Subtitle</h2>"
  result <- convert(html)
  content <- result$content %||% ""

  # content_contains_all
  expect_true(grepl("# Title", content, fixed = TRUE))
  expect_true(grepl("## Subtitle", content, fixed = TRUE))
})

test_that("options_heading_style_atx_closed: ATX closed heading style adds closing hashes", {
  html <- "<h1>Closed Heading</h1>"
  result <- convert(html)
  content <- result$content %||% ""

  # content_contains_all
  expect_true(grepl("# Closed Heading #", content, fixed = TRUE))
})

test_that("options_heading_style_underlined: Underlined heading style produces setext-style headings for h1 and h2", {
  html <- "<h1>Main Title</h1>"
  result <- convert(html)
  content <- result$content %||% ""

  expect_true(nchar(trimws(content)) > 0)
  # content_contains_all
  expect_true(grepl("Main Title", content, fixed = TRUE))
})

test_that("options_list_custom_bullets: Custom bullet character for unordered lists", {
  html <- "<ul><li>Item A</li><li>Item B</li></ul>"
  result <- convert(html)
  content <- result$content %||% ""

  # content_contains_all
  expect_true(grepl("* Item A", content, fixed = TRUE))
  expect_true(grepl("* Item B", content, fixed = TRUE))
})

test_that("options_list_indent_tabs: Tab indentation type for nested list items", {
  html <- "<ul><li>Parent<ul><li>Child</li></ul></li></ul>"
  result <- convert(html)
  content <- result$content %||% ""

  expect_true(nchar(trimws(content)) > 0)
  # content_contains_all
  expect_true(grepl("Parent", content, fixed = TRUE))
  expect_true(grepl("Child", content, fixed = TRUE))
})

test_that("options_output_format_djot: Djot output format produces djot-compatible markup", {
  html <- "<p>Simple paragraph.</p>"
  result <- convert(html)
  content <- result$content %||% ""

  expect_true(nchar(trimws(content)) > 0)
  # content_contains_all
  expect_true(grepl("Simple paragraph.", content, fixed = TRUE))
})

test_that("options_output_format_markdown: Default markdown output format produces standard markdown", {
  html <- "<h1>Title</h1><p>Some text.</p>"
  result <- convert(html)
  content <- result$content %||% ""

  # content_contains_all
  expect_true(grepl("# Title", content, fixed = TRUE))
  expect_true(grepl("Some text.", content, fixed = TRUE))
})

test_that("options_output_format_plain: Plain text output format strips markdown syntax", {
  html <- "<h1>Title</h1><p>Some <strong>bold</strong> text.</p>"
  result <- convert(html)
  content <- result$content %||% ""

  # content_contains_all
  expect_true(grepl("Title", content, fixed = TRUE))
  expect_true(grepl("bold", content, fixed = TRUE))
  expect_true(grepl("text.", content, fixed = TRUE))
  # content_not_contains
  expect_false(grepl("**bold**", content, fixed = TRUE))
  expect_false(grepl("# Title", content, fixed = TRUE))
})

test_that("options_whitespace_normalized: Normalized whitespace mode collapses multiple spaces", {
  html <- "<p>Text   with    extra   spaces.</p>"
  result <- convert(html)
  content <- result$content %||% ""

  expect_true(nchar(trimws(content)) > 0)
  # content_contains_all
  expect_true(grepl("Text", content, fixed = TRUE))
  expect_true(grepl("with", content, fixed = TRUE))
  expect_true(grepl("extra", content, fixed = TRUE))
  expect_true(grepl("spaces.", content, fixed = TRUE))
})

test_that("options_whitespace_strict: Strict whitespace mode preserves whitespace as-is", {
  html <- "<p>Preserved   spacing.</p>"
  result <- convert(html)
  content <- result$content %||% ""

  expect_true(nchar(trimws(content)) > 0)
  # content_contains_all
  expect_true(grepl("Preserved", content, fixed = TRUE))
  expect_true(grepl("spacing.", content, fixed = TRUE))
})

test_that("options_wrap_disabled: Wrap option disabled preserves long lines without breaking", {
  html <- "<p>This is a long paragraph that should not be wrapped at all because wrapping is disabled.</p>"
  result <- convert(html)
  content <- result$content %||% ""

  # content_contains_all
  expect_true(grepl("This is a long paragraph that should not be wrapped at all because wrapping is disabled.", content, fixed = TRUE))
})

test_that("options_wrap_enabled: Wrap option enabled with custom width wraps long lines", {
  html <- "<p>This is a long paragraph that should be wrapped at the specified column width when the wrap option is enabled.</p>"
  result <- convert(html)
  content <- result$content %||% ""

  expect_true(nchar(trimws(content)) > 0)
  # content_contains_all
  expect_true(grepl("This is a long paragraph", content, fixed = TRUE))
})
