# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c50487d07103a402dc5701c861b60fbf7426875bd30d51f212ba311fb965bdca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: smoke

test_that("smoke_empty_string: Empty string produces empty output", {
  result <- convert(html = "")
  expect_equal(trimws(result$content), "")
})

test_that("smoke_simple_heading: H1 heading converts to ATX markdown", {
  result <- convert(html = "<h1>Title</h1>")
  expect_true(grepl("# Title", result$content, fixed = TRUE))
})

test_that("smoke_simple_paragraph: Simple paragraph converts correctly", {
  result <- convert(html = "<p>Hello World</p>")
  expect_equal(trimws(result$content), "Hello World")
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
})
