// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const html_to_markdown_rs = @import("html_to_markdown_rs");

// E2e tests for category: edge-cases

test "empty_html" {
    // Empty HTML document
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head></head><body></body></html>");
    try testing.expectEqual("", result.content);
}

test "encoding_cjk_characters" {
    // CJK (Chinese, Japanese, Korean) characters are preserved
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<p>中文内容</p><p>日本語テキスト</p><p>한국어 텍스트</p>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "中文内容") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "日本語テキスト") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "한국어 텍스트") != null);
}

test "encoding_html_entities" {
    // Common HTML entities are decoded in output
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<p>&amp; &lt; &gt; &nbsp; &quot; &apos;</p>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "&") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "<") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, ">") != null);
}

test "encoding_named_entities" {
    // Named HTML entities like &mdash; and &hellip; are decoded
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<p>Em dash&mdash;used for parenthetical remarks&mdash;is common. Ellipsis&hellip; indicates omission. Non-breaking&nbsp;space.</p>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "—") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "…") != null);
}

test "encoding_numeric_entities" {
    // Numeric HTML entities (decimal and hex) are decoded
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<p>Copyright: &#169; Trade: &#174; Euro: &#8364; Hex: &#x00A9;</p>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "©") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "®") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "€") != null);
}

test "encoding_unicode_emoji" {
    // Emoji and Unicode characters are preserved
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<p>Hello 🌍 World 🚀</p><p>Stars: ⭐ ✨</p>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "🌍") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "🚀") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "⭐") != null);
}

test "html_comments_only" {
    // Document containing only HTML comments produces empty output
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<!-- This is a comment --><!-- Another comment -->");
    try testing.expectEqual("", result.content);
}

test "just_whitespace_input" {
    // Input that is only whitespace characters (spaces, tabs, newlines) produces empty output
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("   ");
    try testing.expectEqual("", result.content);
}

test "malformed_deeply_nested_elements" {
    // Deeply nested elements (100 levels) are handled without stack overflow
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><p>Deeply nested content</p></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "Deeply nested content") != null);
}

test "malformed_missing_block_closing_tags" {
    // Missing closing tags on block elements are auto-closed by parser
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<div><h1>Title<p>First paragraph<p>Second paragraph</div>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "Title") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "First paragraph") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "Second paragraph") != null);
}

test "malformed_overlapping_tags" {
    // Overlapping bold/italic tags are recovered by the HTML parser without panic
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<p><b><i>bold and italic</b></i></p>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "bold and italic") != null);
}

test "malformed_unclosed_paragraph" {
    // Unclosed <p> tag is recovered gracefully and content is preserved
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<p>This paragraph is never closed");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "This paragraph is never closed") != null);
}

test "script_tags_only" {
    // Document with only script tags produces empty output (scripts are stripped)
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><script>alert('xss')</script></head><body><script>document.write('hello')</script></body></html>");
    try testing.expectEqual("", result.content);
}

test "style_tags_only" {
    // Document with only style tags produces empty output (styles are stripped)
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><style>body { color: red; }</style></head><body><style>.foo { margin: 0; }</style></body></html>");
    try testing.expectEqual("", result.content);
}

test "visitor_custom_element_with_nesting" {
    // Visitor handles custom elements with nested content
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<div><custom-widget data-value=\"123\"><p>Widget content here</p><span>With nested elements</span></custom-widget></div>");
    try testing.expect(std.mem.indexOf(u8, result.content, "[CUSTOM WIDGET]") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "Widget content here") == null);
}

test "visitor_deeply_nested_skip" {
    // Visitor skips deeply nested elements
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<div><p>Outer <em>emphasis <strong>with bold <mark>and highlight</mark></strong></em> text</p></div>");
    try testing.expect(std.mem.indexOf(u8, result.content, "Outer") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "text") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "highlight") == null);
}

test "visitor_element_end_modification" {
    // Visitor modifies element at end after children processed
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<blockquote><p>Original quote</p></blockquote>");
    try testing.expect(result.content.len > 0);
}

test "visitor_element_start_skip_entire_subtree" {
    // Visitor skips at element_start level removes entire subtree
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<div><h1>Title</h1><p>Content</p></div>");
    try testing.expect(result.content.len > 0);
}

test "visitor_unknown_tag_preservation" {
    // Visitor preserves unknown HTML tags as raw HTML
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<article><p>Article text</p><x-custom>Custom element with content</x-custom><p>More article text</p></article>");
    try testing.expect(std.mem.indexOf(u8, result.content, "Article text") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "More article text") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "<x-custom>") != null);
}

test "whitespace_only" {
    // Whitespace-only content
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<p>   </p>");
    try testing.expectEqual("", result.content);
}

test "xss_onclick_handler_removed" {
    // onclick and other on* event handlers are removed from elements
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<p><a href=\"https://example.com\" onclick=\"alert('xss')\">Click me</a></p><button onmouseover=\"steal_data()\">Hover me</button>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "Click me") != null);
}

test "xss_script_tag_stripped" {
    // Script tag content is stripped and does not appear in output
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<p>Safe content.</p><script>alert('xss')</script><p>More safe content.</p>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "Safe content") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "More safe content") != null);
}

test "xss_svg_nested_script_stripped" {
    // Script tags nested inside SVG are stripped
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<p>Before SVG.</p><svg xmlns=\"http://www.w3.org/2000/svg\"><script>alert('svg-xss')</script><text>SVG text</text></svg><p>After SVG.</p>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "Before SVG") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "After SVG") != null);
}
