// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const html_to_markdown_rs = @import("html_to_markdown_rs");

// E2e tests for category: metadata

test "metadata_author_meta" {
    // Extract author from <meta name='author'> tag
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Page</title><meta name=\"author\" content=\"Jane Doe\"></head><body><p>Content</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expectEqual("Jane Doe", result.metadata.document.author);
}

test "metadata_canonical_url" {
    // Extract canonical URL from <link rel='canonical'> tag
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Page</title><link rel=\"canonical\" href=\"https://example.com/canonical-page\"></head><body><p>Content</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expectEqual("https://example.com/canonical-page", result.metadata.document.canonical_url);
}

test "metadata_description_meta" {
    // Extract description from <meta name='description'> tag
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Page</title><meta name=\"description\" content=\"This is the page description.\"></head><body><p>Content</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expectEqual("This is the page description.", result.metadata.document.description);
}

test "metadata_dublin_core" {
    // Extract Dublin Core metadata tags
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Scholarly Work</title><meta name=\"DC.title\" content=\"Principles of Knowledge Management\"><meta name=\"DC.creator\" content=\"Dr. Alice Johnson\"><meta name=\"DC.date\" content=\"2023-06-15\"><meta name=\"DC.subject\" content=\"Knowledge Management\"><meta name=\"DC.publisher\" content=\"Academic Press\"></head><body><p>This is a scholarly article.</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "scholarly article") != null);
}

test "metadata_extract_all_images" {
    // Extract all images from a document into metadata
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Gallery</title></head><body><img src=\"https://example.com/photo1.jpg\" alt=\"Photo 1\"><img src=\"https://example.com/photo2.png\" alt=\"Photo 2\"><img src=\"/local/image.webp\" alt=\"Local image\"></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(result.metadata.images.len >= 2);
}

test "metadata_extract_all_links" {
    // Extract all links from a document into metadata
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Links Page</title></head><body><p>Visit <a href=\"https://example.com\">Example</a> or <a href=\"https://docs.example.com\">Docs</a>.</p><p>Also see <a href=\"/relative/path\">relative link</a> and <a href=\"mailto:hello@example.com\">email us</a>.</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(result.metadata.links.len >= 2);
}

test "metadata_headers_hierarchy" {
    // Extract heading hierarchy from document into metadata
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Docs</title></head><body><h1>Introduction</h1><h2>Getting Started</h2><h3>Installation</h3><h3>Configuration</h3><h2>Advanced Usage</h2><h3>Custom Options</h3></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(result.metadata.headers.len >= 5);
}

test "metadata_keywords_meta" {
    // Extract keywords from <meta name='keywords'> tag
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Page</title><meta name=\"keywords\" content=\"rust, markdown, html, converter\"></head><body><p>Content</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(result.metadata.document.keywords.len >= 1);
}

test "metadata_lang_attribute" {
    // Extract language from html lang attribute
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html lang=\"es\"><head><title>Spanish Page</title></head><body><h1>Hola Mundo</h1><p>Este es un documento en español.</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "Hola Mundo") != null);
}

test "metadata_microdata_schema_article" {
    // Extract schema.org microdata for Article
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Article</title></head><body><article itemscope itemtype=\"https://schema.org/Article\"><h1 itemprop=\"headline\">Breaking News Today</h1><span itemprop=\"author\">Jane Reporter</span><span itemprop=\"datePublished\">2024-04-22</span><div itemprop=\"articleBody\"><p>The article content goes here with important information about the breaking news story.</p></div></article></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "Breaking News Today") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "Jane Reporter") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "important information") != null);
}

test "metadata_microdata_schema_breadcrumb" {
    // Extract schema.org breadcrumb navigation microdata
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Navigation</title></head><body><nav itemscope itemtype=\"https://schema.org/BreadcrumbList\"><span itemprop=\"itemListElement\" itemscope itemtype=\"https://schema.org/ListItem\"><a itemprop=\"item\" href=\"https://example.com\"><span itemprop=\"name\">Home</span></a></span><span itemprop=\"itemListElement\" itemscope itemtype=\"https://schema.org/ListItem\"><a itemprop=\"item\" href=\"https://example.com/products\"><span itemprop=\"name\">Products</span></a></span><span itemprop=\"itemListElement\" itemscope itemtype=\"https://schema.org/ListItem\"><span itemprop=\"name\">Current Page</span></span></nav></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "Home") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "Products") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "Current Page") != null);
}

test "metadata_microdata_schema_organization" {
    // Extract schema.org microdata for Organization
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Company</title></head><body><div itemscope itemtype=\"https://schema.org/Organization\"><span itemprop=\"name\">Acme Corp</span><span itemprop=\"foundingDate\">2020</span><span itemprop=\"url\">https://acmecorp.example.com</span><span itemprop=\"logo\">https://acmecorp.example.com/logo.png</span></div></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "Acme Corp") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "2020") != null);
}

test "metadata_microdata_schema_person" {
    // Extract schema.org microdata for Person
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Contact</title></head><body><div itemscope itemtype=\"https://schema.org/Person\"><span itemprop=\"name\">John Smith</span><span itemprop=\"email\">john@example.com</span><span itemprop=\"telephone\">+1-555-0100</span></div></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "John Smith") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "john@example.com") != null);
}

test "metadata_microdata_schema_product" {
    // Extract schema.org microdata for Product
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Product</title></head><body><div itemscope itemtype=\"https://schema.org/Product\"><h1 itemprop=\"name\">Awesome Widget</h1><span itemprop=\"description\">The best widget on the market</span><span itemprop=\"price\">29.99</span><span itemprop=\"priceCurrency\">USD</span><img itemprop=\"image\" src=\"widget.jpg\" alt=\"Widget\"><span itemprop=\"ratingValue\">4.5</span></div></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "Awesome Widget") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "best widget") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "29.99") != null);
}

test "metadata_text_direction_ltr" {
    // Extract text direction from lang attribute on html element
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html lang=\"en\" dir=\"ltr\"><head><title>LTR Document</title></head><body><p>This is left-to-right text.</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "left-to-right text") != null);
}

test "metadata_text_direction_rtl" {
    // Extract right-to-left text direction
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html lang=\"ar\" dir=\"rtl\"><head><title>RTL Document</title></head><body><p>This is right-to-left text.</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "right-to-left text") != null);
}

test "metadata_title_tag" {
    // Extract title from <title> tag
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>My Page</title></head><body><p>Content</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expectEqual("My Page", result.metadata.document.title);
}

test "og_basic_tags" {
    // Extract og:title, og:description, and og:image from Open Graph meta tags
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Fallback Title</title><meta property=\"og:title\" content=\"OG Title\"><meta property=\"og:description\" content=\"OG description text.\"><meta property=\"og:image\" content=\"https://example.com/image.jpg\"></head><body><p>Content</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expectEqual("OG Title", result.metadata.document.open_graph.get("title"));
    try testing.expectEqual("OG description text.", result.metadata.document.open_graph.get("description"));
    try testing.expectEqual("https://example.com/image.jpg", result.metadata.document.open_graph.get("image"));
}

test "og_multiple_tags" {
    // Extract multiple Open Graph tags including type, url, and site_name
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><meta property=\"og:title\" content=\"Article Title\"><meta property=\"og:type\" content=\"article\"><meta property=\"og:url\" content=\"https://example.com/article\"><meta property=\"og:site_name\" content=\"Example Site\"><meta property=\"og:description\" content=\"An interesting article.\"><meta property=\"og:image\" content=\"https://example.com/article.jpg\"></head><body><article><p>Article content here.</p></article></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expectEqual("Article Title", result.metadata.document.open_graph.get("title"));
    try testing.expectEqual("article", result.metadata.document.open_graph.get("type"));
    try testing.expectEqual("https://example.com/article", result.metadata.document.open_graph.get("url"));
    try testing.expectEqual("Example Site", result.metadata.document.open_graph.get("site_name"));
}

test "structured_data_json_ld" {
    // JSON-LD script tag is stripped from output (security) but metadata may be extracted
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Article</title><script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"Article\",\"headline\":\"My Article\",\"author\":{\"@type\":\"Person\",\"name\":\"Jane Doe\"},\"datePublished\":\"2024-01-15\"}</script></head><body><h1>My Article</h1><p>Article body text.</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "My Article") != null);
}

test "structured_data_multiple_json_ld" {
    // Multiple JSON-LD blocks are all stripped from output
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><title>Shop Page</title><script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"Product\",\"name\":\"Widget\",\"price\":\"9.99\"}</script><script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"BreadcrumbList\",\"itemListElement\":[{\"@type\":\"ListItem\",\"position\":1,\"name\":\"Home\"}]}</script></head><body><h1>Widget</h1><p>A great widget for all purposes.</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expect(std.mem.indexOf(u8, result.content, "Widget") != null);
}

test "twitter_card_tags" {
    // Extract Twitter card meta tags
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<html><head><meta name=\"twitter:card\" content=\"summary_large_image\"><meta name=\"twitter:site\" content=\"@examplesite\"><meta name=\"twitter:title\" content=\"Twitter Card Title\"><meta name=\"twitter:description\" content=\"Twitter card description.\"><meta name=\"twitter:image\" content=\"https://example.com/twitter-image.jpg\"></head><body><p>Content</p></body></html>");
    try testing.expect(result.content.len > 0);
    try testing.expectEqual("summary_large_image", result.metadata.document.twitter_card.get("card"));
    try testing.expectEqual("Twitter Card Title", result.metadata.document.twitter_card.get("title"));
    try testing.expectEqual("Twitter card description.", result.metadata.document.twitter_card.get("description"));
}
