// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith

/** E2e tests for category: smoke. */
class SmokeTest {
    @Test
    fun testSmokeEmptyString() {
        // Empty string produces empty output
        val result = HtmlToMarkdownRs.convert("")
        assertEquals("", result.content.orEmpty().trim())
    }

    @Test
    fun testSmokeSimpleHeading() {
        // H1 heading converts to ATX markdown
        val result = HtmlToMarkdownRs.convert("<h1>Title</h1>")
        assertTrue(result.content.orEmpty().contains("# Title"), "expected to contain: " + "# Title")
    }

    @Test
    fun testSmokeSimpleParagraph() {
        // Simple paragraph converts correctly
        val result = HtmlToMarkdownRs.convert("<p>Hello World</p>")
        assertEquals("Hello World", result.content.orEmpty().trim())
        assertFalse(result.content.orEmpty().isEmpty(), "expected non-empty value")
    }

}
