// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith

/** E2e tests for category: visitor. */
class VisitorTest {
    @Test
    fun testVisitorAudioCustom() {
        // Visitor replaces audio element with custom output
        val result = HtmlToMarkdownRs.convert("<p>Listen to this: <audio src=\"podcast.mp3\" controls></audio></p>")
        assertTrue(result.content.orEmpty().contains("[AUDIO: podcast.mp3]"), "expected to contain: " + "[AUDIO: podcast.mp3]")
        assertTrue(result.content.orEmpty().contains("Listen to this:"), "expected to contain: " + "Listen to this:")
    }

    @Test
    fun testVisitorAudioSkip() {
        // Visitor removes audio elements from output
        val result = HtmlToMarkdownRs.convert("<p>Background music:</p><audio src=\"music.ogg\" autoplay></audio><p>Enjoy!</p>")
        assertTrue(result.content.orEmpty().contains("Background music:"), "expected to contain: " + "Background music:")
        assertTrue(result.content.orEmpty().contains("Enjoy!"), "expected to contain: " + "Enjoy!")
        assertFalse(result.content.orEmpty().contains("music.ogg"), "expected NOT to contain: " + "music.ogg")
    }

    @Test
    fun testVisitorButtonCustom() {
        // Visitor replaces button with bracketed text
        val result = HtmlToMarkdownRs.convert("<p>Confirm action: <button type=\"submit\">Click me</button> or <button type=\"reset\">Cancel</button></p>")
        assertTrue(result.content.orEmpty().contains("[BTN:Click me]"), "expected to contain: " + "[BTN:Click me]")
        assertTrue(result.content.orEmpty().contains("[BTN:Cancel]"), "expected to contain: " + "[BTN:Cancel]")
        assertTrue(result.content.orEmpty().contains("Confirm action:"), "expected to contain: " + "Confirm action:")
    }

    @Test
    fun testVisitorButtonSkip() {
        // Visitor removes all buttons from output
        val result = HtmlToMarkdownRs.convert("<p>Actions available: <button>Save</button> <button>Delete</button> <button>Export</button></p>")
        assertTrue(result.content.orEmpty().contains("Actions available:"), "expected to contain: " + "Actions available:")
        assertFalse(result.content.orEmpty().contains("Save"), "expected NOT to contain: " + "Save")
        assertFalse(result.content.orEmpty().contains("Delete"), "expected NOT to contain: " + "Delete")
        assertFalse(result.content.orEmpty().contains("Export"), "expected NOT to contain: " + "Export")
    }

    @Test
    fun testVisitorContinueDefault() {
        // Visitor continue action preserves default conversion
        val result = HtmlToMarkdownRs.convert("<p>Hello <strong>World</strong></p>")
        assertTrue(result.content.orEmpty().contains("**World**"), "expected to contain: " + "**World**")
    }

    @Test
    fun testVisitorCustomBlockquote() {
        // Visitor replaces blockquote with custom format
        val result = HtmlToMarkdownRs.convert("<blockquote><p>A wise quote.</p></blockquote>")
        assertTrue(result.content.orEmpty().contains("QUOTE:"), "expected to contain: " + "QUOTE:")
        assertTrue(result.content.orEmpty().contains("A wise quote."), "expected to contain: " + "A wise quote.")
    }

    @Test
    fun testVisitorCustomEmphasis() {
        // Visitor replaces emphasis with custom output
        val result = HtmlToMarkdownRs.convert("<p>This is <em>important</em> text.</p>")
        assertTrue(result.content.orEmpty().contains(">>>important<<<"), "expected to contain: " + ">>>important<<<")
        assertFalse(result.content.orEmpty().contains("*important*"), "expected NOT to contain: " + "*important*")
    }

    @Test
    fun testVisitorCustomHeading() {
        // Visitor replaces heading with custom format
        val result = HtmlToMarkdownRs.convert("<h2>Section Title</h2><p>Content below heading.</p>")
        assertTrue(result.content.orEmpty().contains("--- Section Title ---"), "expected to contain: " + "--- Section Title ---")
        assertFalse(result.content.orEmpty().contains("## Section Title"), "expected NOT to contain: " + "## Section Title")
        assertTrue(result.content.orEmpty().contains("Content below heading."), "expected to contain: " + "Content below heading.")
    }

    @Test
    fun testVisitorCustomImage() {
        // Visitor replaces image with custom output using template
        val result = HtmlToMarkdownRs.convert("<img src=\"banner.png\" alt=\"Banner\">")
        assertTrue(result.content.orEmpty().contains("[Image: Banner]"), "expected to contain: " + "[Image: Banner]")
        assertFalse(result.content.orEmpty().contains("banner.png"), "expected NOT to contain: " + "banner.png")
    }

    @Test
    fun testVisitorCustomLinkFormat() {
        // Visitor reformats links using template interpolation
        val result = HtmlToMarkdownRs.convert("<p>Visit <a href=\"https://example.com\">Example</a> for more info.</p>")
        assertTrue(result.content.orEmpty().contains("Example (https://example.com)"), "expected to contain: " + "Example (https://example.com)")
        assertFalse(result.content.orEmpty().contains("[Example]"), "expected NOT to contain: " + "[Example]")
    }

    @Test
    fun testVisitorCustomLinkStatic() {
        // Visitor replaces link with static custom output
        val result = HtmlToMarkdownRs.convert("<a href=\"https://example.com\">Click here</a>")
        assertTrue(result.content.orEmpty().contains("[REDACTED LINK]"), "expected to contain: " + "[REDACTED LINK]")
        assertFalse(result.content.orEmpty().contains("example.com"), "expected NOT to contain: " + "example.com")
    }

    @Test
    fun testVisitorCustomOutput() {
        // Visitor custom action replaces element output
        val result = HtmlToMarkdownRs.convert("<h1>Original Heading</h1>")
        assertTrue(result.content.orEmpty().contains("## REPLACED HEADING"), "expected to contain: " + "## REPLACED HEADING")
        assertFalse(result.content.orEmpty().contains("# Original Heading"), "expected NOT to contain: " + "# Original Heading")
    }

    @Test
    fun testVisitorDefinitionListCustom() {
        // Visitor customizes definition list items
        val result = HtmlToMarkdownRs.convert("<dl><dt>HTML</dt><dd>HyperText Markup Language</dd><dt>CSS</dt><dd>Cascading Style Sheets</dd></dl>")
        assertTrue(result.content.orEmpty().contains("**HTML**"), "expected to contain: " + "**HTML**")
        assertTrue(result.content.orEmpty().contains("**CSS**"), "expected to contain: " + "**CSS**")
        assertTrue(result.content.orEmpty().contains("HyperText Markup Language"), "expected to contain: " + "HyperText Markup Language")
    }

    @Test
    fun testVisitorDefinitionListCustomFormat() {
        // Visitor formats definition lists with custom templates
        val result = HtmlToMarkdownRs.convert("<dl><dt>Python</dt><dd>A high-level programming language</dd><dt>JavaScript</dt><dd>A scripting language for web browsers</dd></dl>")
        assertTrue(result.content.orEmpty().contains("### Python"), "expected to contain: " + "### Python")
        assertTrue(result.content.orEmpty().contains("### JavaScript"), "expected to contain: " + "### JavaScript")
        assertTrue(result.content.orEmpty().contains("> A high-level programming language"), "expected to contain: " + "> A high-level programming language")
        assertTrue(result.content.orEmpty().contains("> A scripting language for web browsers"), "expected to contain: " + "> A scripting language for web browsers")
    }

    @Test
    fun testVisitorDefinitionListSkip() {
        // Visitor skips definition list items from output
        val result = HtmlToMarkdownRs.convert("<p>Glossary:</p><dl><dt>Term A</dt><dd>Definition of term A</dd><dt>Term B</dt><dd>Definition of term B</dd></dl><p>End of glossary</p>")
        assertTrue(result.content.orEmpty().contains("Glossary:"), "expected to contain: " + "Glossary:")
        assertTrue(result.content.orEmpty().contains("End of glossary"), "expected to contain: " + "End of glossary")
        assertFalse(result.content.orEmpty().contains("Term A"), "expected NOT to contain: " + "Term A")
        assertFalse(result.content.orEmpty().contains("Definition"), "expected NOT to contain: " + "Definition")
    }

    @Test
    fun testVisitorDetailsSummaryCustom() {
        // Visitor customizes details/summary disclosure elements
        val result = HtmlToMarkdownRs.convert("<details><summary>Click to expand</summary><p>This content is initially hidden.</p><p>But can be revealed by the user.</p></details>")
        assertTrue(result.content.orEmpty().contains("[EXPANDABLE] Click to expand"), "expected to contain: " + "[EXPANDABLE] Click to expand")
        assertTrue(result.content.orEmpty().contains("This content is initially hidden."), "expected to contain: " + "This content is initially hidden.")
    }

    @Test
    fun testVisitorDetailsSummarySkip() {
        // Visitor removes details/summary elements entirely
        val result = HtmlToMarkdownRs.convert("<p>Main content here.</p><details><summary>Hidden section</summary><p>Secret details</p></details><p>More main content.</p>")
        assertTrue(result.content.orEmpty().contains("Main content here."), "expected to contain: " + "Main content here.")
        assertTrue(result.content.orEmpty().contains("More main content."), "expected to contain: " + "More main content.")
        assertFalse(result.content.orEmpty().contains("Hidden section"), "expected NOT to contain: " + "Hidden section")
        assertFalse(result.content.orEmpty().contains("Secret details"), "expected NOT to contain: " + "Secret details")
    }

    @Test
    fun testVisitorFigureCustom() {
        // Visitor customizes figure and figcaption elements
        val result = HtmlToMarkdownRs.convert("<article><h1>Article Title</h1><p>Introduction paragraph.</p><figure><img src=\"diagram.png\" alt=\"System architecture diagram\"><figcaption>Figure 1: System Architecture</figcaption></figure><p>Explanation of the figure.</p></article>")
        assertTrue(result.content.orEmpty().contains("Article Title"), "expected to contain: " + "Article Title")
        assertTrue(result.content.orEmpty().contains("*Figure 1: System Architecture*"), "expected to contain: " + "*Figure 1: System Architecture*")
        assertTrue(result.content.orEmpty().contains("Explanation of the figure."), "expected to contain: " + "Explanation of the figure.")
    }

    @Test
    fun testVisitorFigureCustomWrap() {
        // Visitor wraps figure content with custom formatting
        val result = HtmlToMarkdownRs.convert("<section><h2>Gallery</h2><figure><img src=\"photo1.jpg\" alt=\"Photo\"><figcaption>Beautiful sunset</figcaption></figure></section>")
        assertTrue(result.content.orEmpty().contains("[FIGURE]"), "expected to contain: " + "[FIGURE]")
        assertTrue(result.content.orEmpty().contains("[/FIGURE]"), "expected to contain: " + "[/FIGURE]")
        assertTrue(result.content.orEmpty().contains("Gallery"), "expected to contain: " + "Gallery")
    }

    @Test
    fun testVisitorFigureSkip() {
        // Visitor removes figure elements with their captions
        val result = HtmlToMarkdownRs.convert("<p>See the chart below:</p><figure><img src=\"chart.svg\"><figcaption>Revenue Trends 2020-2024</figcaption></figure><p>As shown in the chart above.</p>")
        assertTrue(result.content.orEmpty().contains("See the chart below:"), "expected to contain: " + "See the chart below:")
        assertTrue(result.content.orEmpty().contains("As shown in the chart above."), "expected to contain: " + "As shown in the chart above.")
        assertFalse(result.content.orEmpty().contains("Revenue Trends"), "expected NOT to contain: " + "Revenue Trends")
        assertFalse(result.content.orEmpty().contains("chart.svg"), "expected NOT to contain: " + "chart.svg")
    }

    @Test
    fun testVisitorFormCustom() {
        // Visitor replaces form with custom output
        val result = HtmlToMarkdownRs.convert("<div><form action=\"/submit\" method=\"POST\"><label>Name: <input type=\"text\" name=\"name\"></label><button type=\"submit\">Submit</button></form></div>")
        assertTrue(result.content.orEmpty().contains("[FORM PLACEHOLDER]"), "expected to contain: " + "[FORM PLACEHOLDER]")
        assertFalse(result.content.orEmpty().contains("submit"), "expected NOT to contain: " + "submit")
        assertFalse(result.content.orEmpty().contains("input"), "expected NOT to contain: " + "input")
    }

    @Test
    fun testVisitorFormSkip() {
        // Visitor skips form elements entirely
        val result = HtmlToMarkdownRs.convert("<p>Before form</p><form><input type=\"email\" name=\"email\"></form><p>After form</p>")
        assertTrue(result.content.orEmpty().contains("Before form"), "expected to contain: " + "Before form")
        assertTrue(result.content.orEmpty().contains("After form"), "expected to contain: " + "After form")
        assertFalse(result.content.orEmpty().contains("email"), "expected NOT to contain: " + "email")
    }

    @Test
    fun testVisitorHorizontalRuleCustom() {
        // Visitor replaces horizontal rule with custom output
        val result = HtmlToMarkdownRs.convert("<h1>Section A</h1><p>Content A</p><hr><h1>Section B</h1><p>Content B</p>")
        assertTrue(result.content.orEmpty().contains("[DIVIDER]"), "expected to contain: " + "[DIVIDER]")
        assertTrue(result.content.orEmpty().contains("Section A"), "expected to contain: " + "Section A")
        assertTrue(result.content.orEmpty().contains("Section B"), "expected to contain: " + "Section B")
        assertFalse(result.content.orEmpty().contains("---"), "expected NOT to contain: " + "---")
    }

    @Test
    fun testVisitorHorizontalRuleSkip() {
        // Visitor removes all horizontal rules
        val result = HtmlToMarkdownRs.convert("<p>Part 1</p><hr><p>Part 2</p><hr><p>Part 3</p>")
        assertTrue(result.content.orEmpty().contains("Part 1"), "expected to contain: " + "Part 1")
        assertTrue(result.content.orEmpty().contains("Part 2"), "expected to contain: " + "Part 2")
        assertTrue(result.content.orEmpty().contains("Part 3"), "expected to contain: " + "Part 3")
        assertFalse(result.content.orEmpty().contains("---"), "expected NOT to contain: " + "---")
    }

    @Test
    fun testVisitorIframeCustom() {
        // Visitor replaces embedded iframe with custom text
        val result = HtmlToMarkdownRs.convert("<p>Embedded map:</p><iframe src=\"https://maps.example.com/embed\" width=\"400\" height=\"300\"></iframe><p>End of map</p>")
        assertTrue(result.content.orEmpty().contains("[EMBEDDED: https://maps.example.com/embed]"), "expected to contain: " + "[EMBEDDED: https://maps.example.com/embed]")
        assertTrue(result.content.orEmpty().contains("Embedded map:"), "expected to contain: " + "Embedded map:")
        assertTrue(result.content.orEmpty().contains("End of map"), "expected to contain: " + "End of map")
    }

    @Test
    fun testVisitorIframeSkip() {
        // Visitor removes embedded iframes
        val result = HtmlToMarkdownRs.convert("<h3>Reviews</h3><iframe src=\"https://widget.example.com/reviews\"></iframe><p>See reviews from our partners.</p>")
        assertTrue(result.content.orEmpty().contains("Reviews"), "expected to contain: " + "Reviews")
        assertTrue(result.content.orEmpty().contains("See reviews from our partners."), "expected to contain: " + "See reviews from our partners.")
        assertFalse(result.content.orEmpty().contains("widget.example.com"), "expected NOT to contain: " + "widget.example.com")
    }

    @Test
    fun testVisitorInputCustom() {
        // Visitor replaces input with labeled output
        val result = HtmlToMarkdownRs.convert("<form><label>Username: <input type=\"text\" name=\"username\" value=\"\"></label><label>Password: <input type=\"password\" name=\"password\"></label></form>")
        assertTrue(result.content.orEmpty().contains("[INPUT:text]"), "expected to contain: " + "[INPUT:text]")
        assertTrue(result.content.orEmpty().contains("[INPUT:password]"), "expected to contain: " + "[INPUT:password]")
    }

    @Test
    fun testVisitorInputSkip() {
        // Visitor skips all input elements
        val result = HtmlToMarkdownRs.convert("<p>Sign up:</p><input type=\"text\" name=\"email\" placeholder=\"your@email.com\"><input type=\"checkbox\" name=\"agree\"><p>Continue</p>")
        assertTrue(result.content.orEmpty().contains("Sign up:"), "expected to contain: " + "Sign up:")
        assertTrue(result.content.orEmpty().contains("Continue"), "expected to contain: " + "Continue")
        assertFalse(result.content.orEmpty().contains("email"), "expected NOT to contain: " + "email")
    }

    @Test
    fun testVisitorLineBreakCustom() {
        // Visitor replaces line break with custom output
        val result = HtmlToMarkdownRs.convert("<p>First line<br>Second line<br>Third line</p>")
        assertTrue(result.content.orEmpty().contains("First line | Second line | Third line"), "expected to contain: " + "First line | Second line | Third line")
        assertFalse(result.content.orEmpty().contains("\n\n"), "expected NOT to contain: " + "\n\n")
    }

    @Test
    fun testVisitorLineBreakSkip() {
        // Visitor removes all line breaks
        val result = HtmlToMarkdownRs.convert("<p>Address Line 1<br>Address Line 2<br>Address Line 3</p>")
        assertTrue(result.content.orEmpty().contains("Address Line 1Address Line 2Address Line 3"), "expected to contain: " + "Address Line 1Address Line 2Address Line 3")
    }

    @Test
    fun testVisitorMarkCustom() {
        // Visitor replaces highlight/mark with custom template
        val result = HtmlToMarkdownRs.convert("<p>This is a <mark>highlighted passage</mark> in the text.</p>")
        assertTrue(result.content.orEmpty().contains("==highlighted passage=="), "expected to contain: " + "==highlighted passage==")
        assertTrue(result.content.orEmpty().contains("This is a"), "expected to contain: " + "This is a")
    }

    @Test
    fun testVisitorMarkSkip() {
        // Visitor skips mark elements entirely
        val result = HtmlToMarkdownRs.convert("<p>Key insight: <mark>always validate input</mark> for security.</p>")
        assertFalse(result.content.orEmpty().contains("always validate input"), "expected NOT to contain: " + "always validate input")
        assertTrue(result.content.orEmpty().contains("Key insight:"), "expected to contain: " + "Key insight:")
        assertTrue(result.content.orEmpty().contains("for security."), "expected to contain: " + "for security.")
    }

    @Test
    fun testVisitorPreserveHtml() {
        // Visitor preserve_html action includes raw HTML in output
        val result = HtmlToMarkdownRs.convert("<div><custom-tag>Custom content</custom-tag></div>")
        assertTrue(result.content.orEmpty().contains("<custom-tag>"), "expected to contain: " + "<custom-tag>")
    }

    @Test
    fun testVisitorSkipAllHeadings() {
        // Visitor skips all headings from document
        val result = HtmlToMarkdownRs.convert("<h1>Title</h1><p>Body text remains.</p>")
        assertFalse(result.content.orEmpty().contains("Title"), "expected NOT to contain: " + "Title")
        assertTrue(result.content.orEmpty().contains("Body text remains."), "expected to contain: " + "Body text remains.")
    }

    @Test
    fun testVisitorSkipCodeBlocks() {
        // Visitor skips code blocks from output
        val result = HtmlToMarkdownRs.convert("<p>Intro text</p><pre><code>let x = 42;</code></pre><p>Outro text</p>")
        assertTrue(result.content.orEmpty().contains("Intro text"), "expected to contain: " + "Intro text")
        assertTrue(result.content.orEmpty().contains("Outro text"), "expected to contain: " + "Outro text")
        assertFalse(result.content.orEmpty().contains("let x = 42"), "expected NOT to contain: " + "let x = 42")
    }

    @Test
    fun testVisitorSkipHeading() {
        // Visitor skip action omits all headings from output
        val result = HtmlToMarkdownRs.convert("<h1>Title</h1><p>Body text remains.</p>")
        assertFalse(result.content.orEmpty().contains("Title"), "expected NOT to contain: " + "Title")
        assertTrue(result.content.orEmpty().contains("Body text remains."), "expected to contain: " + "Body text remains.")
    }

    @Test
    fun testVisitorSkipImages() {
        // Visitor skips all images from output
        val result = HtmlToMarkdownRs.convert("<p>Before image</p><img src=\"photo.jpg\" alt=\"A photo\"><p>After image</p>")
        assertTrue(result.content.orEmpty().contains("Before image"), "expected to contain: " + "Before image")
        assertTrue(result.content.orEmpty().contains("After image"), "expected to contain: " + "After image")
        assertFalse(result.content.orEmpty().contains("photo.jpg"), "expected NOT to contain: " + "photo.jpg")
        assertFalse(result.content.orEmpty().contains("A photo"), "expected NOT to contain: " + "A photo")
    }

    @Test
    fun testVisitorSkipLinks() {
        // Visitor skips all links entirely
        val result = HtmlToMarkdownRs.convert("<p>Before <a href=\"https://example.com\">link text</a> after</p>")
        assertFalse(result.content.orEmpty().contains("link text"), "expected NOT to contain: " + "link text")
        assertFalse(result.content.orEmpty().contains("example.com"), "expected NOT to contain: " + "example.com")
    }

    @Test
    fun testVisitorSkipStrong() {
        // Visitor skips bold/strong elements
        val result = HtmlToMarkdownRs.convert("<p>Normal <strong>bold text</strong> normal</p>")
        assertFalse(result.content.orEmpty().contains("bold text"), "expected NOT to contain: " + "bold text")
        assertTrue(result.content.orEmpty().contains("Normal"), "expected to contain: " + "Normal")
    }

    @Test
    fun testVisitorSubscriptCustom() {
        // Visitor replaces subscript with custom template
        val result = HtmlToMarkdownRs.convert("<p>H<sub>2</sub>O is water.</p>")
        assertTrue(result.content.orEmpty().contains("H~2~O"), "expected to contain: " + "H~2~O")
        assertTrue(result.content.orEmpty().contains("is water"), "expected to contain: " + "is water")
    }

    @Test
    fun testVisitorSubscriptSkip() {
        // Visitor skips subscript elements entirely
        val result = HtmlToMarkdownRs.convert("<p>The formula C<sub>12</sub>H<sub>22</sub>O<sub>11</sub> is sugar.</p>")
        assertTrue(result.content.orEmpty().contains("The formula CHO is sugar."), "expected to contain: " + "The formula CHO is sugar.")
    }

    @Test
    fun testVisitorSuperscriptCustom() {
        // Visitor replaces superscript with custom template
        val result = HtmlToMarkdownRs.convert("<p>Einstein's E=mc<sup>2</sup> revolutionized physics.</p>")
        assertTrue(result.content.orEmpty().contains("E=mc^2^"), "expected to contain: " + "E=mc^2^")
        assertTrue(result.content.orEmpty().contains("revolutionized physics"), "expected to contain: " + "revolutionized physics")
    }

    @Test
    fun testVisitorSuperscriptSkip() {
        // Visitor skips superscript from output
        val result = HtmlToMarkdownRs.convert("<p>The equation x<sup>3</sup> + y<sup>3</sup> = z<sup>3</sup> has no solutions.</p>")
        assertTrue(result.content.orEmpty().contains("The equation x + y = z has no solutions."), "expected to contain: " + "The equation x + y = z has no solutions.")
    }

    @Test
    fun testVisitorUnderlineCustom() {
        // Visitor replaces underline with custom markup
        val result = HtmlToMarkdownRs.convert("<p>This is <u>very important</u> text.</p>")
        assertTrue(result.content.orEmpty().contains("_very important_"), "expected to contain: " + "_very important_")
        assertFalse(result.content.orEmpty().contains("**"), "expected NOT to contain: " + "**")
    }

    @Test
    fun testVisitorUnderlineSkip() {
        // Visitor skips underline elements from output
        val result = HtmlToMarkdownRs.convert("<p>Normal text with <u>underlined part</u> and more text.</p>")
        assertTrue(result.content.orEmpty().contains("Normal text with"), "expected to contain: " + "Normal text with")
        assertTrue(result.content.orEmpty().contains("and more text."), "expected to contain: " + "and more text.")
        assertFalse(result.content.orEmpty().contains("underlined part"), "expected NOT to contain: " + "underlined part")
    }

    @Test
    fun testVisitorVideoCustom() {
        // Visitor replaces video with custom link
        val result = HtmlToMarkdownRs.convert("<p>Watch our tutorial:</p><video src=\"tutorial.mp4\" width=\"320\" height=\"240\" controls></video><p>Great content!</p>")
        assertTrue(result.content.orEmpty().contains("[VIDEO: tutorial.mp4]"), "expected to contain: " + "[VIDEO: tutorial.mp4]")
        assertTrue(result.content.orEmpty().contains("Watch our tutorial:"), "expected to contain: " + "Watch our tutorial:")
        assertTrue(result.content.orEmpty().contains("Great content!"), "expected to contain: " + "Great content!")
    }

    @Test
    fun testVisitorVideoSkip() {
        // Visitor removes video elements entirely
        val result = HtmlToMarkdownRs.convert("<h2>Demo</h2><video src=\"demo.webm\"></video><p>See the demo above.</p>")
        assertTrue(result.content.orEmpty().contains("Demo"), "expected to contain: " + "Demo")
        assertTrue(result.content.orEmpty().contains("See the demo above."), "expected to contain: " + "See the demo above.")
        assertFalse(result.content.orEmpty().contains("demo.webm"), "expected NOT to contain: " + "demo.webm")
    }

}
