# This file is auto-generated by alef. DO NOT EDIT.
"""E2e tests for category: options."""

from html_to_markdown import ConversionOptions, convert
from html_to_markdown.options import CodeBlockStyle, HeadingStyle, ListIndentType, OutputFormat, WhitespaceMode


def test_options_code_block_backticks() -> None:
    """Backticks code block style uses triple backtick fences."""
    html = "<pre><code class=\"language-js\">console.log('hi');</code></pre>"
    options = ConversionOptions(code_block_style=CodeBlockStyle.BACKTICKS)
    result = convert(html=html, options=options)
    assert result.content is not None
    assert "```" in result.content
    assert result.content is not None
    assert "console.log('hi');" in result.content


def test_options_code_block_tildes() -> None:
    """Tildes code block style uses triple tilde fences."""
    html = "<pre><code>some code</code></pre>"
    options = ConversionOptions(code_block_style=CodeBlockStyle.TILDES)
    result = convert(html=html, options=options)
    assert result.content is not None
    assert "~~~" in result.content
    assert result.content is not None
    assert "some code" in result.content


def test_options_escape_asterisks() -> None:
    """escape_asterisks option escapes asterisks in plain text."""
    html = "<p>Use 2*3 = 6 in math.</p>"
    options = ConversionOptions(escape_asterisks=True)
    result = convert(html=html, options=options)
    assert result.content
    assert result.content is not None
    assert "2" in result.content
    assert result.content is not None
    assert "3" in result.content
    assert result.content is not None
    assert "6" in result.content


def test_options_escape_misc() -> None:
    """escape_misc option escapes miscellaneous markdown characters."""
    html = "<p>Use # and | and ~ in text.</p>"
    options = ConversionOptions(escape_misc=True)
    result = convert(html=html, options=options)
    assert result.content
    assert result.content is not None
    assert "Use" in result.content
    assert result.content is not None
    assert "and" in result.content
    assert result.content is not None
    assert "in text." in result.content


def test_options_escape_underscores() -> None:
    """escape_underscores option escapes underscores in plain text."""
    html = "<p>The variable_name is defined.</p>"
    options = ConversionOptions(escape_underscores=True)
    result = convert(html=html, options=options)
    assert result.content
    assert result.content is not None
    assert "variable" in result.content
    assert result.content is not None
    assert "name" in result.content
    assert result.content is not None
    assert "defined." in result.content


def test_options_heading_style_atx() -> None:
    """ATX heading style produces hash-prefixed headings."""
    html = "<h1>Title</h1><h2>Subtitle</h2>"
    options = ConversionOptions(heading_style=HeadingStyle.ATX)
    result = convert(html=html, options=options)
    assert result.content is not None
    assert "# Title" in result.content
    assert result.content is not None
    assert "## Subtitle" in result.content


def test_options_heading_style_atx_closed() -> None:
    """ATX closed heading style adds closing hashes."""
    html = "<h1>Closed Heading</h1>"
    options = ConversionOptions(heading_style=HeadingStyle.ATX_CLOSED)
    result = convert(html=html, options=options)
    assert result.content is not None
    assert "# Closed Heading #" in result.content


def test_options_heading_style_underlined() -> None:
    """Underlined heading style produces setext-style headings for h1 and h2."""
    html = "<h1>Main Title</h1>"
    options = ConversionOptions(heading_style=HeadingStyle.UNDERLINED)
    result = convert(html=html, options=options)
    assert result.content
    assert result.content is not None
    assert "Main Title" in result.content


def test_options_list_custom_bullets() -> None:
    """Custom bullet character for unordered lists."""
    html = "<ul><li>Item A</li><li>Item B</li></ul>"
    options = ConversionOptions(bullets="*")
    result = convert(html=html, options=options)
    assert result.content is not None
    assert "* Item A" in result.content
    assert result.content is not None
    assert "* Item B" in result.content


def test_options_list_indent_tabs() -> None:
    """Tab indentation type for nested list items."""
    html = "<ul><li>Parent<ul><li>Child</li></ul></li></ul>"
    options = ConversionOptions(list_indent_type=ListIndentType.TABS)
    result = convert(html=html, options=options)
    assert result.content
    assert result.content is not None
    assert "Parent" in result.content
    assert result.content is not None
    assert "Child" in result.content


def test_options_max_depth_default_unlimited() -> None:
    """Default max_depth (null) converts deeply nested content fully."""
    html = "<div><div><div><div><p>Deep content</p></div></div></div></div>"
    result = convert(html=html)
    assert result.content is not None
    assert "Deep content" in result.content


def test_options_max_depth_truncates() -> None:
    """max_depth truncates content beyond the specified depth."""
    html = "<div><p>Shallow</p><div><div><div><p>Too deep</p></div></div></div></div>"
    options = ConversionOptions(max_depth=3)
    result = convert(html=html, options=options)
    assert result.content is not None
    assert "Shallow" in result.content
    assert result.content is None or "Too deep" not in result.content


def test_options_max_depth_zero_empty() -> None:
    """max_depth of 0 produces empty output."""
    html = "<p>Hello</p>"
    options = ConversionOptions(max_depth=0)
    result = convert(html=html, options=options)
    assert result.content.strip() == ""


def test_options_output_format_djot() -> None:
    """Djot output format produces djot-compatible markup."""
    html = "<p>Simple paragraph.</p>"
    options = ConversionOptions(output_format=OutputFormat.DJOT)
    result = convert(html=html, options=options)
    assert result.content
    assert result.content is not None
    assert "Simple paragraph." in result.content


def test_options_output_format_markdown() -> None:
    """Default markdown output format produces standard markdown."""
    html = "<h1>Title</h1><p>Some text.</p>"
    options = ConversionOptions(heading_style=HeadingStyle.ATX, output_format=OutputFormat.MARKDOWN)
    result = convert(html=html, options=options)
    assert result.content is not None
    assert "# Title" in result.content
    assert result.content is not None
    assert "Some text." in result.content


def test_options_output_format_plain() -> None:
    """Plain text output format strips markdown syntax."""
    html = "<h1>Title</h1><p>Some <strong>bold</strong> text.</p>"
    options = ConversionOptions(output_format=OutputFormat.PLAIN)
    result = convert(html=html, options=options)
    assert result.content is not None
    assert "Title" in result.content
    assert result.content is not None
    assert "bold" in result.content
    assert result.content is not None
    assert "text." in result.content


def test_options_whitespace_normalized() -> None:
    """Normalized whitespace mode collapses multiple spaces."""
    html = "<p>Text   with    extra   spaces.</p>"
    options = ConversionOptions(whitespace_mode=WhitespaceMode.NORMALIZED)
    result = convert(html=html, options=options)
    assert result.content
    assert result.content is not None
    assert "Text" in result.content
    assert result.content is not None
    assert "with" in result.content
    assert result.content is not None
    assert "extra" in result.content
    assert result.content is not None
    assert "spaces." in result.content


def test_options_whitespace_strict() -> None:
    """Strict whitespace mode preserves whitespace as-is."""
    html = "<p>Preserved   spacing.</p>"
    options = ConversionOptions(whitespace_mode=WhitespaceMode.STRICT)
    result = convert(html=html, options=options)
    assert result.content
    assert result.content is not None
    assert "Preserved" in result.content
    assert result.content is not None
    assert "spacing." in result.content


def test_options_wrap_disabled() -> None:
    """Wrap option disabled preserves long lines without breaking."""
    html = "<p>This is a long paragraph that should not be wrapped at all because wrapping is disabled.</p>"
    options = ConversionOptions(wrap=False)
    result = convert(html=html, options=options)
    assert result.content is not None
    assert "This is a long paragraph that should not be wrapped at all because wrapping is disabled." in result.content


def test_options_wrap_enabled() -> None:
    """Wrap option enabled with custom width wraps long lines."""
    html = "<p>This is a long paragraph that should be wrapped at the specified column width when the wrap option is enabled.</p>"
    options = ConversionOptions(wrap=True, wrap_width=40)
    result = convert(html=html, options=options)
    assert result.content
    assert result.content is not None
    assert "This is a long paragraph" in result.content
