# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c312dc3db9bf85e03750133dd51b1f654f809599941eb0372f7fce9a852d5c2c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.DocumentMetadata do
  @moduledoc "Document-level metadata extracted from `<head>` and top-level elements."

  defstruct title: "",
            description: "",
            keywords: [],
            author: "",
            canonical_url: "",
            base_href: "",
            language: "",
            text_direction: :left_to_right,
            open_graph: %{},
            twitter_card: %{},
            meta_tags: %{}
end
