# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cb206b09d15d194d8ee3c01032c5423d2a7b561c78f96d525272c68d38c9fbaa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.GridCell do
  @moduledoc "A single cell in a table grid."

  defstruct content: "",
            row: 0,
            col: 0,
            row_span: 0,
            col_span: 0,
            is_header: false
end
