# This file is auto-generated by alef. DO NOT EDIT.
defmodule HtmlToMarkdown.HeadingStyle do
  @moduledoc "Heading style options for Markdown output."

  @type t :: :underlined | :atx | :atx_closed

  @underlined :underlined
  @atx :atx
  @atx_closed :atx_closed

  @spec underlined() :: t()
  def underlined, do: @underlined
  @spec atx() :: t()
  def atx, do: @atx
  @spec atx_closed() :: t()
  def atx_closed, do: @atx_closed
end
