# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.HighlightStyle do
  @moduledoc "Highlight rendering style for `<mark>` elements."

  @type t :: :double_equal | :html | :bold | :none

  @double_equal :double_equal
  @html :html
  @bold :bold
  @none :none

  @spec double_equal() :: t()
  def double_equal, do: @double_equal
  @spec html() :: t()
  def html, do: @html
  @spec bold() :: t()
  def bold, do: @bold
  @spec none() :: t()
  def none, do: @none
end
