# This file is auto-generated by alef. DO NOT EDIT.
defmodule HtmlToMarkdown.HighlightStyle do
  @moduledoc "Highlight rendering style for `<mark>` elements."

  @type t :: :double_equal | :html | :bold | :none

  @double_equal :double_equal
  @html :html
  @bold :bold
  @none :none

  @spec double_equal() :: t()
  def double_equal, do: @double_equal
  @spec html() :: t()
  def html, do: @html
  @spec bold() :: t()
  def bold, do: @bold
  @spec none() :: t()
  def none, do: @none
end
