# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e2ce20dc0937a83fc9ed49bf1c44c52ba14c84fe99c53dd8a6d81210699b977c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.HighlightStyle do
  @moduledoc "Highlight rendering style for `<mark>` elements."

  @type t :: :double_equal | :html | :bold | :none

  @double_equal :double_equal
  @html :html
  @bold :bold
  @none :none

  @spec double_equal() :: t()
  def double_equal, do: @double_equal
  @spec html() :: t()
  def html, do: @html
  @spec bold() :: t()
  def bold, do: @bold
  @spec none() :: t()
  def none, do: @none
end
