# This file is auto-generated by alef. DO NOT EDIT.
defmodule HtmlToMarkdown.InlineImageConfig do
  @moduledoc "Inline image configuration that specifies contexts where images remain as markdown links."

  defstruct keep_inline_images_in: []
end
