# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:206e135fcaec4207ed7138482ad1a2399e3bd81462a15f358dc5df53beb8a508
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.LinkMetadata do
  @moduledoc "Hyperlink metadata with categorization and attributes."

  defstruct href: "",
            text: "",
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: %{}
end
