# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e11de7f1f16e4b5d6500f39d02d8180f1bc82e2464d49fe0b3d8ddc6a2cf4d2f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.NewlineStyle do
  @moduledoc "Line break syntax in Markdown output."

  @type t :: :spaces | :backslash

  @spaces :spaces
  @backslash :backslash

  @spec spaces() :: t()
  def spaces, do: @spaces
  @spec backslash() :: t()
  def backslash, do: @backslash
end
