# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.NewlineStyle do
  @moduledoc "Line break syntax in Markdown output."

  @type t :: :spaces | :backslash

  @spaces :spaces
  @backslash :backslash

  @spec spaces() :: t()
  def spaces, do: @spaces
  @spec backslash() :: t()
  def backslash, do: @backslash
end
