# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e13e4c0afe392113a7b0233a49c48e131012e6205e017617962906efed6bf046
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.NodeContext do
  @moduledoc "Context information passed to all visitor methods."

  defstruct node_type: :text,
            tag_name: "",
            attributes: %{},
            depth: 0,
            index_in_parent: 0,
            parent_tag: nil,
            is_inline: false
end
