# This file is auto-generated by alef. DO NOT EDIT.
defmodule HtmlToMarkdown.OutputFormat do
  @moduledoc "Output format for conversion."

  @type t :: :markdown | :djot | :plain

  @markdown :markdown
  @djot :djot
  @plain :plain

  @spec markdown() :: t()
  def markdown, do: @markdown
  @spec djot() :: t()
  def djot, do: @djot
  @spec plain() :: t()
  def plain, do: @plain
end
