# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a00cac70dbc57ec3aa2ad256348cf2e7b9e5e246c156245916a6e698e429d350
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.OutputFormat do
  @moduledoc "Output format for conversion."

  @type t :: :markdown | :djot | :plain

  @markdown :markdown
  @djot :djot
  @plain :plain

  @spec markdown() :: t()
  def markdown, do: @markdown
  @spec djot() :: t()
  def djot, do: @djot
  @spec plain() :: t()
  def plain, do: @plain
end
