# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.ProcessingWarning do
  @moduledoc "A non-fatal warning generated during HTML processing."

  defstruct message: "",
            kind: :image_extraction_failed
end
