# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:de038220f057ad71eaabbafdbcb3b25ab7a3ba5b16e566bcb5d1b5b61c5ea80f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.StructuredData do
  @moduledoc "Structured data block (JSON-LD, Microdata, or RDFa)."

  defstruct data_type: :json_ld,
            raw_json: "",
            schema_type: nil
end
