# This file is auto-generated by alef. DO NOT EDIT.

#' @useDynLib htmltomarkdown, .registration = TRUE
NULL

#' Convert HTML to Markdown, returning a [`ConversionResult`] with content, metadata, images,
#' @export
convert <- function(html, options = NULL, visitor = NULL) {
  .Call("htm_convert", html, options, visitor)
}
