// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4ad7e9c29bcb18477c004b98e06f89331ed519b5627c22fa6369b96a7bbce556
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// Code block fence style in Markdown output.
///
/// Determines how code blocks (`<pre><code>`) are rendered in Markdown.
/// </summary>
public enum CodeBlockStyle
{
    /// <summary>
    /// Indented code blocks (4 spaces). `CommonMark` standard.
    /// </summary>
    [JsonPropertyName("indented")]
    Indented,
    /// <summary>
    /// Fenced code blocks with backticks (```). Default (GFM). Supports language hints.
    /// </summary>
    [JsonPropertyName("backticks")]
    Backticks,
    /// <summary>
    /// Fenced code blocks with tildes (~~~). Supports language hints.
    /// </summary>
    [JsonPropertyName("tildes")]
    Tildes,
}
