// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:496f61518d219efffd18a4da94b3c1b828d61967aa04f97c67f24b7540eb236e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;

namespace HtmlToMarkdown;

public class HtmlToMarkdownRsException : Exception
{
    public int Code { get; }

    public HtmlToMarkdownRsException(int code, string message) : base(message)
    {
        Code = code;
    }
}
