// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4f79bff47244d383878f59a88286a5e4957462447657da5353f1ac9834472eb0
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// I/O error
/// </summary>
public class IoErrorException : ConversionErrorException
{
    public IoErrorException(string message) : base(message) { }

    public IoErrorException(string message, Exception innerException) : base(message, innerException) { }
}
