// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:307cb65ab53ef7407f5c171606980b19c1f18b3df734296b23af0d6f305990a4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// Link classification based on href value and document context.
///
/// Used to categorize links during extraction for filtering and analysis.
/// </summary>
public enum LinkType
{
    /// <summary>
    /// Anchor link within same document (href starts with #)
    /// </summary>
    [JsonPropertyName("anchor")]
    Anchor,
    /// <summary>
    /// Internal link within same domain
    /// </summary>
    [JsonPropertyName("internal")]
    Internal,
    /// <summary>
    /// External link to different domain
    /// </summary>
    [JsonPropertyName("external")]
    External,
    /// <summary>
    /// Email link (mailto:)
    /// </summary>
    [JsonPropertyName("email")]
    Email,
    /// <summary>
    /// Phone link (tel:)
    /// </summary>
    [JsonPropertyName("phone")]
    Phone,
    /// <summary>
    /// Other protocol or unclassifiable
    /// </summary>
    [JsonPropertyName("other")]
    Other,
}
