// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f14e58046fe04080ecc47544b7c23c943794730133fb8fac751f7db28df0cf57
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// Output format for conversion.
///
/// Specifies the target markup language format for the conversion output.
/// </summary>
public enum OutputFormat
{
    /// <summary>
    /// Standard Markdown (CommonMark compatible). Default.
    /// </summary>
    [JsonPropertyName("markdown")]
    Markdown,
    /// <summary>
    /// Djot lightweight markup language.
    /// </summary>
    [JsonPropertyName("djot")]
    Djot,
    /// <summary>
    /// Plain text output (no markup, visible text only).
    /// </summary>
    [JsonPropertyName("plain")]
    Plain,
}
