// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:698a5670370422a74c297ad9a813399e69d977368bf224aceb690626960de9e9
using System;

namespace HtmlToMarkdown;

/// <summary>
/// Panic caught during conversion to prevent unwinding across FFI boundaries
/// </summary>
public class PanicException : ConversionErrorException
{
    public PanicException(string message) : base(message) { }

    public PanicException(string message, Exception innerException) : base(message, innerException) { }
}
