// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b7e1c74b4ca907c564ecd57a015a1f2600036ca425800b645234168f4e38e031
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML parsing error
/// </summary>
public class ParseErrorException : ConversionErrorException
{
    public ParseErrorException(string message) : base(message) { }

    public ParseErrorException(string message, Exception innerException) : base(message, innerException) { }
}
