// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:50108c5603150a61cdd9f989369c4038891ea2d888f71cb5098a81e4e964c789
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// HTML preprocessing aggressiveness level.
///
/// Controls the extent of cleanup performed before conversion. Higher levels remove more elements.
/// </summary>
public enum PreprocessingPreset
{
    /// <summary>
    /// Minimal cleanup. Remove only essential noise (scripts, styles).
    /// </summary>
    [JsonPropertyName("minimal")]
    Minimal,
    /// <summary>
    /// Standard cleanup. Default. Removes navigation, forms, and other auxiliary content.
    /// </summary>
    [JsonPropertyName("standard")]
    Standard,
    /// <summary>
    /// Aggressive cleanup. Remove extensive non-content elements and structure.
    /// </summary>
    [JsonPropertyName("aggressive")]
    Aggressive,
}
