// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b7990c05b16eb430aef43fcc1e747270176f323df84564f01f48cd9be6181a47
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// HTML preprocessing aggressiveness level.
///
/// Controls the extent of cleanup performed before conversion. Higher levels remove more elements.
/// </summary>
public enum PreprocessingPreset
{
    /// <summary>
    /// Minimal cleanup. Remove only essential noise (scripts, styles).
    /// </summary>
    [JsonPropertyName("minimal")]
    Minimal,
    /// <summary>
    /// Standard cleanup. Default. Removes navigation, forms, and other auxiliary content.
    /// </summary>
    [JsonPropertyName("standard")]
    Standard,
    /// <summary>
    /// Aggressive cleanup. Remove extensive non-content elements and structure.
    /// </summary>
    [JsonPropertyName("aggressive")]
    Aggressive,
}
