// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d0f0201bb1f226aaab5e37dd832e9024f99c125870f18f9d859b77462943859e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// HTML preprocessing options for document cleanup before conversion.
/// </summary>
public sealed class PreprocessingOptions
{
    /// <summary>
    /// Enable HTML preprocessing globally
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; } = true;

    /// <summary>
    /// Preprocessing preset level (Minimal, Standard, Aggressive)
    /// </summary>
    [JsonPropertyName("preset")]
    public PreprocessingPreset Preset { get; set; } = default;

    /// <summary>
    /// Remove navigation elements (nav, breadcrumbs, menus, sidebars)
    /// </summary>
    [JsonPropertyName("remove_navigation")]
    public bool RemoveNavigation { get; set; } = true;

    /// <summary>
    /// Remove form elements (forms, inputs, buttons, etc.)
    /// </summary>
    [JsonPropertyName("remove_forms")]
    public bool RemoveForms { get; set; } = true;

}
