// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// Partial update for `PreprocessingOptions`.
///
/// This struct uses `Option<T>` to represent optional fields that can be selectively updated.
/// Only specified fields (Some values) will override existing options; None values leave the
/// corresponding fields unchanged when applied via [`PreprocessingOptions::apply_update`].
/// </summary>
public sealed class PreprocessingOptionsUpdate
{
    /// <summary>
    /// Optional global preprocessing enablement override
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool? Enabled { get; set; } = null;

    /// <summary>
    /// Optional preprocessing preset level override (Minimal, Standard, Aggressive)
    /// </summary>
    [JsonPropertyName("preset")]
    public PreprocessingPreset? Preset { get; set; } = null;

    /// <summary>
    /// Optional navigation element removal override (nav, breadcrumbs, menus, sidebars)
    /// </summary>
    [JsonPropertyName("remove_navigation")]
    public bool? RemoveNavigation { get; set; } = null;

    /// <summary>
    /// Optional form element removal override (forms, inputs, buttons, etc.)
    /// </summary>
    [JsonPropertyName("remove_forms")]
    public bool? RemoveForms { get; set; } = null;

}
