// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f83fc2a46ff342631c2f673164ecde635856a00f8d8d6e50added9fa682fef34
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML sanitization error
/// </summary>
public class SanitizationErrorException : ConversionErrorException
{
    public SanitizationErrorException(string message) : base(message) { }

    public SanitizationErrorException(string message, Exception innerException) : base(message, innerException) { }
}
