// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c71977a3c14f04aa13a391a09c44a04089e60259a8e94a8fc5eef0719a3e5f64
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// Structured data format type.
///
/// Identifies the schema/format used for structured data markup.
/// </summary>
[JsonConverter(typeof(StructuredDataTypeJsonConverter))]
public enum StructuredDataType
{
    /// <summary>
    /// JSON-LD (JSON for Linking Data) script blocks
    /// </summary>
    [JsonPropertyName("json_ld")]
    JsonLd,
    /// <summary>
    /// HTML5 Microdata attributes (itemscope, itemtype, itemprop)
    /// </summary>
    [JsonPropertyName("microdata")]
    Microdata,
    /// <summary>
    /// RDF in Attributes (RDFa) markup
    /// </summary>
    [JsonPropertyName("rdfa")]
    RdFa,
}

/// <summary>Custom JSON converter for <see cref="StructuredDataType"/> that respects explicit variant names.</summary>
internal sealed class StructuredDataTypeJsonConverter : JsonConverter<StructuredDataType>
{
    public override StructuredDataType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "json_ld" => StructuredDataType.JsonLd,
            "microdata" => StructuredDataType.Microdata,
            "rdfa" => StructuredDataType.RdFa,
            _ => throw new JsonException($"Unknown StructuredDataType value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, StructuredDataType value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            StructuredDataType.JsonLd => "json_ld",
            StructuredDataType.Microdata => "microdata",
            StructuredDataType.RdFa => "rdfa",
            _ => throw new JsonException($"Unknown StructuredDataType value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
