// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b083a14c89fdac2cef0af070cb535ba274262d87a178ef84f44a38f2262d3f91
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// A structured table grid with cell-level data including spans.
/// </summary>
public sealed class TableGrid
{
    /// <summary>
    /// Number of rows.
    /// </summary>
    [JsonPropertyName("rows")]
    public uint Rows { get; set; } = 0;

    /// <summary>
    /// Number of columns.
    /// </summary>
    [JsonPropertyName("cols")]
    public uint Cols { get; set; } = 0;

    /// <summary>
    /// All cells in the table (may be fewer than rows*cols due to spans).
    /// </summary>
    [JsonPropertyName("cells")]
    public List<GridCell> Cells { get; set; } = [];

}
