// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// A top-level extracted table with both structured data and markdown representation.
/// </summary>
public sealed class TableData
{
    /// <summary>
    /// The structured table grid.
    /// </summary>
    [JsonPropertyName("grid")]
    public TableGrid Grid { get; set; } = default!;

    /// <summary>
    /// The markdown rendering of this table.
    /// </summary>
    [JsonPropertyName("markdown")]
    public string Markdown { get; set; } = "";

}
