// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// Whitespace handling strategy during conversion.
///
/// Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
/// </summary>
public enum WhitespaceMode
{
    /// <summary>
    /// Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior.
    /// </summary>
    [JsonPropertyName("normalized")]
    Normalized,
    /// <summary>
    /// Preserve all whitespace exactly as it appears in the HTML.
    /// </summary>
    [JsonPropertyName("strict")]
    Strict,
}
