# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0'

gemspec

group :development, :test do
  gem 'rake-compiler'
  gem 'rb_sys' # provides build tooling when developing locally
  gem 'rspec'
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
end
