# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rb_sys/extensiontask'
require 'rspec/core/rake_task'

RbSys::ExtensionTask.new('html-to-markdown-rb') do |ext|
  ext.lib_dir = 'lib'
end

RSpec::Core::RakeTask.new(:spec)

task spec: :compile
task default: :spec
