# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""Public API for the conversion library.

Version: 3.4.0-rc.3
"""

from ._html_to_markdown import (
    AnnotationKind,
    ConversionOptions,
    ConversionOptionsBuilder,
    ConversionResult,
    DocumentNode,
    DocumentStructure,
    GridCell,
    HeaderMetadata,
    ImageMetadata,
    ImageType,
    LinkMetadata,
    LinkType,
    NodeContent,
    NodeContext,
    NodeType,
    ProcessingWarning,
    StructuredData,
    StructuredDataType,
    TableData,
    TextAnnotation,
    VisitResult,
    WarningKind,
)
from .api import convert
from .exceptions import (
    ConfigError,
    ConversionError,
    InvalidInputError,
    IoError,
    OtherError,
    PanicError,
    ParseError,
    SanitizationError,
)
from .options import (
    CodeBlockStyle,
    DocumentMetadata,
    HeadingStyle,
    HighlightStyle,
    HtmlMetadata,
    LinkStyle,
    ListIndentType,
    NewlineStyle,
    OutputFormat,
    PreprocessingOptions,
    PreprocessingPreset,
    TableGrid,
    TextDirection,
    WhitespaceMode,
)

__all__ = [
    "AnnotationKind",
    "CodeBlockStyle",
    "ConfigError",
    "ConversionError",
    "ConversionOptions",
    "ConversionOptionsBuilder",
    "ConversionResult",
    "DocumentMetadata",
    "DocumentNode",
    "DocumentStructure",
    "GridCell",
    "HeaderMetadata",
    "HeadingStyle",
    "HighlightStyle",
    "HtmlMetadata",
    "ImageMetadata",
    "ImageType",
    "InvalidInputError",
    "IoError",
    "LinkMetadata",
    "LinkStyle",
    "LinkType",
    "ListIndentType",
    "NewlineStyle",
    "NodeContent",
    "NodeContext",
    "NodeType",
    "OtherError",
    "OutputFormat",
    "PanicError",
    "ParseError",
    "PreprocessingOptions",
    "PreprocessingPreset",
    "ProcessingWarning",
    "SanitizationError",
    "StructuredData",
    "StructuredDataType",
    "TableData",
    "TableGrid",
    "TextAnnotation",
    "TextDirection",
    "VisitResult",
    "WarningKind",
    "WhitespaceMode",
    "convert",
]

__version__ = "3.4.0-rc.3"
