/**
 * E2e tests for category: edge-cases
 * Generated by html-to-markdown-e2e-generator — do not edit manually.
 */

import { describe, it, expect } from 'vitest';
import { convert } from '@kreuzberg/html-to-markdown-wasm';

describe('edge-cases', () => {
  it('empty_html: Empty HTML document', () => {
    const html = `<html><head></head><body></body></html>`;
    const result = convert(html);
    const content = result.content ?? '';

    expect(content.trim()).toBe('');
  });

  it('whitespace_only: Whitespace-only content', () => {
    const html = `<p>   </p>`;
    const result = convert(html);
    const content = result.content ?? '';

    expect(content.trim()).toBe('');
  });

});
