# frozen_string_literal: true

# E2e tests for category: options
# Generated by html-to-markdown-e2e-generator — do not edit manually.

require 'html_to_markdown'

RSpec.describe 'options' do
  it 'options_code_block_backticks: Backticks code block style uses triple backtick fences' do
    html = "<pre><code class=\"language-js\">console.log('hi');</code></pre>"
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content).to include('```')
    expect(content).to include("console.log('hi');")
  end

  it 'options_code_block_tildes: Tildes code block style uses triple tilde fences' do
    html = '<pre><code>some code</code></pre>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content).to include('~~~')
    expect(content).to include('some code')
  end

  it 'options_escape_asterisks: escape_asterisks option escapes asterisks in plain text' do
    html = '<p>Use 2*3 = 6 in math.</p>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content.strip).not_to be_empty
    expect(content).to include('2')
    expect(content).to include('3')
    expect(content).to include('6')
  end

  it 'options_escape_misc: escape_misc option escapes miscellaneous markdown characters' do
    html = '<p>Use # and | and ~ in text.</p>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content.strip).not_to be_empty
    expect(content).to include('Use')
    expect(content).to include('and')
    expect(content).to include('in text.')
  end

  it 'options_escape_underscores: escape_underscores option escapes underscores in plain text' do
    html = '<p>The variable_name is defined.</p>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content.strip).not_to be_empty
    expect(content).to include('variable')
    expect(content).to include('name')
    expect(content).to include('defined.')
  end

  it 'options_heading_style_atx: ATX heading style produces hash-prefixed headings' do
    html = '<h1>Title</h1><h2>Subtitle</h2>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content).to include('# Title')
    expect(content).to include('## Subtitle')
  end

  it 'options_heading_style_atx_closed: ATX closed heading style adds closing hashes' do
    html = '<h1>Closed Heading</h1>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content).to include('# Closed Heading #')
  end

  it 'options_heading_style_underlined: Underlined heading style produces setext-style headings for h1 and h2' do
    html = '<h1>Main Title</h1>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content.strip).not_to be_empty
    expect(content).to include('Main Title')
  end

  it 'options_list_custom_bullets: Custom bullet character for unordered lists' do
    html = '<ul><li>Item A</li><li>Item B</li></ul>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content).to include('* Item A')
    expect(content).to include('* Item B')
  end

  it 'options_list_indent_tabs: Tab indentation type for nested list items' do
    html = '<ul><li>Parent<ul><li>Child</li></ul></li></ul>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content.strip).not_to be_empty
    expect(content).to include('Parent')
    expect(content).to include('Child')
  end

  it 'options_output_format_djot: Djot output format produces djot-compatible markup' do
    html = '<p>Simple paragraph.</p>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content.strip).not_to be_empty
    expect(content).to include('Simple paragraph.')
  end

  it 'options_output_format_markdown: Default markdown output format produces standard markdown' do
    html = '<h1>Title</h1><p>Some text.</p>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content).to include('# Title')
    expect(content).to include('Some text.')
  end

  it 'options_output_format_plain: Plain text output format strips markdown syntax' do
    html = '<h1>Title</h1><p>Some <strong>bold</strong> text.</p>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content).to include('Title')
    expect(content).to include('bold')
    expect(content).to include('text.')
    expect(content).not_to include('**bold**')
    expect(content).not_to include('# Title')
  end

  it 'options_whitespace_normalized: Normalized whitespace mode collapses multiple spaces' do
    html = '<p>Text   with    extra   spaces.</p>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content.strip).not_to be_empty
    expect(content).to include('Text')
    expect(content).to include('with')
    expect(content).to include('extra')
    expect(content).to include('spaces.')
  end

  it 'options_whitespace_strict: Strict whitespace mode preserves whitespace as-is' do
    html = '<p>Preserved   spacing.</p>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content.strip).not_to be_empty
    expect(content).to include('Preserved')
    expect(content).to include('spacing.')
  end

  it 'options_wrap_disabled: Wrap option disabled preserves long lines without breaking' do
    html = '<p>This is a long paragraph that should not be wrapped at all because wrapping is disabled.</p>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content).to include('This is a long paragraph that should not be wrapped at all because wrapping is disabled.')
  end

  it 'options_wrap_enabled: Wrap option enabled with custom width wraps long lines' do
    html = '<p>This is a long paragraph that should be wrapped at the specified column width when the wrap option is enabled.</p>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content.strip).not_to be_empty
    expect(content).to include('This is a long paragraph')
  end
end
