# frozen_string_literal: true

# E2e tests for category: smoke
# Generated by html-to-markdown-e2e-generator — do not edit manually.

require 'html_to_markdown'

RSpec.describe 'smoke' do
  it 'smoke_empty_string: Empty string produces empty output' do
    html = ''
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content.strip).to eq('')
  end

  it 'smoke_simple_heading: H1 heading converts to ATX markdown' do
    html = '<h1>Title</h1>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content).to include('# Title')
  end

  it 'smoke_simple_paragraph: Simple paragraph converts correctly' do
    html = '<p>Hello World</p>'
    result = HtmlToMarkdown.convert(html)
    content = result[:content] || ''

    expect(content.strip).to eq('Hello World')
    expect(content.strip).not_to be_empty
  end
end
