# This file is auto-generated by alef. DO NOT EDIT.
# frozen_string_literal: true

require 'html_to_markdown'
require 'json'

RSpec.describe 'visitor' do
  it 'visitor_continue_default: Visitor continue action preserves default conversion' do
    visitor = Class.new do
      def visit_strong(ctx, text)
        'continue'
      end
    end.new
    result = HtmlToMarkdown.convert('<p>Hello <strong>World</strong></p>', visitor)
    expect(result.to_s).to include('**World**')
  end

  it 'visitor_custom_blockquote: Visitor replaces blockquote with custom format' do
    visitor = Class.new do
      def visit_blockquote(ctx, content, depth)
        { custom: "QUOTE: "{content}"" }
      end
    end.new
    result = HtmlToMarkdown.convert('<blockquote><p>A wise quote.</p></blockquote>', visitor)
    expect(result.to_s).to include('QUOTE:')
    expect(result.to_s).to include('A wise quote.')
  end

  it 'visitor_custom_emphasis: Visitor replaces emphasis with custom output' do
    visitor = Class.new do
      def visit_emphasis(ctx, text)
        { custom: ">>>{text}<<<" }
      end
    end.new
    result = HtmlToMarkdown.convert('<p>This is <em>important</em> text.</p>', visitor)
    expect(result.to_s).to include('>>>important<<<')
    expect(result.to_s).not_to include('*important*')
  end

  it 'visitor_custom_heading: Visitor replaces heading with custom format' do
    visitor = Class.new do
      def visit_heading(ctx, level, text, id)
        { custom: "--- {text} ---" }
      end
    end.new
    result = HtmlToMarkdown.convert('<h2>Section Title</h2><p>Content below heading.</p>', visitor)
    expect(result.to_s).to include('--- Section Title ---')
    expect(result.to_s).not_to include('## Section Title')
    expect(result.to_s).to include('Content below heading.')
  end

  it 'visitor_custom_image: Visitor replaces image with custom output using template' do
    visitor = Class.new do
      def visit_image(ctx, src, alt, title)
        { custom: "[Image: {alt}]" }
      end
    end.new
    result = HtmlToMarkdown.convert('<img src="banner.png" alt="Banner">', visitor)
    expect(result.to_s).to include('[Image: Banner]')
    expect(result.to_s).not_to include('banner.png')
  end

  it 'visitor_custom_link_format: Visitor reformats links using template interpolation' do
    visitor = Class.new do
      def visit_link(ctx, href, text, title)
        { custom: "{text} ({href})" }
      end
    end.new
    result = HtmlToMarkdown.convert('<p>Visit <a href="https://example.com">Example</a> for more info.</p>', visitor)
    expect(result.to_s).to include('Example (https://example.com)')
    expect(result.to_s).not_to include('[Example]')
  end

  it 'visitor_custom_link_static: Visitor replaces link with static custom output' do
    visitor = Class.new do
      def visit_link(ctx, href, text, title)
        { custom: '[REDACTED LINK]' }
      end
    end.new
    result = HtmlToMarkdown.convert('<a href="https://example.com">Click here</a>', visitor)
    expect(result.to_s).to include('[REDACTED LINK]')
    expect(result.to_s).not_to include('example.com')
  end

  it 'visitor_custom_output: Visitor custom action replaces element output' do
    visitor = Class.new do
      def visit_heading(ctx, level, text, id)
        { custom: '## REPLACED HEADING' }
      end
    end.new
    result = HtmlToMarkdown.convert('<h1>Original Heading</h1>', visitor)
    expect(result.to_s).to include('## REPLACED HEADING')
    expect(result.to_s).not_to include('# Original Heading')
  end

  it 'visitor_preserve_html: Visitor preserve_html action includes raw HTML in output' do
    visitor = Class.new do
      def visit_custom_element(ctx, tag_name, html)
        'preserve_html'
      end
    end.new
    result = HtmlToMarkdown.convert('<div><custom-tag>Custom content</custom-tag></div>', visitor)
    expect(result.to_s).to include('<custom-tag>')
  end

  it 'visitor_skip_all_headings: Visitor skips all headings from document' do
    visitor = Class.new do
      def visit_heading(ctx, level, text, id)
        'skip'
      end
    end.new
    result = HtmlToMarkdown.convert('<h1>Title</h1><p>Body text remains.</p>', visitor)
    expect(result.to_s).not_to include('Title')
    expect(result.to_s).to include('Body text remains.')
  end

  it 'visitor_skip_code_blocks: Visitor skips code blocks from output' do
    visitor = Class.new do
      def visit_code_block(ctx, lang, code)
        'skip'
      end
    end.new
    result = HtmlToMarkdown.convert('<p>Intro text</p><pre><code>let x = 42;</code></pre><p>Outro text</p>', visitor)
    expect(result.to_s).to include('Intro text')
    expect(result.to_s).to include('Outro text')
    expect(result.to_s).not_to include('let x = 42')
  end

  it 'visitor_skip_heading: Visitor skip action omits all headings from output' do
    visitor = Class.new do
      def visit_heading(ctx, level, text, id)
        'skip'
      end
    end.new
    result = HtmlToMarkdown.convert('<h1>Title</h1><p>Body text remains.</p>', visitor)
    expect(result.to_s).not_to include('Title')
    expect(result.to_s).to include('Body text remains.')
  end

  it 'visitor_skip_images: Visitor skips all images from output' do
    visitor = Class.new do
      def visit_image(ctx, src, alt, title)
        'skip'
      end
    end.new
    result = HtmlToMarkdown.convert('<p>Before image</p><img src="photo.jpg" alt="A photo"><p>After image</p>', visitor)
    expect(result.to_s).to include('Before image')
    expect(result.to_s).to include('After image')
    expect(result.to_s).not_to include('photo.jpg')
    expect(result.to_s).not_to include('A photo')
  end

  it 'visitor_skip_links: Visitor skips all links entirely' do
    visitor = Class.new do
      def visit_link(ctx, href, text, title)
        'skip'
      end
    end.new
    result = HtmlToMarkdown.convert('<p>Before <a href="https://example.com">link text</a> after</p>', visitor)
    expect(result.to_s).not_to include('link text')
    expect(result.to_s).not_to include('example.com')
  end

  it 'visitor_skip_strong: Visitor skips bold/strong elements' do
    visitor = Class.new do
      def visit_strong(ctx, text)
        'skip'
      end
    end.new
    result = HtmlToMarkdown.convert('<p>Normal <strong>bold text</strong> normal</p>', visitor)
    expect(result.to_s).not_to include('bold text')
    expect(result.to_s).to include('Normal')
  end
end
