// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import java.util.Optional;

/**
 * The primary result of HTML conversion and extraction.
 *
 * Contains the converted text output, optional structured document tree,
 * metadata, extracted tables, images, and processing warnings.
 *
 * # Example
 *
 * {@code }{@code text}
 * use html_to_markdown_rs::{convert, ConversionOptions};
 *
 * let result = convert("&lt;h1&gt;Hello&lt;/h1&gt;&lt;p&gt;World&lt;/p&gt;", None)?;
 * assert!(result.content.is_some());
 * assert!(result.warnings.is_empty());
 * {@code }{@code }
 */
public class ConversionResultBuilder {

    private Optional<String> content = Optional.empty();
    private Optional<DocumentStructure> document = Optional.empty();
    private HtmlMetadata metadata = null;
    private List<TableData> tables = List.of();
    private List<String> images = List.of();
    private List<ProcessingWarning> warnings = List.of();

    public ConversionResultBuilder withContent(Optional<String> value) {
        this.content = value;
        return this;
    }

    public ConversionResultBuilder withDocument(Optional<DocumentStructure> value) {
        this.document = value;
        return this;
    }

    public ConversionResultBuilder withMetadata(HtmlMetadata value) {
        this.metadata = value;
        return this;
    }

    public ConversionResultBuilder withTables(List<TableData> value) {
        this.tables = value;
        return this;
    }

    public ConversionResultBuilder withImages(List<String> value) {
        this.images = value;
        return this;
    }

    public ConversionResultBuilder withWarnings(List<ProcessingWarning> value) {
        this.warnings = value;
        return this;
    }

    public ConversionResult build() {
        return new ConversionResult(
            content,
            document,
            metadata,
            tables,
            images,
            warnings
        );
    }
}
