// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record DocumentStructure(List<DocumentNode> nodes,
		@JsonProperty("source_format") Optional<String> sourceFormat) {
}
