// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.htmltomarkdown;

/** Exception thrown by HtmlToMarkdownRs. */
public class HtmlToMarkdownRsException extends Exception {
    /** The error code. */
    private final int code;

    /** Creates a new HtmlToMarkdownRsException. */
    public HtmlToMarkdownRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new HtmlToMarkdownRsException with a cause. */
    public HtmlToMarkdownRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
