// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

public final class HtmlToMarkdown {
  private HtmlToMarkdown() {}

  /**
   * Convert HTML to Markdown, returning a [`ConversionResult`] with content, metadata, images, and
   * warnings.
   *
   * <p># Arguments
   *
   * <p>* `html` - The HTML string to convert * `options` - Optional conversion options (defaults to
   * `ConversionOptions::default()`)
   *
   * <p># Example
   *
   * <p>``` use html_to_markdown_rs::{convert, ConversionOptions};
   *
   * <p>let html = "
   *
   * <h1>Hello World</h1>
   *
   * "; let result = convert(html, None, None).unwrap();
   * assert!(result.content.as_deref().unwrap_or("").contains("Hello World")); ```
   *
   * <p># Errors
   *
   * <p>Returns an error if HTML parsing fails or if the input contains invalid UTF-8.
   */
  public static ConversionResult convert(final String html, final ConversionOptions options)
      throws HtmlToMarkdownRsException {
    java.util.Objects.requireNonNull(html, "html must not be null");
    return HtmlToMarkdownRs.convert(html, options);
  }

  public static ConversionResult convert(final String html) throws HtmlToMarkdownRsException {
    return HtmlToMarkdownRs.convert(html, null);
  }
}
