// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;

/**
 * Comprehensive metadata extraction result from HTML document.
 *
 * Contains all extracted metadata types in a single structure,
 * suitable for serialization and transmission across language boundaries.
 *
 * # Examples
 *
 * {@code }{@code }
 * # use html_to_markdown_rs::metadata::HtmlMetadata;
 * let metadata = HtmlMetadata {
 *     document: Default::default(),
 *     headers: Vec::new(),
 *     links: Vec::new(),
 *     images: Vec::new(),
 *     structured_data: Vec::new(),
 * };
 *
 * assert!(metadata.headers.is_empty());
 * {@code }{@code }
 */
public class HtmlMetadataBuilder {

    private DocumentMetadata document = null;
    private List<HeaderMetadata> headers = List.of();
    private List<LinkMetadata> links = List.of();
    private List<ImageMetadata> images = List.of();
    private List<StructuredData> structuredData = List.of();

    public HtmlMetadataBuilder withDocument(DocumentMetadata value) {
        this.document = value;
        return this;
    }

    public HtmlMetadataBuilder withHeaders(List<HeaderMetadata> value) {
        this.headers = value;
        return this;
    }

    public HtmlMetadataBuilder withLinks(List<LinkMetadata> value) {
        this.links = value;
        return this;
    }

    public HtmlMetadataBuilder withImages(List<ImageMetadata> value) {
        this.images = value;
        return this;
    }

    public HtmlMetadataBuilder withStructuredData(List<StructuredData> value) {
        this.structuredData = value;
        return this;
    }

    public HtmlMetadata build() {
        return new HtmlMetadata(
            document,
            headers,
            links,
            images,
            structuredData
        );
    }
}
