// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Image source classification for proper handling and processing.
 *
 * Determines whether an image is embedded (data URI), inline SVG, external, or relative.
 */
public enum ImageType {
    /** Data URI embedded image (base64 or other encoding) */
    DataUri("data_uri"),
    /** Inline SVG element */
    InlineSvg("inline_svg"),
    /** External image URL (http/https) */
    External("external"),
    /** Relative image path */
    Relative("relative");

    private final String value;

    ImageType(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @JsonCreator
    public static ImageType fromValue(String value) {
        for (ImageType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
