// DO NOT EDIT - auto-generated by alef
// alef:hash:e53e30a84ebea2d29a0e1eed148a0d378acb527de4ddce2f3c91bcf5e509423e
package dev.kreuzberg.htmltomarkdown;

/** I/O error. */
public class IoErrorException extends ConversionErrorException {
    /** Creates a new IoErrorException with the given message. */
    public IoErrorException(final String message) {
        super(message);
    }

    /** Creates a new IoErrorException with the given message and cause. */
    public IoErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
