// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Link classification based on href value and document context.
 *
 * <p>Used to categorize links during extraction for filtering and analysis.
 */
public enum LinkType {
  /** Anchor link within same document (href starts with #) */
  Anchor("anchor"),
  /** Internal link within same domain */
  Internal("internal"),
  /** External link to different domain */
  External("external"),
  /** Email link (mailto:) */
  Email("email"),
  /** Phone link (tel:) */
  Phone("phone"),
  /** Other protocol or unclassifiable */
  Other("other");

  /** The string value. */
  private final String value;

  LinkType(final String value) {
    this.value = value;
  }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static LinkType fromValue(final String value) {
    for (LinkType e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown value: " + value);
  }
}
