// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.htmltomarkdown;


/**
 * Configuration for metadata extraction granularity.
 *
 * Controls which metadata types are extracted and size limits for safety.
 * Enables selective extraction of different metadata categories from HTML documents,
 * allowing fine-grained control over which types of information to collect during
 * the HTML-to-Markdown conversion process.
 *
 * # Fields
 *
 * - {@code extract_document}: Enable document-level metadata extraction (title, description, author, Open Graph, Twitter Card, etc.)
 * - {@code extract_headers}: Enable heading element extraction (h1-h6) with hierarchy tracking
 * - {@code extract_links}: Enable anchor element extraction with link type classification
 * - {@code extract_images}: Enable image element extraction with source and dimension metadata
 * - {@code extract_structured_data}: Enable structured data extraction (JSON-LD, Microdata, RDFa)
 * - {@code max_structured_data_size}: Safety limit on total structured data size in bytes
 *
 * # Examples
 *
 * {@code }{@code }
 * # use html_to_markdown_rs::metadata::MetadataConfig;
 * let config = MetadataConfig {
 *     extract_document: true,
 *     extract_headers: true,
 *     extract_links: true,
 *     extract_images: true,
 *     extract_structured_data: true,
 *     max_structured_data_size: 1_000_000,
 * };
 *
 * assert!(config.extract_headers);
 * {@code }{@code }
 */
public class MetadataConfigBuilder {

    private boolean extractDocument = false;
    private boolean extractHeaders = false;
    private boolean extractLinks = false;
    private boolean extractImages = false;
    private boolean extractStructuredData = false;
    private long maxStructuredDataSize = 0;

    public MetadataConfigBuilder withExtractDocument(boolean value) {
        this.extractDocument = value;
        return this;
    }

    public MetadataConfigBuilder withExtractHeaders(boolean value) {
        this.extractHeaders = value;
        return this;
    }

    public MetadataConfigBuilder withExtractLinks(boolean value) {
        this.extractLinks = value;
        return this;
    }

    public MetadataConfigBuilder withExtractImages(boolean value) {
        this.extractImages = value;
        return this;
    }

    public MetadataConfigBuilder withExtractStructuredData(boolean value) {
        this.extractStructuredData = value;
        return this;
    }

    public MetadataConfigBuilder withMaxStructuredDataSize(long value) {
        this.maxStructuredDataSize = value;
        return this;
    }

    public MetadataConfig build() {
        return new MetadataConfig(
            extractDocument,
            extractHeaders,
            extractLinks,
            extractImages,
            extractStructuredData,
            maxStructuredDataSize
        );
    }
}
