// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.htmltomarkdown;

import java.util.Optional;

/**
 * Partial update for {@code MetadataConfig}.
 *
 * This struct uses {@code Option<T>} to represent optional fields that can be selectively updated.
 * Only specified fields (Some values) will override existing config; None values leave the
 * corresponding fields unchanged when applied via [{@code MetadataConfig::apply_update}].
 *
 * # Fields
 *
 * - {@code extract_document}: Optional override for document-level metadata extraction
 * - {@code extract_headers}: Optional override for heading element extraction
 * - {@code extract_links}: Optional override for link element extraction
 * - {@code extract_images}: Optional override for image element extraction
 * - {@code extract_structured_data}: Optional override for structured data extraction
 * - {@code max_structured_data_size}: Optional override for structured data size limit
 *
 * # Examples
 *
 * {@code }{@code }
 * # use html_to_markdown_rs::metadata::{MetadataConfig, MetadataConfigUpdate};
 * let update = MetadataConfigUpdate {
 *     extract_document: Some(false),
 *     extract_headers: Some(true),
 *     extract_links: None,  // No change
 *     extract_images: None,  // No change
 *     extract_structured_data: None,  // No change
 *     max_structured_data_size: None,  // No change
 * };
 *
 * let mut config = MetadataConfig::default();
 * config.apply_update(update);
 * assert!(!config.extract_document);
 * assert!(config.extract_headers);
 * {@code }{@code }
 */
public class MetadataConfigUpdateBuilder {

    private Optional<Boolean> extractDocument = Optional.empty();
    private Optional<Boolean> extractHeaders = Optional.empty();
    private Optional<Boolean> extractLinks = Optional.empty();
    private Optional<Boolean> extractImages = Optional.empty();
    private Optional<Boolean> extractStructuredData = Optional.empty();
    private Optional<Long> maxStructuredDataSize = Optional.empty();

    public MetadataConfigUpdateBuilder withExtractDocument(Optional<Boolean> value) {
        this.extractDocument = value;
        return this;
    }

    public MetadataConfigUpdateBuilder withExtractHeaders(Optional<Boolean> value) {
        this.extractHeaders = value;
        return this;
    }

    public MetadataConfigUpdateBuilder withExtractLinks(Optional<Boolean> value) {
        this.extractLinks = value;
        return this;
    }

    public MetadataConfigUpdateBuilder withExtractImages(Optional<Boolean> value) {
        this.extractImages = value;
        return this;
    }

    public MetadataConfigUpdateBuilder withExtractStructuredData(Optional<Boolean> value) {
        this.extractStructuredData = value;
        return this;
    }

    public MetadataConfigUpdateBuilder withMaxStructuredDataSize(Optional<Long> value) {
        this.maxStructuredDataSize = value;
        return this;
    }

    public MetadataConfigUpdate build() {
        return new MetadataConfigUpdate(
            extractDocument,
            extractHeaders,
            extractLinks,
            extractImages,
            extractStructuredData,
            maxStructuredDataSize
        );
    }
}
