// DO NOT EDIT - auto-generated by alef
// alef:hash:a76090e6d1681f9b9abb3e727b5c31a9000b90aaab22d68cbfc0ecb847eb9be5
package dev.kreuzberg.htmltomarkdown;

/** HTML parsing error. */
public class ParseErrorException extends ConversionErrorException {
    /** Creates a new ParseErrorException with the given message. */
    public ParseErrorException(final String message) {
        super(message);
    }

    /** Creates a new ParseErrorException with the given message and cause. */
    public ParseErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
