// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * HTML preprocessing aggressiveness level.
 *
 * <p>Controls the extent of cleanup performed before conversion. Higher levels remove more
 * elements.
 */
public enum PreprocessingPreset {
  /** Minimal cleanup. Remove only essential noise (scripts, styles). */
  Minimal("minimal"),
  /** Standard cleanup. Default. Removes navigation, forms, and other auxiliary content. */
  Standard("standard"),
  /** Aggressive cleanup. Remove extensive non-content elements and structure. */
  Aggressive("aggressive");

  /** The string value. */
  private final String value;

  PreprocessingPreset(final String value) {
    this.value = value;
  }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static PreprocessingPreset fromValue(final String value) {
    for (PreprocessingPreset e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown value: " + value);
  }
}
