// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2c3838a788e7e537081336bddb73cd08500025aaaca28e174bcc667625de6a80
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

/**
 * A non-fatal warning generated during HTML processing.
 */
public record ProcessingWarning(String message, WarningKind kind) {
}
