// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;

/**
 * A structured table grid with cell-level data including spans.
 */
public record TableGrid(int rows, int cols, List<GridCell> cells) {
    public static TableGridBuilder builder() {
        return new TableGridBuilder();
    }
}
