// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f56b01d524e0f793a60fa854cfd8573e3b55a09c5404694c86f0be39a2e01847
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'package:html_to_markdown_rs/html_to_markdown_rs.dart';

// E2e tests for category: edge-cases
void main() {
  test('Empty HTML document', () {
    final result = convert('<html><head></head><body></body></html>');
    expect(result.content.trim(), equals(''));
  });

  test('CJK (Chinese, Japanese, Korean) characters are preserved', () {
    final result = convert('<p>中文内容</p><p>日本語テキスト</p><p>한국어 텍스트</p>');
    expect(result.content, isNotEmpty);
    expect(result.content, contains('中文内容'));
    expect(result.content, contains('日本語テキスト'));
    expect(result.content, contains('한국어 텍스트'));
  });

  test('Common HTML entities are decoded in output', () {
    final result = convert('<p>&amp; &lt; &gt; &nbsp; &quot; &apos;</p>');
    expect(result.content, isNotEmpty);
    expect(result.content, contains('&'));
    expect(result.content, contains('<'));
    expect(result.content, contains('>'));
  });

  test('Named HTML entities like &mdash; and &hellip; are decoded', () {
    final result = convert('<p>Em dash&mdash;used for parenthetical remarks&mdash;is common. Ellipsis&hellip; indicates omission. Non-breaking&nbsp;space.</p>');
    expect(result.content, isNotEmpty);
    expect(result.content, contains('—'));
    expect(result.content, contains('…'));
  });

  test('Numeric HTML entities (decimal and hex) are decoded', () {
    final result = convert('<p>Copyright: &#169; Trade: &#174; Euro: &#8364; Hex: &#x00A9;</p>');
    expect(result.content, isNotEmpty);
    expect(result.content, contains('©'));
    expect(result.content, contains('®'));
    expect(result.content, contains('€'));
  });

  test('Emoji and Unicode characters are preserved', () {
    final result = convert('<p>Hello 🌍 World 🚀</p><p>Stars: ⭐ ✨</p>');
    expect(result.content, isNotEmpty);
    expect(result.content, contains('🌍'));
    expect(result.content, contains('🚀'));
    expect(result.content, contains('⭐'));
  });

  test('Document containing only HTML comments produces empty output', () {
    final result = convert('<!-- This is a comment --><!-- Another comment -->');
    expect(result.content.trim(), equals(''));
  });

  test('Input that is only whitespace characters (spaces, tabs, newlines) produces empty output', () {
    final result = convert('   ');
    expect(result.content.trim(), equals(''));
  });

  test('Deeply nested elements (100 levels) are handled without stack overflow', () {
    final result = convert('<div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><p>Deeply nested content</p></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>');
    expect(result.content, isNotEmpty);
    expect(result.content, contains('Deeply nested content'));
  });

  test('Missing closing tags on block elements are auto-closed by parser', () {
    final result = convert('<div><h1>Title<p>First paragraph<p>Second paragraph</div>');
    expect(result.content, isNotEmpty);
    expect(result.content, contains('Title'));
    expect(result.content, contains('First paragraph'));
    expect(result.content, contains('Second paragraph'));
  });

  test('Overlapping bold/italic tags are recovered by the HTML parser without panic', () {
    final result = convert('<p><b><i>bold and italic</b></i></p>');
    expect(result.content, isNotEmpty);
    expect(result.content, contains('bold and italic'));
  });

  test('Unclosed <p> tag is recovered gracefully and content is preserved', () {
    final result = convert('<p>This paragraph is never closed');
    expect(result.content, isNotEmpty);
    expect(result.content, contains('This paragraph is never closed'));
  });

  test('Document with only script tags produces empty output (scripts are stripped)', () {
    final result = convert('<html><head><script>alert(\'xss\')</script></head><body><script>document.write(\'hello\')</script></body></html>');
    expect(result.content.trim(), equals(''));
  });

  test('Document with only style tags produces empty output (styles are stripped)', () {
    final result = convert('<html><head><style>body { color: red; }</style></head><body><style>.foo { margin: 0; }</style></body></html>');
    expect(result.content.trim(), equals(''));
  });

  test('Visitor handles custom elements with nested content', () {
    final result = convert('<div><custom-widget data-value="123"><p>Widget content here</p><span>With nested elements</span></custom-widget></div>');
    expect(result.content, contains('[CUSTOM WIDGET]'));
    expect(result.content, isNot(contains('Widget content here')));
  });

  test('Visitor skips deeply nested elements', () {
    final result = convert('<div><p>Outer <em>emphasis <strong>with bold <mark>and highlight</mark></strong></em> text</p></div>');
    expect(result.content, contains('Outer'));
    expect(result.content, contains('text'));
    expect(result.content, isNot(contains('highlight')));
  });

  test('Visitor modifies element at end after children processed', () {
    final result = convert('<blockquote><p>Original quote</p></blockquote>');
    expect(result.content, isNotEmpty);
  });

  test('Visitor skips at element_start level removes entire subtree', () {
    final result = convert('<div><h1>Title</h1><p>Content</p></div>');
    expect(result.content, isNotEmpty);
  });

  test('Visitor preserves unknown HTML tags as raw HTML', () {
    final result = convert('<article><p>Article text</p><x-custom>Custom element with content</x-custom><p>More article text</p></article>');
    expect(result.content, contains('Article text'));
    expect(result.content, contains('More article text'));
    expect(result.content, contains('<x-custom>'));
  });

  test('Whitespace-only content', () {
    final result = convert('<p>   </p>');
    expect(result.content.trim(), equals(''));
  });

  test('onclick and other on* event handlers are removed from elements', () {
    final result = convert('<p><a href="https://example.com" onclick="alert(\'xss\')">Click me</a></p><button onmouseover="steal_data()">Hover me</button>');
    expect(result.content, isNotEmpty);
    expect(result.content, contains('Click me'));
  });

  test('Script tag content is stripped and does not appear in output', () {
    final result = convert('<p>Safe content.</p><script>alert(\'xss\')</script><p>More safe content.</p>');
    expect(result.content, isNotEmpty);
    expect(result.content, contains('Safe content'));
    expect(result.content, contains('More safe content'));
  });

  test('Script tags nested inside SVG are stripped', () {
    final result = convert('<p>Before SVG.</p><svg xmlns="http://www.w3.org/2000/svg"><script>alert(\'svg-xss\')</script><text>SVG text</text></svg><p>After SVG.</p>');
    expect(result.content, isNotEmpty);
    expect(result.content, contains('Before SVG'));
    expect(result.content, contains('After SVG'));
  });

}
