#!/usr/bin/env bash
# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:296a5a1518806f1927b5b72dc2c772b11ecb3c3cf9f45c18165a99af8f741e92
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: real-world
set -euo pipefail

test_real_world_blog_post() {
  # Blog post with headings, paragraphs, code blocks, and links converts to readable Markdown
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_real_world_documentation_page() {
  # Documentation page with nested lists, code examples, and blockquotes converts correctly
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_real_world_product_page() {
  # Product page with table, images, and lists converts correctly
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

run_tests_real_world() {
  run_test test_real_world_blog_post
  run_test test_real_world_documentation_page
  run_test test_real_world_product_page
}
