#!/usr/bin/env bash
# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:72c08cd6196c0a3c54634dd766cd634f837a00f381ce306405d1f4e818629834
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: options
set -euo pipefail

test_options_autolinks_false() {
  # Bare URL links rendered as regular markdown links when autolinks disabled
  local output
  output=$(html_to_markdown convert)

}

test_options_br_in_tables_false() {
  # BR elements in table cells are stripped when disabled
  local output
  output=$(html_to_markdown convert)

}

test_options_br_in_tables_true() {
  # BR elements in table cells render as line breaks
  local output
  output=$(html_to_markdown convert)

}

test_options_code_block_backticks() {
  # Backticks code block style uses triple backtick fences
  local output
  output=$(html_to_markdown convert)

}

test_options_code_block_indented() {
  # Code blocks use 4-space indentation
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" '```' 'content'
}

test_options_code_block_tildes() {
  # Code blocks use tilde fences
  local output
  output=$(html_to_markdown convert)

}

test_options_code_block_tildes_style() {
  # Tildes code block style uses triple tilde fences
  local output
  output=$(html_to_markdown convert)

}

test_options_code_language_python() {
  # Default code language annotation on blocks without lang attribute
  local output
  output=$(html_to_markdown convert)

}

test_options_convert_as_inline() {
  # Block elements treated as inline
  local output
  output=$(html_to_markdown convert)

}

test_options_debug_true() {
  # Debug mode enabled does not crash and produces output
  local output
  output=$(html_to_markdown convert)

}

test_options_default_title_true() {
  # Links without title get empty title attribute when defaultTitle is true
  local output
  output=$(html_to_markdown convert)

}

test_options_encoding_utf8() {
  # UTF-8 encoding hint for special characters
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_escape_ascii_enabled() {
  # ASCII Markdown characters are escaped when escapeAscii is true
  local output
  output=$(html_to_markdown convert)

}

test_options_escape_asterisks() {
  # escape_asterisks option escapes asterisks in plain text
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_escape_misc() {
  # escape_misc option escapes miscellaneous markdown characters
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_escape_underscores() {
  # escape_underscores option escapes underscores in plain text
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_exclude_selectors_attribute() {
  # Elements matching CSS attribute selector are excluded entirely
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_contains "$val_content" 'Primary text' 'content'
  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'Sidebar' 'content'
}

test_options_exclude_selectors_class() {
  # Elements matching CSS class selector are excluded entirely
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_contains "$val_content" 'Main content' 'content'
  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'cookies' 'content'
}

test_options_exclude_selectors_empty_noop() {
  # Empty exclude_selectors list does not affect output
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_contains "$val_content" 'Hello world' 'content'
}

test_options_exclude_selectors_id() {
  # Elements matching CSS id selector are excluded entirely
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_contains "$val_content" 'Article text' 'content'
  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'Buy stuff' 'content'
}

test_options_exclude_selectors_multiple() {
  # Multiple CSS selectors each exclude their matched elements
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_contains "$val_content" 'Content' 'content'
  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'Menu' 'content'
  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'Footer' 'content'
}

test_options_exclude_selectors_nested_content_dropped() {
  # All descendants of excluded elements are dropped
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_contains "$val_content" 'Main text' 'content'
  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'Related' 'content'
  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'Sidebar text' 'content'
}

test_options_exclude_selectors_plain_text_mode() {
  # Exclude selectors work in plain text output mode
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_contains "$val_content" 'Article body' 'content'
  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'Navigation' 'content'
}

test_options_exclude_selectors_vs_strip_tags() {
  # exclude_selectors drops entire subtree unlike strip_tags which keeps children
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_contains "$val_content" 'Outer text' 'content'
  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'Inner paragraph' 'content'
}

test_options_extract_metadata_true() {
  # Extract metadata returns document metadata when enabled
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
  local val_metadata_title
  val_metadata_title=$(echo "$output" | jq -r '.metadata.document.title')
  assert_equals "$val_metadata_title" 'Test Page' 'metadata.title'
  local val_metadata_description
  val_metadata_description=$(echo "$output" | jq -r '.metadata.document.description')
  assert_equals "$val_metadata_description" 'A test page' 'metadata.description'
}

test_options_heading_style_atx() {
  # ATX heading style produces hash-prefixed headings
  local output
  output=$(html_to_markdown convert)

}

test_options_heading_style_atx_closed() {
  # ATX closed heading style adds closing hashes
  local output
  output=$(html_to_markdown convert)

}

test_options_heading_style_underlined() {
  # Underlined heading style produces setext-style headings for h1 and h2
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_highlight_bold() {
  # Mark tag rendered as bold
  local output
  output=$(html_to_markdown convert)

}

test_options_highlight_double_equal() {
  # Mark tag with double equal highlight style
  local output
  output=$(html_to_markdown convert)

}

test_options_highlight_none() {
  # Mark tag with no highlight style strips the mark
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" '==' 'content'
}

test_options_keep_inline_images_in_paragraph() {
  # Images inside specified tags stay inline
  local output
  output=$(html_to_markdown convert)

}

test_options_link_style_reference() {
  # Links use reference-style formatting
  local output
  output=$(html_to_markdown convert)

}

test_options_list_custom_bullets() {
  # Custom bullet character for unordered lists
  local output
  output=$(html_to_markdown convert)

}

test_options_list_indent_tabs() {
  # Tab indentation type for nested list items
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_list_indent_width_four() {
  # Nested lists indented with 4 spaces per level
  local output
  output=$(html_to_markdown convert)

}

test_options_max_depth_default_unlimited() {
  # Default max_depth (null) converts deeply nested content fully
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_contains "$val_content" 'Deep content' 'content'
}

test_options_max_depth_truncates() {
  # max_depth truncates content beyond the specified depth
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_contains "$val_content" 'Shallow' 'content'
  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'Too deep' 'content'
}

test_options_max_depth_zero_empty() {
  # max_depth of 0 produces empty output
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_equals "$val_content" '' 'content'
}

test_options_newline_backslash() {
  # Hard line breaks rendered with backslash
  local output
  output=$(html_to_markdown convert)

}

test_options_newline_spaces() {
  # Hard line breaks rendered with trailing spaces
  local output
  output=$(html_to_markdown convert)

}

test_options_output_format_djot() {
  # Djot output format produces djot-compatible markup
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_output_format_markdown() {
  # Default markdown output format produces standard markdown
  local output
  output=$(html_to_markdown convert)

}

test_options_output_format_plain() {
  # Plain text output format strips markdown syntax
  local output
  output=$(html_to_markdown convert)

}

test_options_preprocessing_aggressive() {
  # Aggressive preset removes nav, footer, aside unconditionally
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'Menu' 'content'
}

test_options_preprocessing_minimal() {
  # Minimal preset preserves nav, footer, aside
  local output
  output=$(html_to_markdown convert)

}

test_options_preprocessing_remove_forms() {
  # Forms are removed when remove_forms is true
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'Submit' 'content'
}

test_options_preserve_tags_iframe() {
  # Iframe tags preserved as raw HTML in output
  local output
  output=$(html_to_markdown convert)

}

test_options_skip_images_true() {
  # Images are omitted from output when skipImages is true
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'photo' 'content'
}

test_options_strip_newlines() {
  # Strip newlines produces single-line paragraphs
  local output
  output=$(html_to_markdown convert)

}

test_options_strip_tags_div_span() {
  # Div and span tags stripped but content preserved
  local output
  output=$(html_to_markdown convert)

}

test_options_strong_em_underscore() {
  # Strong and em tags use underscore symbol instead of asterisk
  local output
  output=$(html_to_markdown convert)

}

test_options_sub_symbol_tilde() {
  # Subscript rendered with tilde symbol
  local output
  output=$(html_to_markdown convert)

}

test_options_sup_symbol_caret() {
  # Superscript rendered with caret symbol
  local output
  output=$(html_to_markdown convert)

}

test_options_whitespace_normalized() {
  # Normalized whitespace mode collapses multiple spaces
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_whitespace_strict() {
  # Strict whitespace mode preserves whitespace as-is
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_wrap_disabled() {
  # Wrap option disabled preserves long lines without breaking
  local output
  output=$(html_to_markdown convert)

}

test_options_wrap_enabled() {
  # Wrap option enabled with custom width wraps long lines
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

run_tests_options() {
  run_test test_options_autolinks_false
  run_test test_options_br_in_tables_false
  run_test test_options_br_in_tables_true
  run_test test_options_code_block_backticks
  run_test test_options_code_block_indented
  run_test test_options_code_block_tildes
  run_test test_options_code_block_tildes_style
  run_test test_options_code_language_python
  run_test test_options_convert_as_inline
  run_test test_options_debug_true
  run_test test_options_default_title_true
  run_test test_options_encoding_utf8
  run_test test_options_escape_ascii_enabled
  run_test test_options_escape_asterisks
  run_test test_options_escape_misc
  run_test test_options_escape_underscores
  run_test test_options_exclude_selectors_attribute
  run_test test_options_exclude_selectors_class
  run_test test_options_exclude_selectors_empty_noop
  run_test test_options_exclude_selectors_id
  run_test test_options_exclude_selectors_multiple
  run_test test_options_exclude_selectors_nested_content_dropped
  run_test test_options_exclude_selectors_plain_text_mode
  run_test test_options_exclude_selectors_vs_strip_tags
  run_test test_options_extract_metadata_true
  run_test test_options_heading_style_atx
  run_test test_options_heading_style_atx_closed
  run_test test_options_heading_style_underlined
  run_test test_options_highlight_bold
  run_test test_options_highlight_double_equal
  run_test test_options_highlight_none
  run_test test_options_keep_inline_images_in_paragraph
  run_test test_options_link_style_reference
  run_test test_options_list_custom_bullets
  run_test test_options_list_indent_tabs
  run_test test_options_list_indent_width_four
  run_test test_options_max_depth_default_unlimited
  run_test test_options_max_depth_truncates
  run_test test_options_max_depth_zero_empty
  run_test test_options_newline_backslash
  run_test test_options_newline_spaces
  run_test test_options_output_format_djot
  run_test test_options_output_format_markdown
  run_test test_options_output_format_plain
  run_test test_options_preprocessing_aggressive
  run_test test_options_preprocessing_minimal
  run_test test_options_preprocessing_remove_forms
  run_test test_options_preserve_tags_iframe
  run_test test_options_skip_images_true
  run_test test_options_strip_newlines
  run_test test_options_strip_tags_div_span
  run_test test_options_strong_em_underscore
  run_test test_options_sub_symbol_tilde
  run_test test_options_sup_symbol_caret
  run_test test_options_whitespace_normalized
  run_test test_options_whitespace_strict
  run_test test_options_wrap_disabled
  run_test test_options_wrap_enabled
}
