#!/usr/bin/env bash
# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: options
set -euo pipefail

test_options_code_block_backticks() {
  # Backticks code block style uses triple backtick fences
  local output
  output=$(html_to_markdown convert)

}

test_options_code_block_tildes() {
  # Tildes code block style uses triple tilde fences
  local output
  output=$(html_to_markdown convert)

}

test_options_escape_asterisks() {
  # escape_asterisks option escapes asterisks in plain text
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_escape_misc() {
  # escape_misc option escapes miscellaneous markdown characters
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_escape_underscores() {
  # escape_underscores option escapes underscores in plain text
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_heading_style_atx() {
  # ATX heading style produces hash-prefixed headings
  local output
  output=$(html_to_markdown convert)

}

test_options_heading_style_atx_closed() {
  # ATX closed heading style adds closing hashes
  local output
  output=$(html_to_markdown convert)

}

test_options_heading_style_underlined() {
  # Underlined heading style produces setext-style headings for h1 and h2
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_list_custom_bullets() {
  # Custom bullet character for unordered lists
  local output
  output=$(html_to_markdown convert)

}

test_options_list_indent_tabs() {
  # Tab indentation type for nested list items
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_max_depth_default_unlimited() {
  # Default max_depth (null) converts deeply nested content fully
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_contains "$val_content" 'Deep content' 'content'
}

test_options_max_depth_truncates() {
  # max_depth truncates content beyond the specified depth
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_contains "$val_content" 'Shallow' 'content'
  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_contains "$val_content" 'Too deep' 'content'
}

test_options_max_depth_zero_empty() {
  # max_depth of 0 produces empty output
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_equals "$val_content" '' 'content'
}

test_options_output_format_djot() {
  # Djot output format produces djot-compatible markup
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_output_format_markdown() {
  # Default markdown output format produces standard markdown
  local output
  output=$(html_to_markdown convert)

}

test_options_output_format_plain() {
  # Plain text output format strips markdown syntax
  local output
  output=$(html_to_markdown convert)

}

test_options_whitespace_normalized() {
  # Normalized whitespace mode collapses multiple spaces
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_whitespace_strict() {
  # Strict whitespace mode preserves whitespace as-is
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

test_options_wrap_disabled() {
  # Wrap option disabled preserves long lines without breaking
  local output
  output=$(html_to_markdown convert)

}

test_options_wrap_enabled() {
  # Wrap option enabled with custom width wraps long lines
  local output
  output=$(html_to_markdown convert)

  local val_content
  val_content=$(echo "$output" | jq -r '.content')
  assert_not_empty "$val_content" 'content'
}

run_tests_options() {
  run_test test_options_code_block_backticks
  run_test test_options_code_block_tildes
  run_test test_options_escape_asterisks
  run_test test_options_escape_misc
  run_test test_options_escape_underscores
  run_test test_options_heading_style_atx
  run_test test_options_heading_style_atx_closed
  run_test test_options_heading_style_underlined
  run_test test_options_list_custom_bullets
  run_test test_options_list_indent_tabs
  run_test test_options_max_depth_default_unlimited
  run_test test_options_max_depth_truncates
  run_test test_options_max_depth_zero_empty
  run_test test_options_output_format_djot
  run_test test_options_output_format_markdown
  run_test test_options_output_format_plain
  run_test test_options_whitespace_normalized
  run_test test_options_whitespace_strict
  run_test test_options_wrap_disabled
  run_test test_options_wrap_enabled
}
